#!/usr/bin/env python3
"""Add drink recipes to reach 500 total"""
import re
import json
import sys

def recipe_to_ts(recipe):
    lines = ['  {']
    for key in ['id', 'slug', 'title', 'shortTitle', 'description', 'image', 'kategori', 'waktu', 'porsi', 'kesulitan', 'rating', 'origin']:
        if key in recipe:
            val = recipe[key]
            if isinstance(val, str):
                val = val.replace('\\', '\\\\').replace('"', '\\"')
                lines.append(f'    {key}: "{val}",')
            elif isinstance(val, (int, float)):
                lines.append(f'    {key}: {val},')
    
    for json_key, ts_key in [('bahan', 'ingredients'), ('ingredients', 'ingredients'), ('cara_buat', 'instructions'), ('cara_but', 'instructions'), ('instructions', 'instructions')]:
        if json_key in recipe and isinstance(recipe[json_key], list):
            lines.append(f'    {ts_key}: [')
            for item in recipe[json_key]:
                item = item.replace('\\', '\\\\').replace('"', '\\"')
                lines.append(f'      "{item}",')
            lines.append('    ],')
            break
    
    field_map = {
        'tips': 'tips', 'sejarah': 'detailedHistory', 'variasi_daerah': 'regionalVariations',
        'teknik_memasak': 'cookingTechnique', 'profil_gizi': 'nutritionalProfile'
    }
    for json_key, ts_key in field_map.items():
        if json_key in recipe and isinstance(recipe[json_key], str) and recipe[json_key]:
            val = recipe[json_key].replace('\\', '\\\\').replace('"', '\\"')
            lines.append(f'    {ts_key}: "{val}",')
    
    lines.append('  }')
    return '\n'.join(lines)

def main():
    with open('src/data/recipes.ts', 'r') as f:
        content = f.read()
    
    existing_slugs = set(re.findall(r'slug:\s*"([^"]+)"', content))
    existing_ids = set(int(x) for x in re.findall(r'id:\s*(\d+)', content))
    max_id = max(existing_ids) if existing_ids else 0
    next_id = max_id + 1
    print(f"Current: {len(existing_slugs)} unique slugs, max ID: {max_id}")
    
    # Load drinks from subagent file
    drinks = [
        {"slug":"es-goyobod","title":"Es Goyobod Recipe: Traditional Sundanese Ice Dessert","shortTitle":"Es Goyobod","description":"Es goyobod is a traditional Sundanese cold dessert from West Java made with hunkue jelly, kelapa muda, alpukat, and coconut milk.","image":"/images/es-goyobod.jpg","kategori":"minuman","waktu":30,"porsi":"4 gelas","kesulitan":"Medium","rating":4.5,"origin":"Subang, West Java","bahan":["200 gram tepung hunkue","1 liter air","200 gram gula pasir","1 butir kelapa muda","1 buah alpukat","500 ml santan","Sirup cocopandan","Es batu","Kacang tanah sangrai"],"cara_buat":["Masak tepung hunkue hingga mengental","Tuang ke cetakan, biarkan set","Potong dadu kecil","Siapkan gelas, masukkan es batu dan potongan hunkue","Tambahkan serutan kelapa dan alpukat","Siram dengan santan dan sirup cocopandan","Taburi kacang tanah sangrai"],"tips":"Hunkue jelly harus cukup firm. Gunakan santan segar dan dingin.","sejarah":"Es goyobod berasal dari dataran Priangan, populer di Subang dan Bandung.","variasi_daerah":"Di Bandung ditambah cincau. Di Tasikmalaya pakai gula aren.","teknik_memasak":"Memasak tepung hunkue hingga mengental, mengiris saat sudah set.","profil_gizi":"Rendah kalori, kaya serat dari hunkue, lemak sehat dari santan dan alpukat."},
        {"slug":"es-blewah","title":"Es Blewah Recipe: Traditional Cantaloupe Ice","shortTitle":"Es Blewah","description":"Es blewah is a refreshing cold drink made from local cantaloupe, served with ice, syrup, and condensed milk. Popular during Ramadan as takjil.","image":"/images/es-blewah.jpg","kategori":"minuman","waktu":15,"porsi":"2 gelas","kesulitan":"Easy","rating":4.3,"origin":"Nationwide","bahan":["1 buah blewah","2 sendok makan gula pasir","200 ml air","Sirup cocopandan","Susu kental manis","Es batu"],"cara_buat":["Belah blewah, buang bijinya","Serut daging blewah","Masukkan blewah serut ke gelas","Tambahkan es batu","Tuang air gula dan sirup","Siram susu kental manis","Sajikan segera"],"tips":"Pilih blewah yang matang sempurna dan harum.","sejarah":"Es blewah populer sebagai takjil saat Ramadan.","variasi_daerah":"Di beberapa daerah ditambah nata de coco atau cincau.","teknik_memasak":"Menserut daging blewah menggunakan garpu atau alat serut.","profil_gizi":"Rendah kalori, kaya vitamin A dan C dari blewah."},
        {"slug":"es-gempol","title":"Es Gempol Recipe: Central Javanese Rice Flour Ice","shortTitle":"Es Gempol","description":"Es gempol is a traditional cold dessert from Central Java made with small balls of rice flour dough in sweet coconut milk soup.","image":"/images/es-gempol.jpg","kategori":"minuman","waktu":30,"porsi":"4 gelas","kesulitan":"Medium","rating":4.4,"origin":"Jepara, Central Java","bahan":["150 gram tepung beras","50 gram tepung tapioka","200 ml air hangat","Pewarna makanan","700 ml santan","100 gram gula pasir","Daun pandan","Es batu"],"cara_buat":["Campur tepung, tambahkan air hangat, uleni hingga kalis","Bulatkan menjadi bola kecil","Rebus hingga mengapung, tiriskan","Rebus santan dengan gula dan pandan","Siapkan gelas, masukkan es batu dan bola gempol","Tuang kuah santan","Sajikan dingin"],"tips":"Bola tepung harus kenyal, tidak keras atau lembek.","sejarah":"Es gempol khas Jepara, dijual pedagang di pasar tradisional.","variasi_daerah":"Di Kudus pakai gula merah. Di beberapa daerah tambah nangka.","teknik_memasak":"Menguleni adonan tepung, membulatkan, merebus hingga mengapung.","profil_gizi":"Karbohidrat dari tepung beras, lemak dari santan, sekitar 200 kcal per porsi."},
        {"slug":"es-laksamana-mengamuk","title":"Es Laksamana Mengamuk Recipe: Riau Mango Milk Ice","shortTitle":"Es Laksamana Mengamuk","description":"Es laksamana mengamuk is a cold dessert from Riau Islands made with fresh mango slices in sweetened condensed milk and ice.","image":"/images/es-laksamana-mengamuk.jpg","kategori":"minuman","waktu":10,"porsi":"2 gelas","kesulitan":"Easy","rating":4.6,"origin":"Riau Islands","bahan":["2 buah mangga matang","200 ml susu kental manis","200 ml air","Es batu"],"cara_buat":["Kupas dan iris mangga tipis memanjang","Masukkan es batu ke gelas","Tata irisan mangga di atas es","Tuangkan susu kental manis","Tambahkan air secukupnya","Aduk perlahan, sajikan"],"tips":"Gunakan mangga harum manis yang matang sempurna.","sejarah":"Nama laksamana mengamuk dari penampilan yang berani dan colorful.","variasi_daerah":"Di Batam ditambah nata de coco. Versi smoothie juga populer.","teknik_memasak":"Mengiris mangga tipis memanjang untuk presentasi yang menarik.","profil_gizi":"Kaya vitamin A dan C dari mangga, kalsium dari susu, sekitar 250 kcal."},
        {"slug":"es-lidah-buaya","title":"Es Lidah Buaya Recipe: West Kalimantan Aloe Vera Ice","shortTitle":"Es Lidah Buaya","description":"Es lidah buaya is a traditional cold drink from West Kalimantan made from aloe vera gel with cincau hitam, basil seeds, and coconut milk.","image":"/images/es-lidah-buaya.jpg","kategori":"minuman","waktu":20,"porsi":"4 gelas","kesulitan":"Medium","rating":4.3,"origin":"West Kalimantan","bahan":["200 gram daging lidah buaya","50 gram cincau hitam","1 sendok makan biji selasih","400 ml santan","100 gram gula aren","Daun pandan","Es batu"],"cara_buat":["Rebus lidah buaya 5 menit, tiriskan dan bilas","Rebus santan dengan pandan, biarkan dingin","Siapkan gelas, masukkan es batu","Tambahkan lidah buaya, cincau, biji selasih","Siram larutan gula aren dan santan dingin","Aduk dan sajikan"],"tips":"Lidah buaya harus direbus untuk menghilangkan lendir. Bilas hingga bersih.","sejarah":"Lidah buaya digunakan dalam obat tradisional Indonesia, diolah jadi minuman segar.","variasi_daerah":"Di Pontianak pakai air kelapa muda. Versi modern tambah nata de coco.","teknik_memasak":"Merebus lidah buaya untuk menghilangkan lendir, memotong dadu.","profil_gizi":"Rendah kalori, kaya vitamin A, C, E, dan B12 dari lidah buaya."},
        {"slug":"es-omu","title":"Es Omu Recipe: Gorontalo Coconut Delight","shortTitle":"Es Omu","description":"Es omu is a traditional cold drink from Gorontalo made with tender coconut flesh, fresh coconut water, and palm sugar.","image":"/images/es-omu.jpg","kategori":"minuman","waktu":10,"porsi":"2 gelas","kesulitan":"Easy","rating":4.4,"origin":"Gorontalo","bahan":["1 butir kelapa muda","100 gram gula aren","Es batu"],"cara_buat":["Buka kelapa, simpan airnya","Kerok daging kelapa menjadi serutan","Larutkan gula aren dalam air panas, biarkan dingin","Masukkan es batu ke gelas","Tambahkan serutan kelapa dan air kelapa","Tambahkan larutan gula aren","Aduk dan sajikan"],"tips":"Pilih kelapa yang berat isinya. Gula aren asli memberikan rasa lebih kaya.","sejarah":"Es omu mencerminkan kesederhanaan masakan Gorontalo, hanya kelapa dan gula aren.","variasi_daerah":"Di Gorontalo ditambah sago pearls atau nangka.","teknik_memasak":"Mengambil daging kelapa dan airnya, melarutkan gula aren.","profil_gizi":"Menyegarkan, rendah kalori, kaya elektrolit dari air kelapa."},
        {"slug":"es-matoa","title":"Es Matoa Recipe: Papuan Matoa Fruit Ice","shortTitle":"Es Matoa","description":"Es matoa is a refreshing cold drink from Papua made with the rare matoa fruit, kolang-kaling, and jelly.","image":"/images/es-matoa.jpg","kategori":"minuman","waktu":15,"porsi":"2 gelas","kesulitan":"Easy","rating":4.5,"origin":"Papua","bahan":["200 gram buah matoa","100 gram kolang-kaling","100 gram jelly cincau","200 ml air","50 gram gula","Sirup","Es batu"],"cara_buat":["Belah matoa, keluarkan isinya","Rebus kolang-kaling hingga empuk","Didihkan air dengan gula, biarkan dingin","Siapkan gelas, masukkan es batu","Tambahkan matoa, kolang-kaling, jelly","Tuang sirup gula dingin","Sajikan"],"tips":"Matoa segar sulit ditemukan di luar Papua, bisa diganti campuran lychee dan longan.","sejarah":"Matoa adalah buah asli Papua, bernilai tinggi dalam budaya Papuan.","variasi_daerah":"Di Jayapura ditambah santan. Di Manokwari pakai susu kedelai.","teknik_memasak":"Mengupas buah matoa dan merebus kolang-kaling.","profil_gizi":"Kaya vitamin C, kalium, dan antioksidan dari matoa."},
        {"slug":"es-samudra","title":"Es Samudra Recipe: Dumai Sea of Flavors Ice","shortTitle":"Es Samudra","description":"Es samudra is a unique cold drink from Dumai, Riau, made with white bread, durian, seaweed, and cocopandan syrup.","image":"/images/es-samudra.jpg","kategori":"minuman","waktu":15,"porsi":"2 gelas","kesulitan":"Easy","rating":4.3,"origin":"Dumai, Riau","bahan":["3 lembar roti tawar","100 gram daging durian","50 gram rumput laut","Sirup cocopandan","Susu kental manis","Es batu"],"cara_buat":["Potong roti menjadi dadu kecil","Siapkan gelas, masukkan es batu","Tambahkan roti, durian haluskan, dan rumput laut","Siram sirup cocopandan dan susu kental manis","Aduk perlahan, sajikan"],"tips":"Gunakan roti yang agak stale agar menyerap sirup lebih baik.","sejarah":"Es samudra dari Dumai, mencerminkan pengaruh Tionghoa-Indonesia.","variasi_daerah":"Di Pekanbaru tanpa roti, fokus durian dengan santan.","teknik_memasak":"Menyusun bahan dalam gelas dengan urutan yang tepat.","profil_gizi":"Kalori tinggi dari roti dan durian, kaya kalium dan vitamin B."},
        {"slug":"es-sunset-papua","title":"Es Sunset Papua Recipe: Papuan Sunset Fruit Ice","shortTitle":"Es Sunset Papua","description":"Es sunset papua is a colorful cold drink from Papua made with orange juice, carrot juice, syrup, and basil seeds.","image":"/images/es-sunset-papua.jpg","kategori":"minuman","waktu":10,"porsi":"2 gelas","kesulitan":"Easy","rating":4.4,"origin":"Papua","bahan":["2 buah jeruk manis","1 buah wortel","200 ml sirup","1 sendok makan biji selasih","Es batu"],"cara_buat":["Peras jeruk dan wortel, saring","Siapkan gelas tinggi, masukkan es batu","Tuang perasan jeruk terlebih dahulu","Tambahkan perasan wortel perlahan untuk gradient","Tambahkan biji selasih dan sirup","Sajikan dengan sedotan"],"tips":"Tuang jus perlahan di belakang sendok untuk efek gradient.","sejarah":"Es sunset papua dibuat untuk merayakan sunset di pantai Papua.","variasi_daerah":"Di Jayapura tambah sari mangga. Di Manokwari pakai sirup rosella.","teknik_memasak":"Menuang cairan berbeda density perlahan untuk membentuk gradient.","profil_gizi":"Sumber vitamin C dari jeruk dan beta-karoten dari wortel, rendah kalori."},
        {"slug":"es-timun-serut","title":"Es Timun Serut Recipe: Aceh Shredded Cucumber Ice","shortTitle":"Es Timun Serut","description":"Es timun serut is a refreshing cold drink from Aceh made with shredded cucumber, lime juice, and sugar.","image":"/images/es-timun-serut.jpg","kategori":"minuman","waktu":10,"porsi":"2 gelas","kesulitan":"Easy","rating":4.5,"origin":"Aceh","bahan":["2 buah mentimun","2 sendok makan gula pasir","200 ml air","2 buah jeruk nipis","Es batu","Daun mint"],"cara_buat":["Kupas mentimun, buang bijinya","Serut mentimun menjadi serutan panjang","Larutkan gula dalam air hangat, biarkan dingin","Siapkan gelas, masukkan es batu dan serutan mentimun","Tuang larutan gula dan peras jeruk nipis","Aduk, hias dengan daun mint"],"tips":"Pilih mentimun segar dan renyah. Buang biji agar tidak terlalu berair.","sejarah":"Es timun serut mencerminkan filosofi Aceh memanfaatkan bahan sederhana dan segar.","variasi_daerah":"Di Aceh ada yang pakai air kelapa. Di Banda Aceh tambah lime cordial.","teknik_memasak":"Menserut mentimun menggunakan alat serut atau julienne peeler.","profil_gizi":"Sangat menyegarkan, rendah kalori, kaya vitamin K dan kalium."},
        {"slug":"es-serbat-kweni","title":"Es Serbat Kweni Recipe: Lampung Mango Kweni Ice","shortTitle":"Es Serbat Kweni","description":"Es serbat kweni is a cold drink from Lampung made from kweni mango mixed with palm sugar.","image":"/images/es-serbat-kweni.jpg","kategori":"minuman","waktu":15,"porsi":"2 gelas","kesulitan":"Easy","rating":4.3,"origin":"Lampung","bahan":["2 buah kweni","100 gram gula aren","200 ml air","Es batu","Daun mint"],"cara_buat":["Kupas kweni, buang biji, potong-potong","Haluskan sebagian kweni dengan garpu","Larutkan gula aren dalam air hangat, saring, dinginkan","Siapkan gelas, masukkan es batu","Tambahkan kweni halus dan potongan","Tuang larutan gula aren dingin","Hias dengan daun mint, sajikan"],"tips":"Kweni punya aroma kuat yang unik. Jika tidak tersedia, campur mangga biasa dengan essence mangga.","sejarah":"Kweni adalah varietas mangga khas Sumatra. Serbat berasal dari bahasa Arab, mencerminkan pengaruh budaya Arab.","variasi_daerah":"Di Palembang kweni juga dipakai dalam rujak.","teknik_memasak":"Menghaluskan kweni dengan garpu untuk mempertahankan tekstur rustic.","profil_gizi":"Kaya vitamin C dan A dari kweni, mineral dari gula aren, sekitar 160 kcal."},
        {"slug":"es-siwalan","title":"Es Siwalan Recipe: Palm Fruit Ice","shortTitle":"Es Siwalan","description":"Es siwalan is a cold dessert drink made with siwalan (borassus palm) fruit, basil seeds, and flavored syrup.","image":"/images/es-siwalan.jpg","kategori":"minuman","waktu":15,"porsi":"2 gelas","kesulitan":"Easy","rating":4.4,"origin":"Nationwide","bahan":["200 gram buah siwalan","1 sendok makan biji selasih","Sirup cocopandan","Susu kental manis","Es batu"],"cara_buat":["Keluarkan buah siwalan dari tempurung, potong-potong","Rendam biji selasih hingga mengembang","Siapkan gelas, masukkan es batu","Tambahkan buah siwalan dan biji selasih","Siram sirup dan susu kental manis","Aduk dan sajikan"],"tips":"Siwalan segar lebih baik dari kaleng. Biji selasih harus benar-benar mengembang.","sejarah":"Siwalan atau lontar sudah dibudidayakan di Indonesia berabad-abad.","variasi_daerah":"Di Jawa Timur pakai gula aren. Di Bali tambah santan.","teknik_memasak":"Mengekstrak buah siwalan dari tempurung yang sangat keras.","profil_gizi":"Rendah kalori, kaya glukosa dan fruktosa, menyegarkan."},
        {"slug":"es-sekemu","title":"Es Sekemu Recipe: Banten Sapodilla Coconut Ice","shortTitle":"Es Sekemu","description":"Es sekemu is a cold drink from Banten made with coconut water, coconut flesh, sapodilla, and basil seeds.","image":"/images/es-sekemu.jpg","kategori":"minuman","waktu":10,"porsi":"2 gelas","kesulitan":"Easy","rating":4.3,"origin":"Banten","bahan":["1 butir kelapa muda","2 buah sapodilla","1 sendok makan biji selasih","Gula pasir atau gula aren","Es batu"],"cara_buat":["Ambil air kelapa dan serut dagingnya","Kupas sapodilla, potong dadu","Siapkan gelas, masukkan es batu","Tambahkan sapodilla, serutan kelapa, biji selasih","Tuang air kelapa muda","Tambahkan gula sesuai selera","Aduk dan sajikan"],"tips":"Sapodilla harus matang tapi tidak terlalu lembek. Kelapa harus muda dengan daging lunak.","sejarah":"Banten memiliki sejarah panjang sebagai pelabuhan rempah, es sekemu mencerminkan budaya pesisir.","variasi_daerah":"Di Serang tambah nangka. Di Anyer pakai susu kental manis.","teknik_memasak":"Mengambil air dan daging kelapa, memotong sapodilla.","profil_gizi":"Menyegarkan, kaya elektrolit dari air kelapa, vitamin C dari sapodilla."},
        {"slug":"es-kelacin","title":"Es Kelacin Recipe: West Sulawesi Grass Jelly Coconut Ice","shortTitle":"Es Kelacin","description":"Es kelacin is a traditional cold drink from West Sulawesi made with coconut flesh and green grass jelly in iced coconut milk.","image":"/images/es-kelacin.jpg","kategori":"minuman","waktu":15,"porsi":"2 gelas","kesulitan":"Easy","rating":4.3,"origin":"West Sulawesi","bahan":["1 butir kelapa muda","100 gram cincau hijau","400 ml santan","100 ml air kelapa","50 gram gula pasir","Daun pandan","Es batu"],"cara_buat":["Rebus santan dengan gula dan pandan, dinginkan","Serut daging kelapa","Potong cincau hijau kecil-kecil","Siapkan gelas, masukkan es batu","Tambahkan serutan kelapa dan cincau","Tuang santan dingin dan air kelapa","Aduk dan sajikan"],"tips":"Gunakan kelapa muda segar dan cincau hijau buatan sendiri untuk rasa terbaik.","sejarah":"Es kelacin mencerminkan tradisi masakan kelapa di Sulawesi Barat.","variasi_daerah":"Di Mamuju tambah sago pearls. Di Makassar pakai sirup merah.","teknik_memasak":"Memasak santan dengan api kecil agar tidak pecah, menambahkan pandan untuk aroma.","profil_gizi":"Kaya lemak sehat dari santan, rendah kalori dari cincau hijau."},
        {"slug":"air-guraka","title":"Air Guraka Recipe: Ternate Ginger Walnut Drink","shortTitle":"Air Guraka","description":"Air guraka is a traditional hot ginger drink from Ternate mixed with palm sugar and crushed walnuts.","image":"/images/air-guraka.jpg","kategori":"minuman","waktu":15,"porsi":"2 gelas","kesulitan":"Easy","rating":4.4,"origin":"Ternate, North Maluku","bahan":["100 gram jahe segar","100 gram gula aren","50 gram kacang kenari","1 liter air","Daun pandan"],"cara_buat":["Didihkan air dengan jahe dimemarkan","Masukkan gula aren dan pandan","Rebus 15 menit hingga berwarna kecokelatan","Saring ke gelas","Taburi kacang kenari tumbuk","Sajikan panas"],"tips":"Gunakan jahe tua yang sudah kekuningan untuk rasa lebih kuat. Kacang kenari bisa diganti kacang biasa.","sejarah":"Ternate adalah salah satu Spice Islands. Air guraka mencerminkan kekayaan rempah Maluku.","variasi_daerah":"Di Tidore ada kopi dabe yang mirip. Di Ambon tambah cengkeh dan pala.","teknik_memasak":"Merebus jahe cukup lama untuk mengekstrak gingerol tanpa pahit berlebihan.","profil_gizi":"Hangat dan metabolism-boosting, gingerol anti-inflamasi, omega-3 dari walnut."},
        {"slug":"sara-ba","title":"Sara'ba Recipe: Makassarese Palm Sugar Ginger Drink","shortTitle":"Sara'ba","description":"Sara'ba is a traditional hot drink from Makassar made from palm sugar and ginger, can be mixed with coconut milk, milk, or raw egg yolk.","image":"/images/sara-ba.jpg","kategori":"minuman","waktu":15,"porsi":"2 gelas","kesulitan":"Easy","rating":4.5,"origin":"Makassar, South Sulawesi","bahan":["100 gram gula aren","50 gram jahe segar","500 ml air","1 kuning telur (opsional)","Susu atau santan (opsional)","Daun pandan"],"cara_buat":["Didihkan air dengan jahe dimemarkan dan pandan","Masukkan gula aren, aduk hingga larut","Rebus 10-15 menit hingga beraroma","Saring ke gelas","Jika pakai telur: kocok kuning telur, tuang sara'ba panas perlahan sambil aduk cepat","Tambahkan susu atau santan jika mau","Sajikan panas"],"tips":"Jika pakai telur mentah, tuang cairan panas perlahan sambil diaduk cepat agar tidak menggumpal.","sejarah":"Sara'ba adalah bagian tak terpisahkan dari budaya Makassar, disajikan saat perayaan.","variasi_daerah":"Di Gowa tambah kayu manis. Di Bulukumba pakai gula merah.","teknik_memasak":"Merebus jahe dengan gentle boiling, tempering telur dengan cara menuang perlahan.","profil_gizi":"Hangat dan menghangatkan, gingerol anti-inflamasi, protein dari telur jika dipakai."}
    ]
    
    # Filter unique slugs
    new_drinks = []
    for recipe in drinks:
        slug = recipe['slug']
        if slug not in existing_slugs:
            recipe['id'] = next_id
            recipe['image'] = f'/images/{slug}.jpg'
            new_drinks.append(recipe)
            existing_slugs.add(slug)
            next_id += 1
            if len(new_drinks) >= 17:  # Only need 17 more to reach 500
                break
    
    print(f"Added {len(new_drinks)} unique drinks (IDs {new_drinks[0]['id']}-{new_drinks[-1]['id']})")
    
    ts_recipes = [recipe_to_ts(r) for r in new_drinks]
    
    arr_end = content.rfind('];')
    if arr_end == -1:
        print("ERROR: Could not find ]; in recipes.ts")
        sys.exit(1)
    
    new_ts = ',\n'.join(ts_recipes)
    new_content = content[:arr_end] + new_ts + ',\n' + content[arr_end:]
    
    with open('src/data/recipes.ts', 'w') as f:
        f.write(new_content)
    
    print(f"Successfully added {len(new_drinks)} drinks to recipes.ts")
    
    with open('src/data/recipes.ts', 'r') as f:
        verify_content = f.read()
    verify_slugs = set(re.findall(r'slug:\s*"([^"]+)"', verify_content))
    verify_ids = set(int(x) for x in re.findall(r'id:\s*(\d+)', verify_content))
    print(f"Verified: {len(verify_slugs)} unique slugs, {len(verify_ids)} total recipes")

if __name__ == '__main__':
    main()
