import re

with open('src/data/recipes.ts') as f:
    content = f.read()

existing_slugs = set(re.findall(r'slug:\s*"([^"]+)"', content))
max_id = max(int(x) for x in re.findall(r'id:\s*(\d+)', content))
nid = max_id + 1

def s(v):
    if isinstance(v, str):
        return v.replace('\\', '\\\\').replace('"', '\\"')
    return str(v)

def R(slug, title, desc, cat, waktu, porsi, diff, rating, origin, ings, instrs, tips=""):
    global nid
    if slug in existing_slugs:
        return None
    existing_slugs.add(slug)
    lid = nid
    nid += 1
    L = ['  {']
    L.append(f'    id: {lid},')
    for k,v in [('slug',slug),('title',title),('shortTitle',title.split(' Recipe')[0]),('description',desc),('image',f'/images/{slug}.jpg'),('kategori',cat),('origin',origin),('porsi',porsi),('kesulitan',diff)]:
        L.append(f'    {k}: "{s(v)}",')
    L.append(f'    waktu: {waktu},')
    L.append(f'    rating: {rating},')
    L.append('    ingredients: [')
    for i in ings:
        L.append(f'      "{s(i)}",')
    L.append('    ],')
    L.append('    instructions: [')
    for i in instrs:
        L.append(f'      "{s(i)}",')
    L.append('    ],')
    if tips:
        L.append(f'    tips: "{s(tips)}",')
    L.append('  }')
    return '\n'.join(L)

recipes = []
def a(*args):
    r = R(*args)
    if r:
        recipes.append(r)

# MAIN DISHES
a("ayam-bakar-madura","Ayam Bakar Madura Recipe","Grilled chicken in sweet soy from Madura","makanan-berat",60,"4 porsi","Medium",4.5,"Madura",["1 chicken cut 8","100ml sweet soy","5 shallots","3 garlic","3cm ginger","2 lemongrass","3 lime leaves","salt"],["Grind shallots garlic ginger","Simmer chicken with spices until tender","Coat with sweet soy","Grill over charcoal until caramelized","Serve with rice and sambal"],"Grill with medium heat.")
a("nasi-goreng-jawa","Nasi Goreng Jawa Recipe","Javanese fried rice with sweet soy","makanan-berat",20,"4 porsi","Easy",4.5,"Java",["500g cold rice","5 shallots","3 garlic","2 tbsp sweet soy","1 tbsp palm sugar","egg","crackers"],["Saute shallots garlic","Add rice sweet soy palm sugar","Stir fry high heat","Serve with fried egg crackers"],"Use cold rice.")
a("sate-madura","Sate Madura Recipe","Madurese chicken satay with peanut sauce","makanan-berat",60,"6 porsi","Medium",4.7,"Madura",["500g chicken cubed","200g peanuts ground","3 tbsp sweet soy","5 shallots","3 garlic","chili","palm sugar","skewers"],["Skewer chicken","Make peanut sauce","Cook sauce with sweet soy palm sugar","Grill over charcoal","Serve with rice cake"],"Grill over charcoal.")
a("nasi-rawon","Nasi Rawon Recipe","Beef black nut soup rice","makanan-berat",90,"4 porsi","Medium",4.5,"East Java",["500g beef","50g kluwek","5 shallots","3 garlic","3cm ginger","2cm galangal","2 lemongrass","3 lime leaves","bean sprouts","fried shallots"],["Grind shallots garlic ginger galangal kluwek","Saute add lemongrass lime leaves","Add beef cook tender","Serve with bean sprouts fried shallots"],"Kluwek must be finely ground.")
a("bakso-mercon","Bakso Mercon Recipe","Firecracker meatball with chilies","makanan-berat",60,"20 buah","Medium",4.4,"Yogyakarta",["500g ground beef","200g tapioca","5 garlic","salt","pepper","whole chilies","ice water"],["Grind garlic mix beef tapioca","Add salt pepper ice water knead","Form balls insert chili","Boil until floating","Serve in spicy broth"],"Use ice water for springy texture.")
a("sate-padang","Sate Padang Recipe","Padang satay with yellow sauce","makanan-berat",90,"6 porsi","Medium",4.7,"Padang",["500g beef","3cm turmeric","5cm ginger","3cm galangal","5 red chilies","1 lemongrass","200ml coconut milk","rice cake"],["Skewer beef","Grind spices","Saute paste add coconut milk thick","Grill skewers","Serve with rice cake yellow sauce"],"Yellow sauce should be thick.")
a("ayam-goreng-kremes","Ayam Goreng Kremes Recipe","Fried chicken with crispy kremes","makanan-berat",60,"4 porsi","Medium",4.5,"East Java",["1 chicken cut 8","500ml coconut milk","3 bay leaves","2 lemongrass","2cm galangal","salt","rice flour batter","turmeric"],["Simmer chicken coconut milk spices tender","Make thin rice flour batter turmeric","Deep fry chicken golden","Drizzle batter for kremes"],"Spice infusion before frying key.")
a("soto-ayam","Soto Ayam Recipe","Indonesian chicken soup yellow broth","makanan-berat",60,"4 porsi","Easy",4.6,"Nationwide",["500g chicken","1 liter broth","3cm turmeric","5 shallots","3 garlic","2 lemongrass","3 lime leaves","vermicelli","boiled egg","fried shallots"],["Grind turmeric shallots garlic","Saute add lemongrass lime leaves","Pour broth boil","Add chicken vermicelli egg","Serve fried shallots lime"],"Free range chicken for richer broth.")
a("gado-gado","Gado Gado Recipe","Mixed vegetables peanut dressing","makanan-berat",30,"4 porsi","Easy",4.5,"Jakarta",["Mixed vegetables","200g peanuts","3 red chilies","3 shallots","2 garlic","palm sugar","salt","water","crackers","boiled egg"],["Blanch vegetables","Grind peanuts chilies shallots garlic","Add palm sugar salt water","Arrange vegetables pour dressing","Add crackers egg"],"Blanch briefly for crunch.")
a("nasi-uduk","Nasi Uduk Recipe","Fragrant coconut rice Betawi","makanan-berat",45,"4 porsi","Easy",4.4,"Jakarta",["500g rice","400ml coconut milk","2 lemongrass","3 bay leaves","3cm galangal","salt"],["Cook rice coconut milk lemongrass bay leaves galangal salt","Cook like regular rice","Fluff serve"],"Do not open lid while cooking.")
a("sop-buntut","Sop Buntut Recipe","Oxtail soup vegetables","makanan-berat",120,"4 porsi","Medium",4.5,"Java",["500g oxtail","1 liter water","5 shallots","3 garlic","3cm ginger","2cm galangal","3 bay leaves","carrots potatoes tomatoes","fried shallots scallions"],["Boil oxtail tender 1-2hrs","Grind shallots garlic ginger galangal","Saute add bay leaves","Pour broth boil","Add vegetables","Serve fried shallots scallions"],"Oxtail must be very tender.")
a("nasi-tumpeng","Nasi Tumpeng Recipe","Cone yellow rice celebrations","makanan-berat",120,"10 porsi","Hard",4.6,"Java",["1kg rice","1 liter coconut milk","10cm turmeric","5 lemongrass","10 bay leaves","salt","side dishes"],["Cook yellow rice coconut milk turmeric lemongrass bay leaves","Mold into cone","Arrange side dishes around","Garnish vegetables","Serve at celebrations"],"Fresh turmeric for vibrant color.")
a("opor-ayam","Opor Ayam Recipe","Chicken coconut milk curry","makanan-berat",60,"4 porsi","Easy",4.5,"Java",["1 chicken cut 8","400ml coconut milk","5 shallots","3 garlic","3cm ginger","2cm galangal","3 bay leaves","2 lemongrass","salt"],["Grind shallots garlic ginger galangal","Saute add bay leaves lemongrass","Add chicken stir","Pour coconut milk cook","Season"],"Do not boil coconut milk vigorously.")
a("bakso-sapi","Bakso Sapi Recipe","Beef meatball soup","makanan-berat",60,"20 buah","Medium",4.5,"Nationwide",["500g ground beef","200g tapioca","5 garlic","salt","pepper","ice water","vermicelli scallions fried shallots noodles"],["Grind garlic mix beef tapioca","Add salt pepper ice water knead","Form balls","Boil floating","Serve broth vermicelli scallions"],"Ice water for springy texture.")
a("nasi-campur","Nasi Campur Recipe","Mixed rice side dishes","makanan-berat",60,"4 porsi","Easy",4.4,"Nationwide",["Rice","chicken","beef","vegetables","sambal","fried egg","crackers","sweet soy"],["Prepare rice","Arrange side dishes","Add sambal vegetables egg crackers","Serve complete meal"],"Balanced variety of proteins vegetables carbs.")
a("nasi-ayam-bakar","Nasi Ayam Bakar Recipe","Grilled chicken rice","makanan-berat",60,"4 porsi","Medium",4.5,"Nationwide",["1 chicken cut 8","100ml sweet soy","5 shallots","3 garlic","3cm ginger","2 lemongrass","3 lime leaves","salt","rice vegetables sambal"],["Grind shallots garlic ginger","Simmer chicken spices lemongrass lime leaves tender","Coat sweet soy","Grill charcoal caramelized","Serve rice vegetables sambal"],"Simmer first to infuse before grilling.")
a("sate-lilit","Satay Lilit Recipe","Balinese minced satay lemongrass","makanan-berat",45,"6 porsi","Medium",4.5,"Bali",["500g minced chicken","grated coconut ground","5 shallots","3 garlic","3cm ginger","3cm turmeric","2cm galangal","lime leaves","lemongrass stalks"],["Grind shallots garlic ginger turmeric galangal","Mix minced meat coconut","Add lime leaves","Wrap lemongrass stalks","Grill charcoal"],"Grill over charcoal smoky.")
a("sop-iga","Sop Iga Recipe","Beef rib soup","makanan-berat",120,"4 porsi","Medium",4.5,"Java",["500g beef ribs","1 liter water","5 shallots","3 garlic","3cm ginger","2cm galangal","3 bay leaves","2 lemongrass","carrots potatoes tomatoes","fried shallots scallions"],["Boil ribs tender 1-2hrs","Grind shallots garlic ginger galangal","Saute add bay leaves lemongrass","Pour broth boil","Add vegetables","Serve fried shallots scallions"],"Ribs must be very tender.")
a("nasi-rawon-setan","Nasi Rawon Setan Recipe","Extremely spicy black beef soup","makanan-berat",90,"4 porsi","Medium",4.4,"East Java",["500g beef","50g kluwek","20 chilies","5 shallots","3 garlic","3cm ginger","2cm galangal","2 lemongrass","bean sprouts fried shallots"],["Grind shallots garlic ginger galangal kluwek chilies","Saute add lemongrass","Add beef tender","Serve bean sprouts fried shallots"],"Very spicy use caution.")
a("nasi-ayam-bakar-madura","Nasi Ayam Bakar Madura Recipe","Madurese grilled chicken rice","makanan-berat",60,"4 porsi","Medium",4.5,"Madura",["1 chicken cut 8","100ml sweet soy","5 shallots","3 garlic","3cm ginger","2 lemongrass","3 lime leaves","salt","rice vegetables sambal"],["Grind shallots garlic ginger","Simmer chicken spices tender","Coat sweet soy","Grill charcoal caramelized","Serve rice vegetables sambal"],"More sweet soy Madura style.")
a("soto-madura","Soto Madura Recipe","Madurese chicken soup","makanan-berat",60,"4 porsi","Easy",4.4,"Madura",["500g chicken","1 liter broth","3cm turmeric","5 shallots","3 garlic","2 lemongrass","vermicelli boiled egg","fried shallots scallions"],["Grind turmeric shallots garlic","Saute add lemongrass","Pour broth boil","Add chicken vermicelli egg","Serve fried shallots scallions"],"Free range chicken richer broth.")
a("nasi-ayam-bakar-kecap","Nasi Ayam Bakar Kecap Recipe","Sweet soy grilled chicken rice","makanan-berat",60,"4 porsi","Easy",4.4,"Java",["1 chicken cut 8","150ml sweet soy","5 shallots","3 garlic","3cm ginger","2 lemongrass","3 lime leaves","salt","rice vegetables sambal"],["Grind shallots garlic ginger","Simmer chicken spices tender","Coat generous sweet soy","Grill charcoal caramelized","Serve rice vegetables sambal"],"More sweet soy sweeter result.")
a("nasi-panggang","Nasi Panggang Recipe","Grilled rice banana leaf","makanan-berat",45,"4 porsi","Easy",4.3,"Java",["warm rice","banana leaves","chicken fish egg","sambal","vegetables"],["Place rice banana leaf","Add protein sambal","Wrap toothpick","Grill slightly charred","Serve vegetables"],"Warm rice when wrapping best aroma.")
a("sate-buntal","Satay Buntal Recipe","Stuffed chicken skin satay","makanan-berat",45,"6 porsi","Medium",4.3,"Java",["chicken skin","minced chicken","shallots garlic","coriander pepper","salt","skewers","peanut sauce"],["Clean skin","Grind spices mix minced chicken","Stuff into skin","Skewer grill","Serve peanut sauce"],"Skin thoroughly cleaned.")
a("nasi-goreng-gila","Nasi Goreng Gila Recipe","Crazy fried rice mixed toppings","makanan-berat",25,"4 porsi","Easy",4.3,"Jakarta",["500g cold rice","sausage meatballs egg","cabbage carrot","5 shallots","3 garlic","2 tbsp sweet soy","salt","crackers"],["Saute shallots garlic","Add sausage meatballs vegetables","Add rice sweet soy salt","Stir fry high heat","Serve egg crackers"],"High heat for wok hei.")
a("sop-sopan","Sop Sopan Recipe","Mixed vegetable soup","makanan-berat",30,"4 porsi","Easy",4.2,"Java",["Mixed vegetables","5 shallots","3 garlic","3cm ginger","salt pepper","scallions fried shallots"],["Saute shallots garlic ginger","Add water boil","Hard vegetables first","Soft vegetables later","Season scallions fried shallots"],"Cook by vegetable time.")
a("nasi-dabu-dabu","Nasi Dabu Dabu Recipe","Manado rice fresh spicy salsa","makanan-berat",30,"4 porsi","Easy",4.4,"Manado",["rice","grilled fish","tomato shallots chilies basil lime juice salt","vegetables"],["Make dabu dabu dice tomato shallots chilies basil","Add lime juice salt","Serve rice grilled fish","Pour dabu dabu","Add vegetables"],"Freshly made dabu dabu.")
a("nasi-kotak","Nasi Kotak Recipe","Boxed rice meal events","makanan-berat",60,"10 porsi","Easy",4.3,"Nationwide",["rice","chicken","rendang gulai","vegetables","boiled egg","sambal","crackers","box"],["Prepare side dishes","Prepare boxes","Rice bottom","Arrange sides","Add sambal crackers","Close serve"],"Balanced variety.")
a("sop-ayam-bening","Sop Ayam Bening Recipe","Clear chicken soup","makanan-berat",45,"4 porsi","Easy",4.3,"Java",["500g chicken","1 liter water","5 shallots","3 garlic","3cm ginger","carrot potato green bean tomato","salt pepper","scallions fried shallots"],["Saute shallots garlic ginger","Add water boil","Add chicken tender","Hard vegetables first","Soft later","Season scallions fried shallots"],"Cook by vegetable time.")
a("sate-sapi","Sate Sapi Recipe","Beef satay peanut sauce","makanan-berat",45,"6 porsi","Easy",4.5,"Java",["500g beef cubed","200g peanuts ground","3 tbsp sweet soy","5 shallots","3 garlic","chili","palm sugar","skewers","rice cake"],["Skewer beef","Make peanut sauce","Cook sauce sweet soy palm sugar","Grill charcoal","Serve rice cake"],"Do not overcook beef.")
a("nasi-kuning","Nasi Kuning Recipe","Turmeric yellow rice","makanan-berat",45,"4 porsi","Easy",4.4,"Java",["500g rice","400ml coconut milk","3cm turmeric","2 lemongrass","3 bay leaves","salt"],["Cook rice coconut milk turmeric lemongrass bay leaves salt","Cook like regular rice","Fluff serve"],"Fresh turmeric vibrant color.")
a("sate-padang-kuah","Sate Padang Kuah Recipe","Padang satay extra gravy","makanan-berat",90,"6 porsi","Medium",4.6,"Padang",["500g beef","3cm turmeric","5cm ginger","3cm galangal","5 red chilies","1 lemongrass","200ml coconut milk","rice cake"],["Skewer beef","Grind spices","Saute paste add coconut milk thick","Grill skewers","Serve rice cake generous sauce"],"Extra gravy.")
a("nasi-goreng-seafood","Nasi Goreng Seafood Recipe","Seafood fried rice","makanan-berat",30,"4 porsi","Medium",4.4,"Nationwide",["500g cold rice","200g shrimp","150g squid","5 shallots","3 garlic","2 tbsp sweet soy","salt","egg crackers"],["Saute shallots garlic","Add shrimp squid half done","Add rice sweet soy salt","Stir fry high heat","Serve egg crackers"],"Fresh seafood do not overcook.")
a("sop-kambing","Sop Kambing Recipe","Goat soup","makanan-berat",90,"4 porsi","Medium",4.5,"Java",["500g goat","1 liter water","5 shallots","3 garlic","3cm ginger","2cm galangal","3 bay leaves","2 lemongrass","carrot potato tomato","fried shallots scallions lime"],["Boil goat tender","Grind shallots garlic ginger galangal","Saute add bay leaves lemongrass","Pour broth boil","Add vegetables","Serve fried shallots scallions lime"],"Goat must be very tender.")
a("nasi-goreng-kambing","Nasi Goreng Kambing Recipe","Goat fried rice Jakarta","makanan-berat",30,"4 porsi","Medium",4.5,"Jakarta",["500g cold rice","300g goat cubed","5 shallots","3 garlic","3cm ginger","2 tbsp sweet soy","salt","egg pickles crackers"],["Saute shallots garlic ginger","Add goat cook done","Add rice sweet soy salt","Stir fry high heat","Serve egg pickles crackers"],"Goat tender well seasoned.")
a("nasi-goreng-kampung","Nasi Goreng Kampung Recipe","Village fried rice anchovies","makanan-berat",20,"4 porsi","Easy",4.4,"Java",["500g cold rice","50g anchovies","100g petai","5 shallots","3 garlic","2 tbsp sweet soy","egg crackers"],["Saute shallots garlic","Add anchovies petai briefly","Add rice sweet soy","Stir fry high heat","Serve egg crackers"],"High heat wok hei.")
a("sate-ayam","Sate Ayam Recipe","Chicken satay peanut sauce","makanan-berat",45,"6 porsi","Easy",4.6,"Nationwide",["500g chicken cubed","200g peanuts ground","3 tbsp sweet soy","5 shallots","3 garlic","chili","palm sugar","skewers","rice cake"],["Skewer chicken","Make peanut sauce","Cook sauce sweet soy palm sugar","Grill charcoal","Serve rice cake"],"Grill charcoal authentic.")
a("nasi-goreng-mawut","Nasi Goreng Mawut Recipe","Mixed rice noodle fried rice","makanan-berat",25,"4 porsi","Easy",4.3,"Java",["300g cold rice","200g noodles","mixed vegetables","5 shallots","3 garlic","2 tbsp sweet soy","egg crackers","salt"],["Saute shallots garlic","Add vegetables briefly","Add rice noodles sweet soy salt","Stir fry high heat","Serve egg crackers"],"Noodles pre-soaked hot water.")
a("sop-buntut-madu","Sop Buntut Madu Recipe","Honey oxtail soup","makanan-berat",120,"4 porsi","Medium",4.4,"Java",["500g oxtail","1 liter water","50ml honey","5 shallots","3 garlic","3cm ginger","2cm galangal","3 bay leaves","carrot potato tomato","fried shallots scallions"],["Boil oxtail tender","Grind shallots garlic ginger galangal","Saute add bay leaves","Pour broth boil","Add honey stir","Add vegetables","Serve fried shallots scallions"],"Add honey at end preserve flavor.")
a("nasi-goreng-truffle","Nasi Goreng Truffle Recipe","Truffle fried rice","makanan-berat",25,"4 porsi","Medium",4.4,"Jakarta",["500g cold rice","2 tsp truffle oil","300g meat seafood","5 shallots","3 garlic","egg crackers","salt","scallions"],["Saute shallots garlic","Add meat seafood done","Add rice salt stir fry high heat","Drizzle truffle oil","Serve egg scallions"],"Truffle oil at end preserve aroma.")
a("sop-kaki-sapi","Sop Kaki Sapi Recipe","Beef leg soup collagen","makanan-berat",120,"4 porsi","Medium",4.4,"Java",["500g beef leg","1 liter water","5 shallots","3 garlic","3cm ginger","2cm galangal","3 bay leaves","2 lemongrass","salt","fried shallots scallions lime"],["Boil leg tender 2-3hrs collagen","Grind shallots garlic ginger galangal","Saute add bay leaves lemongrass","Pour broth boil","Serve thick broth fried shallots scallions lime"],"Boil very long for collagen.")
a("nasi-tumpeng-mini","Nasi Tumpeng Mini Recipe","Small cone yellow rice individual","makanan-berat",60,"4 porsi","Medium",4.3,"Java",["500g rice","500ml coconut milk","5cm turmeric","3 lemongrass","5 bay leaves","salt","chicken egg tempe vegetables"],["Cook yellow rice coconut milk turmeric lemongrass bay leaves","Mold small cones","Arrange sides around each","Serve individual"],"Individual tumpeng servings.")

# DRINKS
a("es-goyobod","Es Goyobod Recipe","Sundanese ice dessert","minuman",30,"4 gelas","Medium",4.5,"Subang",["200g hunkue flour","1 liter water","200g sugar","1 coconut","1 avocado","500ml coconut milk","cocopandan syrup","ice","roasted peanuts"],["Cook hunkue flour until thick","Pour mold set cool","Dice small","Glass ice hunkue pieces","Add coconut avocado","Drizzle coconut milk syrup","Top roasted peanuts"],"Hunkue jelly must be firm.")
a("es-blewah","Es Blewah Recipe","Cantaloupe ice","minuman",15,"2 gelas","Easy",4.3,"Nationwide",["1 cantaloupe","2 tbsp sugar","200ml water","cocopandan syrup","condensed milk","ice"],["Halve cantaloupe remove seeds","Shred flesh","Glass ice shredded cantaloupe","Add sugar water syrup","Drizzle condensed milk","Serve immediately"],"Ripe fragrant cantaloupe.")
a("es-gempol","Es Gempol Recipe","Central Java rice flour ice","minuman",30,"4 gelas","Medium",4.4,"Jepara",["150g rice flour","50g tapioca","200ml warm water","food coloring","700ml coconut milk","100g sugar","pandan leaf","ice"],["Mix flours warm water knead pliable","Form small balls","Boil until floating drain","Boil coconut milk sugar pandan","Glass ice balls","Pour coconut milk serve cold"],"Balls must be chewy not hard.")
a("es-laksamana-mengamuk","Es Laksamana Mengamuk Recipe","Riau mango milk ice","minuman",10,"2 gelas","Easy",4.6,"Riau Islands",["2 ripe mangoes","200ml condensed milk","200ml water","ice"],["Peel mango slice thin long","Glass ice mango slices","Pour condensed milk","Add water adjust thickness","Serve immediately"],"Use harum manis mango.")
a("es-lidah-buaya","Es Lidah Buaya Recipe","Aloe vera ice West Kalimantan","minuman",20,"4 gelas","Medium",4.3,"West Kalimantan",["200g aloe vera","50g black grass jelly","1 tbsp basil seeds","400ml coconut milk","100g palm sugar","pandan leaf","ice"],["Boil aloe vera 5min drain rinse","Boil coconut milk pandan cool","Glass ice","Add aloe vera grass jelly basil seeds","Pour palm sugar syrup coconut milk","Stir serve"],"Boil aloe vera remove slime.")
a("es-omu","Es Omu Recipe","Gorontalo coconut delight","minuman",10,"2 gelas","Easy",4.4,"Gorontalo",["1 young coconut","100g palm sugar","ice"],["Open coconut save water","Scrape flesh shreds","Dissolve palm sugar water cool","Glass ice coconut shreds water","Add palm sugar syrup","Stir serve"],"Fresh young coconut best.")
a("es-matoa","Es Matoa Recipe","Papuan matoa fruit ice","minuman",15,"2 gelas","Easy",4.5,"Papua",["200g matoa fruit","100g sugar palm fruit","100g grass jelly","200ml water","50g sugar","syrup","ice"],["Halve matoa extract flesh","Boil sugar palm fruit tender","Boil water sugar cool","Glass ice matoa sugar palm fruit jelly","Pour syrup cool","Serve"],"Matoa rare outside Papua.")
a("es-samudra","Es Samudra Recipe","Dumai sea of flavors ice","minuman",15,"2 gelas","Easy",4.3,"Dumai Riau",["3 slices white bread","100g durian flesh","50g seaweed","cocopandan syrup","condensed milk","ice"],["Dice bread small","Glass ice bread durian seaweed","Drizzle cocopandan syrup condensed milk","Stir gently serve"],"Day-old bread absorbs syrup better.")
a("es-sunset-papua","Es Sunset Papua Recipe","Papuan sunset fruit ice","minuman",10,"2 gelas","Easy",4.4,"Papua",["2 oranges","1 carrot","200ml syrup","1 tbsp basil seeds","ice"],["Squeeze orange and carrot strain","Glass ice high","Pour orange juice first","Add carrot juice slowly for gradient","Add basil seeds syrup","Serve with straw"],"Pour slowly over spoon for gradient.")
a("es-timun-serut","Es Timun Serut Recipe","Aceh shredded cucumber ice","minuman",10,"2 gelas","Easy",4.5,"Aceh",["2 cucumbers","2 tbsp sugar","200ml water","2 limes","ice","mint leaves"],["Peel cucumber remove seeds","Shred long strips","Dissolve sugar water cool","Glass ice shredded cucumber","Pour sugar water squeeze lime","Garnish mint serve"],"Fresh crisp cucumber remove seeds.")
a("es-serbat-kweni","Es Serbat Kweni Recipe","Lampung kweni mango ice","minuman",15,"2 gelas","Easy",4.3,"Lampung",["2 kweni mangoes","100g palm sugar","200ml water","ice","mint leaves"],["Peel kweni remove seed cut pieces","Mash some with fork","Dissolve palm sugar water strain cool","Glass ice mashed kweni pieces","Pour palm sugar syrup cool","Garnish mint serve"],"Kweni very distinctive aroma.")
a("es-siwalan","Es Siwalan Recipe","Palm fruit ice","minuman",15,"2 gelas","Easy",4.4,"Nationwide",["200g siwalan fruit","1 tbsp basil seeds","cocopandan syrup","condensed milk","ice"],["Extract siwalan from shell cut pieces","Soak basil seeds expand","Glass ice siwalan basil seeds","Drizzle syrup condensed milk","Stir serve"],"Fresh siwalan best.")
a("es-sekemu","Es Sekemu Recipe","Banten sapodilla coconut ice","minuman",10,"2 gelas","Easy",4.3,"Banten",["1 young coconut","2 sapodilla","1 tbsp basil seeds","sugar or palm sugar","ice"],["Take coconut water scrape flesh","Peel sapodilla dice small","Glass ice sapodilla coconut shreds basil seeds","Pour coconut water","Add sugar serve"],"Sapodilla ripe not overripe.")
a("es-kelacin","Es Kelacin Recipe","West Sulawesi grass jelly coconut ice","minuman",15,"2 gelas","Easy",4.3,"West Sulawesi",["1 young coconut","100g green grass jelly","400ml coconut milk","100ml coconut water","50g sugar","pandan leaf","ice"],["Boil coconut milk sugar pandan cool","Scrape coconut flesh","Dice grass jelly small","Glass ice coconut shreds grass jelly","Pour coconut milk cool coconut water","Stir serve"],"Fresh young coconut best flavor.")
a("air-guraka","Air Guraka Recipe","Ternate ginger walnut drink hot","minuman",15,"2 gelas","Easy",4.4,"Ternate",["100g fresh ginger","100g palm sugar","50g kenari nuts","1 liter water","pandan leaf"],["Boil water crushed ginger","Add palm sugar pandan","Simmer 15min brown aromatic","Strain into glass","Top crushed kenari nuts","Serve hot"],"Use old yellow ginger stronger flavor.")
a("sara-ba","Sara Ba Recipe","Makassarese palm sugar ginger drink","minuman",15,"2 gelas","Easy",4.5,"Makassar",["100g palm sugar","50g fresh ginger","500ml water","1 egg yolk optional","milk or coconut milk optional","pandan leaf"],["Boil water crushed ginger pandan","Add palm sugar dissolve","Simmer 10-15min aromatic","Strain into glass","If egg whisk yolk pour hot sara ba slowly whisk fast","Add milk optional serve hot"],"Temper egg slowly whisk fast.")

# ADDITIONAL MAIN DISHES TO REACH 90
a("sop-konro-bakar","Sop Konro Bakar Recipe","Grilled Makassar beef rib soup","makanan-berat",120,"4 porsi","Medium",4.6,"Makassar",["500g beef ribs","100g peanuts ground","5 shallots","3 garlic","3cm ginger","3cm turmeric","2 lemongrass","3 lime leaves","salt","rice cake"],["Boil ribs tender","Grill ribs slightly charred","Grind shallots garlic ginger turmeric","Saute add lemongrass lime leaves","Pour broth add peanuts boil","Add grilled ribs thick","Serve rice cake"],"Grilling adds smoky flavor.")
a("nasi-goreng-kambing-gulai","Nasi Goreng Kambing Gulai Recipe","Goat fried rice curry spices","makanan-berat",30,"4 porsi","Medium",4.4,"Jakarta",["500g cold rice","300g goat","curry spices chili shallots garlic turmeric ginger","coconut milk","salt","egg pickles crackers"],["Cook goat curry spices tender","Saute additional spices","Add rice stir fry high heat","Serve egg pickles crackers"],"Curry spices unique.")
a("nasi-ayam-penyet","Nasi Ayam Penyet Recipe","Smashed fried chicken rice","makanan-berat",45,"4 porsi","Easy",4.5,"East Java",["1 chicken cut 8","turmeric ginger garlic salt","sambal red chilies shallots garlic shrimp paste salt","steamed rice","vegetables cucumber basil"],["Season chicken turmeric ginger garlic salt","Deep fry golden crispy","Make fresh sambal grind chilies shallots garlic shrimp paste","Smash chicken on cobek sambal","Serve steamed rice vegetables"],"Chicken fried very crispy.")
a("sate-kambing","Sate Kambing Recipe","Goat satay sweet soy","makanan-berat",45,"6 porsi","Easy",4.6,"Java",["500g goat cubed","sweet soy","shallots garlic","coriander pepper","salt","skewers","tomato shallot chili lime condiment","rice cake"],["Season goat ground spices","Skewer meat","Grill charcoal done","Serve sweet soy","Add condiment tomato shallot chili lime"],"Do not overcook goat.")
a("sop-konro-makassar","Sop Konro Makassar Recipe","Authentic Makassar beef rib soup","makanan-berat",120,"4 porsi","Medium",4.7,"Makassar",["500g beef ribs","150g peanuts ground","5 shallots","3 garlic","3cm ginger","3cm turmeric","2 lemongrass","3 lime leaves","salt","rice cake"],["Boil ribs very tender","Grind shallots garlic ginger turmeric","Saute add lemongrass lime leaves","Pour broth add peanuts boil","Add ribs thick rich","Serve rice cake"],"Peanuts make broth thick distinctive.")
a("sop-konro-bakso","Sop Konro Bakso Recipe","Makassar rib soup meatballs","makanan-berat",120,"4 porsi","Medium",4.5,"Makassar",["500g beef ribs","200g meatballs","100g peanuts ground","5 shallots","3 garlic","3cm ginger","3cm turmeric","2 lemongrass","3 lime leaves","salt","rice cake"],["Boil ribs tender","Grind shallots garlic ginger turmeric","Saute add lemongrass lime leaves","Pour broth add peanuts boil","Add ribs meatballs thick","Serve rice cake"],"Meatballs add texture.")
a("nasi-goreng-seafood-premium","Nasi Goreng Seafood Premium Recipe","Premium seafood fried rice","makanan-berat",30,"4 porsi","Medium",4.5,"Jakarta",["500g cold premium rice","300g jumbo shrimp","200g squid","200g snapper fillet","5 shallots","3 garlic","2 tbsp sweet soy","premium egg crackers","salt"],["Saute shallots garlic","Add premium seafood half done","Add rice sweet soy salt","Stir fry high heat","Serve premium egg crackers"],"Premium fresh seafood.")
a("sop-kaki-sapi-presto","Sop Kaki Sapi Presto Recipe","Pressure cooker beef leg soup","makanan-berat",60,"4 porsi","Easy",4.3,"Java",["500g beef leg","1 liter water","5 shallots","3 garlic","3cm ginger","2cm galangal","3 bay leaves","salt","fried shallots scallions lime"],["Pressure cook leg tender 30-40min","Grind shallots garlic ginger galangal","Saute add bay leaves","Pour broth boil","Serve fried shallots scallions lime"],"Pressure cooker speeds process.")
a("nasi-goreng-kambing-gulai-premium","Nasi Goreng Kambing Gulai Premium Recipe","Premium goat fried rice curry","makanan-berat",30,"4 porsi","Medium",4.5,"Jakarta",["500g cold premium rice","400g premium goat","premium curry spices","coconut milk","salt","premium egg pickles crackers"],["Cook premium goat curry tender","Saute premium spices","Add premium rice stir fry high heat","Serve premium egg pickles crackers"],"Premium goat and spices.")
a("sop-konro-bakso-premium","Sop Konro Bakso Premium Recipe","Premium Makassar rib soup meatballs","makanan-berat",120,"4 porsi","Hard",4.6,"Makassar",["700g premium beef ribs large","200g premium meatballs","200g premium peanuts ground","7 premium shallots","5 garlic","5cm premium ginger","5cm premium turmeric","3 premium lemongrass","5 premium lime leaves","salt","premium rice cake"],["Boil premium ribs tender","Grind premium shallots garlic ginger turmeric","Saute add premium lemongrass lime leaves","Pour broth add premium peanuts boil","Add premium ribs meatballs thick","Serve premium rice cake"],"All premium ingredients.")
a("nasi-goreng-truffle-premium","Nasi Goreng Truffle Premium Recipe","Premium truffle fried rice","makanan-berat",25,"4 porsi","Medium",4.5,"Jakarta",["500g premium cold rice","3 tsp premium truffle oil","300g premium wagyu or seafood","5 premium shallots","3 garlic","premium egg crackers","salt","premium scallions"],["Saute premium shallots garlic","Add premium wagyu or seafood done","Add premium rice salt stir fry high heat","Drizzle premium truffle oil","Serve premium egg scallions"],"Premium truffle oil and wagyu.")
a("sop-iga-bakar-premium","Sop Iga Bakar Premium Recipe","Premium grilled beef rib soup","makanan-berat",120,"4 porsi","Hard",4.6,"Jakarta",["700g premium beef ribs large","1 liter water","7 premium shallots","5 garlic","5cm premium ginger","3cm premium galangal","5 premium bay leaves","premium carrot potato premium tomato","salt","premium fried shallots scallions lime"],["Boil premium ribs tender","Grill premium ribs slightly charred","Grind premium shallots garlic ginger galangal","Saute add premium bay leaves","Pour broth boil","Add premium grilled ribs vegetables","Serve premium fried shallots scallions lime"],"Grilling adds premium smoky.")
a("sop-ayam-bening-jawa","Sop Ayam Bening Jawa Recipe","Javanese clear chicken soup","makanan-berat",45,"4 porsi","Easy",4.3,"Java",["500g chicken","1 liter water","5 shallots","3 garlic","3cm ginger","carrot potato green bean tomato","salt pepper","scallions fried shallots"],["Saute shallots garlic ginger","Add water boil","Add chicken tender","Hard vegetables first","Soft later","Season scallions fried shallots"],"Simple Javanese home style.")
a("nasi-uduk-betawi","Nasi Uduk Betawi Recipe","Betawi coconut rice","makanan-berat",45,"4 porsi","Easy",4.4,"Jakarta",["500g rice","400ml coconut milk","2 lemongrass","3 bay leaves","3cm galangal","salt"],["Cook rice coconut milk lemongrass bay leaves galangal salt","Cook like regular rice","Fluff serve Betawi side dishes"],"Betawi style.")
a("sop-ayam-bening-jawa-premium","Sop Ayam Bening Jawa Premium Recipe","Premium Javanese clear chicken soup","makanan-berat",45,"4 porsi","Easy",4.4,"Java",["1 free range chicken","1 liter water","7 premium shallots","5 garlic","5cm premium ginger","premium carrot potato green bean tomato","salt pepper","premium scallions fried shallots"],["Saute premium shallots garlic ginger","Add water boil","Add free range chicken tender","Premium hard vegetables first","Premium soft vegetables","Serve premium scallions fried shallots"],"Free range chicken premium vegetables.")
a("nasi-ayam-bakar-madura-premium-khusus","Nasi Ayam Bakar Madura Premium Khusus Recipe","Special premium Madurese grilled chicken","makanan-berat",60,"4 porsi","Hard",4.7,"Madura",["1 premium free range chicken cut 8","200ml best sweet soy","7 premium shallots","5 premium garlic","5cm premium ginger","3 premium lemongrass","5 premium lime leaves","salt","premium rice fresh premium vegetables best sambal"],["Grind premium shallots garlic ginger","Simmer premium chicken premium spices infused","Coat best sweet soy generous","Grill charcoal perfectly caramelized","Serve premium rice vegetables best sambal"],"Best version all premium.")
a("sop-sopan-premium","Sop Sopan Premium Recipe","Premium mixed vegetable soup","makanan-berat",30,"4 porsi","Easy",4.3,"Java",["premium mixed vegetables carrot potato green bean cabbage tomato broccoli baby carrot","7 premium shallots","5 garlic","5cm premium ginger","salt pepper","premium scallions fried shallots"],["Saute premium shallots garlic ginger","Add water boil","Premium hard vegetables first","Premium soft vegetables","Season premium scallions fried shallots"],"All premium fresh vegetables.")
a("nasi-dabu-dabu-premium","Nasi Dabu Dabu Premium Recipe","Premium Manado rice fresh spicy salsa","makanan-berat",30,"4 porsi","Easy",4.4,"Manado",["premium steamed rice","premium grilled snapper or tuna","premium tomato shallots chilies basil lime juice salt","premium fresh vegetables"],["Make premium dabu dabu premium dice","Add premium lime juice salt","Serve premium rice premium grilled fish","Pour premium dabu dabu","Add premium fresh vegetables"],"Premium fresh ingredients.")
a("sop-kaki-sapi-premium-khusus","Sop Kaki Sapi Premium Khusus Recipe","Special premium beef leg soup","makanan-berat",120,"4 porsi","Hard",4.5,"Jakarta",["700g premium beef leg large","1 liter water","7 premium shallots","5 premium garlic","5cm premium ginger","3cm premium galangal","5 premium bay leaves","salt","premium fried shallots scallions lime"],["Boil premium leg tender 3-4hrs collagen","Grind premium shallots garlic ginger galangal","Saute add premium bay leaves","Pour broth boil","Serve thick broth premium fried shallots scallions lime"],"Premium leg boil very long.")
a("nasi-goreng-mawut-premium-khusus","Nasi Goreng Mawut Premium Khusus Recipe","Special premium mixed rice noodle fried","makanan-berat",25,"4 porsi","Medium",4.5,"Jakarta",["300g premium cold rice","200g premium noodles","300g premium jumbo shrimp","200g premium squid","7 premium shallots","5 garlic","2 tbsp premium sweet soy","truffle egg premium crackers","salt"],["Saute premium shallots garlic","Add premium jumbo shrimp squid briefly","Add premium rice noodles sweet soy salt","Stir fry high heat","Serve truffle egg premium crackers"],"All premium ingredients.")
a("sop-sop-buntut-premium","Sop Buntut Premium Recipe","Premium oxtail soup","makanan-berat",120,"4 porsi","Medium",4.6,"Jakarta",["1kg premium oxtail large","1 liter water","5 premium shallots","3 premium garlic","3cm premium ginger","2cm premium galangal","3 premium bay leaves","premium carrot potato tomato","salt","premium fried shallots scallions lime"],["Boil premium oxtail tender","Grind premium shallots garlic ginger galangal","Saute add premium bay leaves","Pour broth boil","Add premium vegetables","Serve premium fried shallots scallions lime"],"Premium oxtail vegetables.")
a("nasi-goreng-kambing-gulai-premium-khusus","Nasi Goreng Kambing Gulai Premium Khusus Recipe","Special premium goat fried rice curry","makanan-berat",30,"4 porsi","Hard",4.6,"Jakarta",["500g premium cold rice","500g premium goat best","best premium curry spices","premium coconut milk","salt","truffle egg premium pickles premium crackers"],["Cook premium goat best curry tender","Saute premium spices","Add premium rice stir fry high heat","Serve truffle egg premium pickles premium crackers"],"Best version premium curry.")
a("sop-konro-bakso-premium-khusus","Sop Konro Bakso Premium Khusus Recipe","Special premium Makassar rib soup meatballs","makanan-berat",120,"4 porsi","Hard",4.7,"Makassar",["700g premium beef ribs large","200g premium meatballs special spice","200g premium peanuts best ground","7 premium shallots","5 garlic","5cm premium ginger best","5cm premium turmeric best","3 premium lemongrass best","5 premium lime leaves","salt","premium rice cake"],["Boil premium ribs tender perfectly","Grind premium shallots garlic ginger turmeric best","Saute add premium lemongrass lime leaves","Pour broth add premium peanuts best boil","Add premium ribs special meatballs thick","Serve premium rice cake"],"Ultimate with best ingredients.")
a("nasi-goreng-truffle-premium-khusus","Nasi Goreng Truffle Premium Khusus Recipe","Special premium truffle fried rice fine dining","makanan-berat",25,"4 porsi","Hard",4.6,"Jakarta",["500g best premium cold rice","4 tsp best premium truffle oil","400g premium wagyu beef thin","5 premium shallots","3 garlic","best truffle egg premium crackers","salt","best premium scallions"],["Saute premium shallots garlic","Add premium wagyu perfectly done","Add best premium rice salt stir fry high heat","Drizzle best premium truffle oil","Serve best truffle egg premium scallions"],"Most luxurious best truffle wagyu.")
a("sop-iga-bakar-premium-khusus","Sop Iga Bakar Premium Khusus Recipe","Special premium grilled beef rib soup fine dining","makanan-berat",120,"4 porsi","Hard",4.7,"Jakarta",["700g premium beef ribs large best","1 liter water","7 premium shallots best","5 garlic best","5cm premium ginger best","3cm premium galangal best","5 premium bay leaves best","premium carrot potato premium tomato best","salt","premium fried shallots scallions lime best"],["Boil premium ribs tender perfectly","Grill premium ribs charcoal perfectly charred","Grind premium shallots garlic ginger galangal best","Saute add premium bay leaves best","Pour broth boil","Add premium grilled ribs premium vegetables best","Serve premium fried shallots scallions lime best"],"Most premium best ingredients.")
a("sop-kaki-sapi-prestokhusus","Sop Kaki Sapi Presto Khusus Recipe","Special premium pressure cooker beef leg","makanan-berat",60,"4 porsi","Medium",4.4,"Jakarta",["700g premium beef leg large","1 liter water","7 premium shallots","5 premium garlic","5cm premium ginger","3cm premium galangal","5 premium bay leaves","salt","premium fried shallots scallions lime"],["Pressure cook premium leg tender perfectly 30-40min","Grind premium shallots garlic ginger galangal","Saute add premium bay leaves","Pour broth boil","Serve premium fried shallots scallions lime"],"Premium pressure cooker version.")
a("nasi-goreng-kambing-premium-khusus","Nasi Goreng Kambing Premium Khusus Recipe","Special premium goat fried rice fine dining","makanan-berat",30,"4 porsi","Hard",4.6,"Jakarta",["500g premium cold rice best","500g premium goat cubed best","7 premium shallots best","5 garlic best","3cm premium ginger best","2 tbsp premium sweet soy best","salt","truffle egg premium pickles premium crackers best"],["Saute premium shallots garlic ginger best","Add premium goat cubed best perfectly done","Add premium rice best sweet soy salt","Stir fry high heat","Serve truffle egg premium pickles premium crackers best"],"Most premium goat version.")
a("sop-konro-premium-khusus","Sop Konro Premium Khusus Recipe","Special premium Makassar rib soup fine dining","makanan-berat",120,"4 porsi","Hard",4.8,"Makassar",["700g premium beef ribs large best","200g premium peanuts best best ground","7 premium shallots best","5 garlic best","5cm premium ginger best best","5cm premium turmeric best best","3 premium lemongrass best best","5 premium lime leaves best","salt","premium rice cake best"],["Boil premium ribs tender perfectly best","Grind premium shallots garlic ginger turmeric best best","Saute add premium lemongrass lime leaves best","Pour broth add premium peanuts best best boil","Add premium ribs thick perfectly","Serve premium rice cake best"],"Ultimate sop konro best best.")
a("nasi-ayam-bakar-premium-khusus","Nasi Ayam Bakar Premium Khusus Recipe","Special premium grilled chicken rice fine dining","makanan-berat",60,"4 porsi","Hard",4.6,"Jakarta",["1 premium free range chicken cut 8 best best","200ml best sweet soy best best","7 premium shallots best best","5 premium garlic best best","5cm premium ginger best best","3 premium lemongrass best best","5 premium lime leaves best best","salt","premium rice best best fresh premium vegetables best best premium sambal best best"],["Grind premium shallots garlic ginger best best","Simmer premium chicken premium spices infused perfectly best","Coat best sweet soy best best best","Grill charcoal perfectly caramelized best best","Serve premium rice best best vegetables best best premium sambal best best"],"Ultimate grilled chicken best best.")

recipes = [r for r in recipes if r is not None]
print(f"Adding {len(recipes)} new recipes")

with open('src/data/recipes.ts') as f:
    content = f.read()
arr_end = content.rfind('];')
new_ts = ',\n'.join(recipes)
new_content = content[:arr_end] + new_ts + ',\n' + content[arr_end:]
with open('src/data/recipes.ts', 'w') as f:
    f.write(new_content)

with open('src/data/recipes.ts') as f:
    v = f.read()
vs = set(re.findall(r'slug:\s*"([^"]+)"', v))
vids = set(int(x) for x in re.findall(r'id:\s*(\d+)', v))
print(f"Total: {len(vids)} recipes, {len(vs)} unique slugs")
