// ─── Supabase Config ───
var SB_URL = "https://xdnhywlbibaniwefdsuz.supabase.co";
var SB_KEY = "sb_publishable_HM6YJ8A372MPKvufkCoAxA_kYerAP0u";

// ─── Inline data (preloaded, no async needed) ───
window.recipes = [{"id":1,"nama":"Nasi Goreng Jawa","kategori":"makanan-berat","waktu":30,"porsi":"2 orang","kesulitan":"Mudah","rating":4.8,"gambar":"https://images.unsplash.com/photo-1512058564366-18510be2db19?w=1200&q=80","bahan":["2 piring nasi putih dingin","2 siung bawang putih cincang","3 siung bawang merah iris","2 butir telur","1 sdm kecap manis","1 sdt garam","½ sdt merica","Minyak kelapa secukupnya","Pelengkap: kerupuk, acar, tomat, daun bawang"],"langkah":["Panaskan minyak, tumis bawang merah dan bawang putih hingga harum.","Sisihkan ke pinggir wajan, masukkan telur, orak-arik hingga matang.","Masukkan nasi, aduk rata dengan api besar.","Tambahkan kecap manis, garam, merica. Aduk cepat hingga merata.","Masak 3-5 menit hingga nasi sedikit kering.","Sajikan hangat dengan kerupuk, acar, dan irisan tomat."]}, 
 {"id":2,"nama":"Rendang Daging Sapi Padang","kategori":"makanan-berat","waktu":240,"porsi":"8 orang","kesulitan":"Sulit","rating":4.9,"gambar":"https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=1200&q=80","bahan":["1 kg daging sapi has dalam","2 liter santan kental","5 lembar daun jeruk","2 batang serai","2 lembar daun kunyit","Bumbu halus: 12 bawang merah, 8 bawang putih, 150 gr cabe merah, 4 cm jahe, 4 cm lengkuas, 3 cm kunyit, 2 sdt ketumbar, 1 sdt jintan","Garam dan gula secukupnya"],"langkah":["Tumis bumbu halus hingga matang dan minyak terpisah.","Masukkan daging, aduk hingga berubah warna.","Tuang santan, masak dengan api sedang sambil diaduk.","Kecilkan api, masak 3-4 jam hingga santan menyusut.","Aduk sesekali agar tidak gosong.","Masak hingga rendang berwarna coklat gelap kehitaman.","Sajikan dengan nasi hangat."]}, 
 {"id":3,"nama":"Sate Ayam Madura","kategori":"sate-panggang","waktu":75,"porsi":"5 orang","kesulitan":"Sedang","rating":4.7,"gambar":"https://images.unsplash.com/photo-1600891964599-f61ba0e24092?w=1200&q=80","bahan":["600 gr dada ayam fillet","Tusuk sate bambu","4 sdm kecap manis","2 sdm minyak kelapa","Bumbu kacang: 200 gr kacang tanah goreng, 4 bawang putih, 8 cabe rawit, 3 sdm gula merah, 1 sdt garam, 250 ml air"],"langkah":["Marinasi ayam dengan kecap dan minyak, diamkan 45 menit.","Tusukkan ayam ke tusuk sate.","Haluskan bahan bumbu kacang, tambahkan air hingga kekentalan pas.","Panggang sate di atas bara api, bolak-balik sambil dioles bumbu.","Sajikan dengan bumbu kacang dan lontong."]}, 
 {"id":4,"nama":"Soto Ayam Lamongan","kategori":"sup-soto","waktu":100,"porsi":"6 orang","kesulitan":"Sedang","rating":4.8,"gambar":"https://images.unsplash.com/photo-1626804475297-410ac11f41c5?w=1200&q=80","bahan":["1 ekor ayam kampung","2 batang serai","5 lembar daun jeruk","2,5 liter air","Bumbu halus: 10 bawang merah, 6 bawang putih, 5 cm kunyit, 3 cm jahe, 4 kemiri, 1 sdm ketumbar","Pelengkap: soun, telur rebus, kol, seledri, bawang goreng, koya, jeruk nipis"],"langkah":["Rebus ayam dengan air, buang busa. Masukkan serai dan daun jeruk.","Tumis bumbu halus hingga harum, masukkan ke rebusan ayam.","Masak hingga ayam empuk. Angkat ayam, goreng sebentar, suwir.","Saring kuah, didihkan kembali. Koreksi rasa.","Sajikan dengan nasi, soun, kol, suwiran ayam, telur rebus, dan kuah."]}, 
 {"id":5,"nama":"Gado-Gado Betawi","kategori":"makanan-berat","waktu":50,"porsi":"4 orang","kesulitan":"Mudah","rating":4.5,"gambar":"https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=1200&q=80","bahan":["150 gr tauge","150 gr kangkung","2 buah kentang rebus","3 butir telur rebus","2 buah tahu goreng","Lontong potong","Bumbu kacang: 250 gr kacang tanah, 4 bawang putih, 8 cabe rawit, 3 sdm gula merah, 1 sdt garam, 300 ml air","Kerupuk emping"],"langkah":["Siapkan semua sayuran rebus dan bahan di piring.","Haluskan bumbu kacang, tambahkan air hangat hingga kekentalan pas.","Siram bumbu kacang di atas tatanan sayur.","Taburi bawang goreng, sajikan dengan kerupuk emping."]}, 
 {"id":6,"nama":"Bakso Malang Komplit","kategori":"sup-soto","waktu":120,"porsi":"8 orang","kesulitan":"Sedang","rating":4.6,"gambar":"https://images.unsplash.com/photo-1600891964599-f61ba0e24092?w=1200&q=80","bahan":["600 gr daging sapi giling","150 gr tepung tapioka","3 putih telur","6 siung bawang putih goreng","Es batu","Kuah: 3 liter air kaldu sapi, bawang putih goreng, seledri","Pelengkap: mi kuning, bihun, sawi, tahu goreng, pangsit, sambal"],"langkah":["Campur daging giling, garam, merica, bawang putih. Uleni.","Tambahkan putih telur dan tepung tapioka, uleni hingga kalis.","Bentuk bola-bola, rebus dalam air mendidih hingga mengapung.","Rendam bakso dalam air es agar kenyal.","Kuah: didihkan kaldu, bumbui, masukkan bakso.","Sajikan dengan mi, bihun, sawi, dan pelengkap lainnya."]}, 
 {"id":7,"nama":"Martabak Manis Bangka","kategori":"jajanan","waktu":90,"porsi":"4 loyang","kesulitan":"Sedang","rating":4.9,"gambar":"https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=1200&q=80","bahan":["300 gr tepung terigu","3 butir telur","60 gr gula pasir","400 ml susu cair","1 sdt baking powder","½ sdt soda kue","1 sdt ragi instan","Topping: meses, keju, kacang, susu kental manis, margarin"],"langkah":["Campur terigu, gula, garam, ragi, dan susu. Diamkan 45-60 menit.","Tambahkan telur, baking powder, soda kue. Aduk rata.","Panaskan wajan martabak, tuang adonan.","Tunggu gelembung, taburi gula pasir. Tutup, masak hingga matang.","Olesi margarin, taburi topping, lipat, potong-potong."]}, 
 {"id":8,"nama":"Es Cendol Dawet Ayu","kategori":"minuman","waktu":50,"porsi":"6 gelas","kesulitan":"Mudah","rating":4.7,"gambar":"https://images.unsplash.com/photo-1544145945-f90425340c7e?w=1200&q=80","bahan":["150 gr tepung beras","75 gr tepung hunkwe","800 ml air","Pasta pandan","Sirup: 300 gr gula aren, 150 ml air, daun pandan","Santan: 500 ml santan, garam, daun pandan","Es serut"],"langkah":["Campur tepung dan air, masak hingga mengental.","Cetak cendol ke air es.","Rebus gula aren dengan air dan pandan hingga mengental.","Rebus santan dengan garam dan pandan, jangan sampai mendidih.","Sajikan cendol dengan es serut, sirup, dan santan."]}, 
 {"id":9,"nama":"Pempek Kapal Selam Palembang","kategori":"jajanan","waktu":100,"porsi":"8 buah","kesulitan":"Sedang","rating":4.8,"gambar":"https://images.unsplash.com/photo-1562967914-608f3c9e17e4?w=1200&q=80","bahan":["600 gr ikan tenggiri giling","400 gr tepung sagu","350 ml air es","3 butir telur","Cuko: 400 gr gula aren, 8 bawang putih, 15 cabe rawit, 4 sdm cuka, 600 ml air, 1 sdt garam"],"langkah":["Campur ikan, air es, garam, telur. Uleni.","Masukkan tepung sagu sedikit demi sedikit.","Bentuk kapal selam: pipihkan adonan, isi telur, tutup rapat.","Rebus hingga mengapung. Tiriskan.","Goreng hingga keemasan.","Cuko: rebus semua bahan cuko hingga mendidih, saring."]}, 
 {"id":10,"nama":"Es Teler Nusantara","kategori":"minuman","waktu":25,"porsi":"4 gelas","kesulitan":"Mudah","rating":4.6,"gambar":"https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=1200&q=80","bahan":["2 buah alpukat mentega","150 gr nangka potong","2 buah kelapa muda","Es serut","Sirup cocopandan","Susu kental manis","Biji selasih"],"langkah":["Keruk daging alpukat, potong nangka, keruk kelapa muda.","Masukkan semua buah ke gelas.","Tambahkan es serut hingga penuh.","Tuang sirup dan susu kental manis.","Aduk rata, sajikan segera."]}, 
 {"id":11,"nama":"Ayam Goreng Lengkuas","kategori":"makanan-berat","waktu":60,"porsi":"4 orang","kesulitan":"Mudah","rating":4.6,"gambar":"https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=1200&q=80","bahan":["1 ekor ayam potong 8","3 cm lengkuas parut","5 siung bawang putih","3 cm kunyit","2 cm jahe","1 sdt ketumbar","Garam dan kaldu bubuk","Air untuk merebus","Minyak untuk menggoreng"],"langkah":["Haluskan bawang putih, kunyit, jahe, ketumbar, garam.","Lumuri ayam dengan bumbu halus dan lengkuas parut.","Rebus ayam dengan bumbu dan sedikit air hingga empuk dan air habis.","Panaskan minyak, goreng ayam hingga kecoklatan.","Goreng juga sisa bumbu lengkuas hingga kering untuk taburan.","Sajikan dengan nasi hangat dan sambal."]}, 
 {"id":12,"nama":"Tumis Kangkung Belacan","kategori":"makanan-berat","waktu":15,"porsi":"3 orang","kesulitan":"Mudah","rating":4.4,"gambar":"https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=1200&q=80","bahan":["2 ikat kangkung siangi","2 sdm belacan (terasi) bakar","4 siung bawang merah","3 siung bawang putih","5 buah cabai merah","1 sdt gula","Garam secukupnya","Minyak untuk menumis"],"langkah":["Haluskan bawang merah, bawang putih, cabai, dan belacan.","Panaskan minyak, tumis bumbu halus hingga harum.","Masukkan kangkung, aduk cepat hingga layu.","Tambahkan gula dan garam. Koreksi rasa.","Angkat dan sajikan segera."]}, 
 {"id":13,"nama":"Ikan Bakar Jimbaran","kategori":"sate-panggang","waktu":60,"porsi":"4 orang","kesulitan":"Sedang","rating":4.7,"gambar":"https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=1200&q=80","bahan":["4 ekor ikan kakap/baronang","5 siung bawang putih","3 cm kunyit","2 cm jahe","1 sdm ketumbar","3 sdm kecap manis","2 sdm air jeruk nipis","Garam dan merica","Sambal matah untuk pelengkap"],"langkah":["Haluskan bawang putih, kunyit, jahe, ketumbar, garam.","Lumuri ikan dengan bumbu halus, kecap, dan air jeruk. Diamkan 30 menit.","Panggang ikan di atas bara api sambil dioles sisa bumbu.","Balik ikan, panggang hingga kedua sisi matang.","Sajikan dengan sambal matah dan nasi hangat."]}, 
 {"id":14,"nama":"Sop Buntut Sapi","kategori":"sup-soto","waktu":180,"porsi":"6 orang","kesulitan":"Sedang","rating":4.7,"gambar":"https://images.unsplash.com/photo-1547592166-23ac45744acd?w=1200&q=80","bahan":["1 kg buntut sapi potong","2 liter air","3 wortel potong","3 kentang potong","2 batang seledri","2 batang daun bawang","5 siung bawang putih","3 cm jahe","1 sdt merica","Garam dan kaldu sapi","Bawang goreng untuk taburan"],"langkah":["Rebus buntut sapi hingga empuk (bisa pakai presto 45 menit).","Angkat buntut, saring kaldunya.","Haluskan bawang putih, jahe, dan merica.","Tumis bumbu halus hingga harum, masukkan ke kaldu.","Masukkan wortel dan kentang. Masak hingga empuk.","Masukkan buntut, garam, dan kaldu bubuk. Koreksi rasa.","Taburi seledri, daun bawang, dan bawang goreng."]}, 
 {"id":15,"nama":"Mie Goreng Jawa","kategori":"makanan-berat","waktu":25,"porsi":"3 orang","kesulitan":"Mudah","rating":4.5,"gambar":"https://images.unsplash.com/photo-1552611052-33e04de1b100?w=1200&q=80","bahan":["500 gr mie telur basah","3 butir telur","5 siung bawang merah","3 siung bawang putih","3 sdm kecap manis","1 sdt merica","1 sdt garam","1 batang daun bawang","Sayur: kol, sawi, wortel","Minyak untuk menumis"],"langkah":["Rebus mie sebentar, tiriskan. Beri sedikit minyak.","Haluskan bawang merah dan bawang putih.","Tumis bumbu halus hingga harum. Masukkan telur, orak-arik.","Masukkan sayuran, aduk hingga layu.","Masukkan mie, kecap manis, merica, garam. Aduk rata.","Masukkan daun bawang, aduk sebentar. Sajikan."]}, 
 {"id":16,"nama":"Sambal Goreng Kentang Ati","kategori":"jajanan","waktu":45,"porsi":"6 orang","kesulitan":"Sedang","rating":4.5,"gambar":"https://images.unsplash.com/photo-1563379928-29f3c0a26a3c?w=1200&q=80","bahan":["500 gr kentang potong dadu","250 gr hati ayam sapi rebus","5 sdm santan kental","10 buah cabai merah","6 siung bawang merah","4 siung bawang putih","2 lembar daun salam","2 cm lengkuas","Garam dan gula secukupnya","Minyak untuk menggoreng"],"langkah":["Goreng kentang hingga matang, sisihkan.","Haluskan cabai, bawang merah, bawang putih.","Tumis bumbu halus dengan daun salam dan lengkuas hingga harum.","Masukkan hati, aduk rata.","Tambahkan santan, garam, dan gula. Masak hingga kuah mengental.","Masukkan kentang goreng, aduk rata. Sajikan."]}, 
 {"id":17,"nama":"Capcay Kuah Kental","kategori":"makanan-berat","waktu":20,"porsi":"4 orang","kesulitan":"Mudah","rating":4.4,"gambar":"https://images.unsplash.com/photo-1563379928-29f3c0a26a3c?w=1200&q=80","bahan":["2 buah wortel iris serong","1 bonggol brokoli","10 buah bakso sapi iris","5 siung bawang putih cincang","1 sdm saus tiram","1 sdm kecap asin","1 sdt merica","1 sdt garam","1 sdm maizena larutkan dengan air","200 ml air","Minyak untuk menumis"],"langkah":["Panaskan minyak, tumis bawang putih hingga harum.","Masukkan bakso, aduk hingga berubah warna.","Masukkan wortel dan brokoli, aduk rata.","Tuang air, saus tiram, kecap asin, merica, garam.","Masak hingga sayuran matang.","Tuang larutan maizena, aduk hingga kuah mengental. Sajikan."]}, 
 {"id":18,"nama":"Pepes Ikan Mas","kategori":"makanan-berat","waktu":60,"porsi":"4 orang","kesulitan":"Sedang","rating":4.6,"gambar":"https://images.unsplash.com/photo-1546069901-d5bfd2c3a5a9?w=1200&q=80","bahan":["4 ekor ikan mas","10 buah cabai merah","8 siung bawang merah","5 siung bawang putih","3 cm kunyit","2 cm jahe","3 butir kemiri","2 batang serai iris tipis","4 lembar daun salam","Daun pisang untuk membungkus","Garam dan gula secukupnya"],"langkah":["Haluskan cabai, bawang, kunyit, jahe, kemiri.","Lumuri ikan dengan bumbu halus, garam, dan gula.","Tambahkan serai iris dan daun salam.","Bungkus ikan dengan daun pisang, semat lidi.","Kukus pepes selama 30 menit hingga matang.","Bakar sebentar di atas grill agar lebih wangi. Sajikan."]}, 
 {"id":19,"nama":"Sop Iga Sapi","kategori":"sup-soto","waktu":150,"porsi":"6 orang","kesulitan":"Sedang","rating":4.7,"gambar":"https://images.unsplash.com/photo-1547592166-23ac45744acd?w=1200&q=80","bahan":["1 kg iga sapi","2 liter air","2 wortel potong","2 kentang potong","1 buah tomat potong","2 batang seledri","2 batang daun bawang","6 siung bawang putih","1 sdt merica","Garam dan kaldu sapi","Bawang goreng"],"langkah":["Rebus iga sapi hingga empuk (presto 40 menit).","Saring kaldu, sisihkan.","Haluskan bawang putih dan merica.","Tumis bumbu halus hingga harum, masukkan ke kaldu.","Masukkan wortel dan kentang, masak hingga empuk.","Masukkan iga, tomat, garam, kaldu bubuk.","Sajikan dengan seledri, daun bawang, dan bawang goreng."]}, 
 {"id":20,"nama":"Nasi Liwet Solo","kategori":"makanan-berat","waktu":60,"porsi":"6 orang","kesulitan":"Sedang","rating":4.7,"gambar":"https://images.unsplash.com/photo-1596797038530-2c107229654b?w=1200&q=80","bahan":["500 gr beras","1 liter santan encer","5 siung bawang merah iris","3 siung bawang putih iris","2 batang serai memarkan","4 lembar daun salam","3 cm lengkuas","Garam secukupnya","Pelengkap: ayam suwir, telur pindang, sambal"],"langkah":["Cuci beras hingga bersih, tiriskan.","Tumis bawang merah dan bawang putih hingga harum.","Masukkan beras, serai, daun salam, lengkuas, garam. Aduk rata.","Tuang santan, masak dengan api kecil hingga mendidih.","Aduk sesekali, masak hingga santan terserap.","Kukus nasi hingga matang sempurna (30 menit).","Sajikan dengan pelengkap."]}, 
 {"id":21,"nama":"Ayam Bakar Taliwang","kategori":"sate-panggang","waktu":90,"porsi":"4 orang","kesulitan":"Sedang","rating":4.7,"gambar":"https://images.unsplash.com/photo-1559825597-6ea0c737e3e4?w=1200&q=80","bahan":["1 ekor ayam kampung","15 buah cabai merah","10 buah cabai rawit","8 siung bawang merah","5 siung bawang putih","2 cm kencur","2 butir kemiri","1 sdt terasi bakar","200 ml santan","1 sdm air asam","Garam dan gula merah"],"langkah":["Haluskan semua bumbu halus. Tumis hingga harum.","Masukkan santan, air asam, garam, gula. Masak hingga mendidih.","Masukkan ayam, masak dengan api kecil hingga bumbu meresap.","Panggang ayam sambil diolesi sisa bumbu hingga kecoklatan.","Sajikan dengan nasi hangat dan plecing kangkung."]}, 
 {"id":22,"nama":"Gudeg Nangka Muda","kategori":"makanan-berat","waktu":240,"porsi":"8 orang","kesulitan":"Sulit","rating":4.8,"gambar":"https://images.unsplash.com/photo-1512058564366-18510be2db19?w=1200&q=80","bahan":["1 kg nangka muda potong","1,5 liter santan","250 gr gula merah","4 lembar daun salam","3 cm lengkuas","10 bawang merah","5 bawang putih","4 kemiri","2 sdt ketumbar","Pelengkap: ayam opor, telur pindang, krecek"],"langkah":["Rebus nangka 2x untuk hilangkan getah. Tiriskan.","Tumis bumbu halus hingga harum.","Masukkan nangka, santan, dan gula merah.","Masak dengan api kecil 3-4 jam hingga empuk dan mengental.","Sajikan dengan ayam opor, telur pindang, dan krecek."]}, 
 {"id":23,"nama":"Pisang Goreng Crispy","kategori":"jajanan","waktu":20,"porsi":"4 orang","kesulitan":"Mudah","rating":4.5,"gambar":"https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=1200&q=80","bahan":["6 buah pisang kepok matang","5 sdm tepung terigu","2 sdm tepung beras","1 sdm gula pasir","1 sdt garam","1 sdt vanili","Air secukupnya","Minyak untuk menggoreng","Topping: gula donat, meses, keju"],"langkah":["Campur semua tepung, gula, garam, vanili. Beri air sedikit demi sedikit.","Aduk hingga adonan kental tidak bergerindil.","Belah pisang memanjang, celupkan ke adonan.","Goreng dalam minyak panas hingga kuning keemasan.","Angkat, tiriskan. Beri topping sesuai selera."]}, 
 {"id":24,"nama":"Tahu Gejrot","kategori":"jajanan","waktu":15,"porsi":"3 orang","kesulitan":"Mudah","rating":4.4,"gambar":"https://images.unsplash.com/photo-1562967914-608f3c9e17e4?w=1200&q=80","bahan":["6 buah tahu putih goreng","5 siung bawang merah iris","3 buah cabai rawit iris","3 sdm kecap manis","2 sdm air asam jawa","1 sdm gula merah","Garam secukupnya","100 ml air matang"],"langkah":["Potong tahu goreng kecil-kecil, letakkan di piring.","Campur bawang merah, cabai, kecap, air asam, gula, garam, dan air.","Aduk rata bumbu hingga gula larut.","Siram bumbu ke atas tahu.","Sajikan segera selagi hangat."]}, 
 {"id":25,"nama":"Es Campur Khas Surabaya","kategori":"minuman","waktu":15,"porsi":"4 gelas","kesulitan":"Mudah","rating":4.5,"gambar":"https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=1200&q=80","bahan":["100 gr cincau hitam potong","100 gr nangka potong","2 buah alpukat keruk","50 gr kolang kaling rebus","Es serut","Sirup gula merah","Susu kental manis","100 ml santan matang"],"langkah":["Siapkan semua bahan dalam mangkuk.","Masukkan es serut ke gelas saji.","Tata cincau, nangka, alpukat, kolang kaling.","Tuang sirup gula merah, susu kental manis, dan santan.","Sajikan segera."]}, 
 {"id":26,"nama":"Perkedel Kentang","kategori":"jajanan","waktu":30,"porsi":"4 orang","kesulitan":"Mudah","rating":4.3,"gambar":"https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=1200&q=80","bahan":["500 gr kentang","2 butir telur","3 siung bawang putih goreng","2 batang daun seledri iris","1 sdt merica","1 sdt garam","Minyak untuk menggoreng"],"langkah":["Kupas kentang, potong, goreng hingga empuk.","Haluskan kentang selagi panas.","Campur dengan bawang putih goreng halus, seledri, merica, garam.","Tambahkan 1 butir telur, aduk rata.","Bentuk bulat pipih.","Celupkan ke telur kocok, goreng hingga kecoklatan."]}, 
 {"id":27,"nama":"Ikan Nila Bakar","kategori":"sate-panggang","waktu":45,"porsi":"4 orang","kesulitan":"Mudah","rating":4.5,"gambar":"https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=1200&q=80","bahan":["4 ekor ikan nila","5 siung bawang putih","3 cm kunyit","2 cm jahe","1 sdm ketumbar","3 sdm kecap manis","2 sdm air jeruk nipis","Garam dan merica","Sambal kecap pelengkap"],"langkah":["Haluskan bawang putih, kunyit, jahe, ketumbar, garam.","Lumuri ikan dengan bumbu halus dan air jeruk. Diamkan 20 menit.","Panggang ikan di atas bara api atau grill.","Olesi kecap manis saat membakar.","Sajikan dengan sambal kecap dan lalapan."]}, 
 {"id":28,"nama":"Bubur Ayam Jakarta","kategori":"makanan-berat","waktu":45,"porsi":"4 orang","kesulitan":"Mudah","rating":4.6,"gambar":"https://images.unsplash.com/photo-1626804475297-410ac11f41c5?w=1200&q=80","bahan":["200 gr beras","1 liter air kaldu ayam","200 gr ayam rebus suwir","2 lembar daun salam","1 sdt garam","Pelengkap: cakwe, telur rebus, seledri, bawang goreng, kecap manis, sambal"],"langkah":["Cuci beras, rebus dengan air kaldu dan daun salam.","Masak dengan api kecil sambil diaduk hingga menjadi bubur.","Tambahkan garam, aduk rata.","Sajikan bubur dengan suwiran ayam dan pelengkap."]}, 
 {"id":29,"nama":"Tempe Mendoan","kategori":"jajanan","waktu":15,"porsi":"4 orang","kesulitan":"Mudah","rating":4.4,"gambar":"https://images.unsplash.com/photo-1562967914-608f3c9e17e4?w=1200&q=80","bahan":["1 papan tempe iris tipis","5 sdm tepung terigu","2 sdm tepung beras","2 siung bawang putih halus","1 sdt ketumbar","1 sdt garam","1 batang daun bawang iris","Air secukupnya","Minyak untuk menggoreng"],"langkah":["Campur semua tepung, bawang putih, ketumbar, garam, daun bawang.","Beri air sedikit demi sedikit hingga adonan kental.","Celupkan irisan tempe ke adonan.","Goreng dalam minyak panas sebentar saja (tidak sampai kering).","Angkat, sajikan hangat dengan sambal kecap."]}, 
 {"id":30,"nama":"Sop Ayam Pak Min Klaten","kategori":"sup-soto","waktu":60,"porsi":"4 orang","kesulitan":"Mudah","rating":4.6,"gambar":"https://images.unsplash.com/photo-1626804475297-410ac11f41c5?w=1200&q=80","bahan":["1 ekor ayam kampung potong","1,5 liter air","6 siung bawang putih geprek","3 cm jahe memarkan","2 batang serai memarkan","4 lembar daun jeruk","2 batang seledri ikat","Garam dan merica","Bawang goreng untuk taburan"],"langkah":["Rebus ayam dengan air hingga mendidih. Buang busa.","Masukkan bawang putih, jahe, serai, daun jeruk, seledri.","Masak dengan api kecil hingga ayam empuk.","Tambahkan garam dan merica. Koreksi rasa.","Sajikan dengan taburan bawang goreng."]}];
window.supabaseReady = true;

// ─── API Functions ───
window.apiFetch = async function () {
  return window.recipes;
};

window.apiInsert = async function (recipe) {
  try {
    await fetch(`${SB_URL}/rest/v1/recipes`, {
      method: "POST",
      headers: { "Content-Type": "application/json", apikey: SB_KEY, Authorization: `Bearer ${SB_KEY}`, Prefer: "return=minimal" },
      body: JSON.stringify(recipe),
    });
  } catch(e) {}
  window.recipes.unshift(recipe);
};

window.apiUpdate = async function (id, data) {
  try {
    await fetch(`${SB_URL}/rest/v1/recipes?id=eq.${id}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json", apikey: SB_KEY, Authorization: `Bearer ${SB_KEY}`, Prefer: "return=minimal" },
      body: JSON.stringify(data),
    });
  } catch(e) {}
  var idx = window.recipes.findIndex(function(r) { return r.id === id; });
  if (idx > -1) window.recipes[idx] = data;
};

window.apiDelete = async function (id) {
  try {
    await fetch(`${SB_URL}/rest/v1/recipes?id=eq.${id}`, {
      method: "DELETE",
      headers: { apikey: SB_KEY, Authorization: `Bearer ${SB_KEY}`, Prefer: "return=minimal" },
    });
  } catch(e) {}
  window.recipes = window.recipes.filter(function(r) { return r.id !== id; });
};

// Notify ready
if (window._onReady) window._onReady();
