const fs = require('fs');

// Read the original Indonesian data
const raw = fs.readFileSync('/home/liveuser/nusantaraeats-site/supabase-config.js', 'utf8');
const match = raw.match(/window\.recipes\s*=\s*(\[[\s\S]*?\]);/);
const recipes = JSON.parse(match[1]);

// Translation maps
const difficultyMap = { 'Mudah': 'Easy', 'Sedang': 'Medium', 'Sulit': 'Hard' };

const nameTranslations = {
  'Nasi Goreng Jawa': 'Javanese Fried Rice',
  'Rendang Daging Sapi Padang': 'Padang Beef Rendang',
  'Sate Ayam Madura': 'Madura Chicken Satay',
  'Soto Ayam Lamongan': 'Lamongan Chicken Soto',
  'Gado-Gado Betawi': 'Betawi Gado-Gado',
  'Bakso Malang Komplit': 'Complete Malang Meatballs',
  'Martabak Manis Bangka': 'Bangka Sweet Martabak',
  'Es Cendol Dawet Ayu': 'Cendol Dawet Ayu Ice',
  'Pempek Kapal Selam Palembang': 'Palembang Submarine Pempek',
  'Es Teler Nusantara': 'Nusantara Es Teler',
  'Ayam Goreng Lengkuas': 'Galangal Fried Chicken',
  'Tumis Kangkung Belacan': 'Stir-Fried Water Spinach with Shrimp Paste',
  'Ikan Bakar Jimbaran': 'Jimbaran Grilled Fish',
  'Sop Buntut Sapi': 'Indonesian Oxtail Soup',
  'Mie Goreng Jawa': 'Javanese Fried Noodles',
  'Sambal Goreng Kentang Ati': 'Spicy Fried Potatoes with Liver',
  'Capcay Kuah Kental': 'Thick Gravy Mixed Vegetables',
  'Pepes Ikan Mas': 'Steamed Spiced Goldfish',
  'Sop Iga Sapi': 'Beef Rib Soup',
  'Nasi Liwet Solo': 'Solo Liwet Rice',
  'Ayam Bakar Taliwang': 'Taliwang Grilled Chicken',
  'Gudeg Nangka Muda': 'Young Jackfruit Gudeg',
  'Pisang Goreng Crispy': 'Crispy Fried Banana',
  'Tahu Gejrot': 'Gejrot Tofu',
  'Es Campur Khas Surabaya': 'Surabaya Mixed Ice',
  'Perkedel Kentang': 'Potato Fritters',
  'Ikan Nila Bakar': 'Grilled Tilapia',
  'Bubur Ayam Jakarta': 'Jakarta Chicken Porridge',
  'Tempe Mendoan': 'Mendoan Tempeh',
  'Sop Ayam Pak Min Klaten': 'Pak Min Klaten Chicken Soup',
  'Pallubasa': 'Pallubasa Soup',
  'Sate Padang': 'Padang Satay',
  'Sate Lilit Bali': 'Balinese Minced Satay',
  'Sate Pusut': 'Pusut Satay',
  'Sate Klatak': 'Klatak Iron Skewer Satay',
  'Sate Maranggi': 'Maranggi Beef Satay',
  'Gudeg Jogja': 'Yogyakarta Gudeg',
  'Sayur Lodeh': 'Lodeh Vegetable Stew',
  'Lontong Sayur': 'Rice Cake with Vegetable Stew',
  'Ketoprak': 'Ketoprak',
  'Nasi Uduk Betawi': 'Betawi Coconut Rice',
  'Nasi Kuning': 'Yellow Turmeric Rice',
  'Nasi Tumpeng': 'Cone-Shaped Festive Rice',
  'Bubur Manado': 'Manado Porridge',
  'Sop Saudara': 'Brother\'s Soup',
  'Tinutuan': 'Tinutuan Porridge',
  'Klepon': 'Klepon Rice Balls',
  'Onde-Onde': 'Sesame Balls',
  'Kue Lapis': 'Layer Cake',
  'Kue Lumpur': 'Mud Cake',
  'Bika Ambon': 'Bika Ambon Honeycomb Cake',
  'Putri Salju': 'Snow White Cookies',
  'Kastengel': 'Cheese Stick Cookies',
  'Nastar': 'Pineapple Tart Cookies',
  'Lemang': 'Bamboo Sticky Rice',
  'Wajik': 'Sweet Sticky Rice Cake',
  'Es Doger': 'Doger Ice',
  'Es Bir Pletok': 'Pletok Herbal Ice',
  'Wedang Uwuh': 'Uwuh Herbal Drink',
  'Wedang Ronde': 'Ronde Ginger Drink',
  'Bandrek': 'Bandrek Ginger Drink',
  'Sekoteng': 'Sekoteng Ginger Drink',
  'Lahang': 'Palm Sap Drink',
  'Es Gempol': 'Gempol Ice',
  'Cendol': 'Cendol Jelly Drink',
  'Es Kopyor': 'Kopyor Coconut Ice',
  'Ayam Betutu': 'Betutu Slow-Cooked Chicken',
  'Ayam Geprek': 'Smashed Fried Chicken',
  'Ayam Pop': 'Pop Chicken',
  'Rendang Jengkol': 'Jengkol Rendang',
  'Dendeng Batokok': 'Beaten Smoked Beef',
  'Gulai Tambusu': 'Intestine Curry',
  'Kalio': 'Kalio Beef Curry',
  'Pindang Patin': 'Patin Fish Sour Soup',
  'Tempoyak': 'Fermented Durian Fish',
  'Mie Aceh': 'Aceh Curry Noodles',
  'Kuah Beulangong': 'Beulangong Curry Soup',
  'Sop Kambing': 'Goat Meat Soup',
  'Timlo Solo': 'Solo Timlo Soup',
  'Tongseng': 'Tongseng Stir-Fry',
  'Tutug Oncom': 'Oncom Rice',
  'Kupat Tahu': 'Rice Cake with Tofu',
  'Serabi': 'Serabi Coconut Pancake',
  'Dadar Gulung': 'Rolled Coconut Crepe',
  'Lemper': 'Lemper Sticky Rice Roll',
  'Arem-Arem': 'Arem-Arem Rice Roll',
  'Kue Putu': 'Putu Steamed Cake',
  'Cenil': 'Cenil Tapioca Balls',
  'Gethuk': 'Gethuk Cassava Cake',
  'Mochi': 'Mochi Rice Cake',
  'Kue Cubit': 'Cubit Pinch Cake',
  'Pukis': 'Pukis Half-Moon Cake',
  'Bakpia': 'Bakpia Sweet Roll',
  'Wingko': 'Wingko Coconut Cake',
  'Kue Talam': 'Talam Steamed Cake',
  'Es Palu Butung': 'Butung Banana Ice',
  'Es Kelapa Muda': 'Young Coconut Ice',
  'Es Tebu': 'Sugarcane Ice',
  'Es Timun Serut': 'Shaved Cucumber Ice',
  'Es Kacang Merah': 'Red Bean Ice',
};

const originMap = {
  'Nasi Goreng Jawa': 'Central Java',
  'Rendang Daging Sapi Padang': 'West Sumatra',
  'Sate Ayam Madura': 'East Java (Madura)',
  'Soto Ayam Lamongan': 'East Java',
  'Gado-Gado Betawi': 'Jakarta',
  'Bakso Malang Komplit': 'East Java (Malang)',
  'Martabak Manis Bangka': 'Bangka Belitung',
  'Es Cendol Dawet Ayu': 'Central Java',
  'Pempek Kapal Selam Palembang': 'South Sumatra',
  'Es Teler Nusantara': 'West Java',
  'Ayam Goreng Lengkuas': 'West Java',
  'Tumis Kangkung Belacan': 'East Java',
  'Ikan Bakar Jimbaran': 'Bali',
  'Sop Buntut Sapi': 'Jakarta',
  'Mie Goreng Jawa': 'Central Java',
  'Sambal Goreng Kentang Ati': 'Jakarta',
  'Capcay Kuah Kental': 'Chinese-Indonesian',
  'Pepes Ikan Mas': 'West Java',
  'Sop Iga Sapi': 'Jakarta',
  'Nasi Liwet Solo': 'Central Java (Solo)',
  'Ayam Bakar Taliwang': 'West Nusa Tenggara (Lombok)',
  'Gudeg Nangka Muda': 'Yogyakarta',
  'Pisang Goreng Crispy': 'Indonesia',
  'Tahu Gejrot': 'West Java (Cirebon)',
  'Es Campur Khas Surabaya': 'East Java (Surabaya)',
  'Perkedel Kentang': 'Indonesia',
  'Ikan Nila Bakar': 'Indonesia',
  'Bubur Ayam Jakarta': 'Jakarta',
  'Tempe Mendoan': 'Central Java',
  'Sop Ayam Pak Min Klaten': 'Central Java (Klaten)',
  'Pallubasa': 'South Sulawesi',
  'Sate Padang': 'West Sumatra',
  'Sate Lilit Bali': 'Bali',
  'Sate Pusut': 'Bali (Lombok)',
  'Sate Klatak': 'Yogyakarta',
  'Sate Maranggi': 'West Java',
  'Gudeg Jogja': 'Yogyakarta',
  'Sayur Lodeh': 'Java',
  'Lontong Sayur': 'Jakarta',
  'Ketoprak': 'Jakarta',
  'Nasi Uduk Betawi': 'Jakarta',
  'Nasi Kuning': 'Indonesia',
  'Nasi Tumpeng': 'Java',
  'Bubur Manado': 'North Sulawesi',
  'Sop Saudara': 'South Sulawesi',
  'Tinutuan': 'North Sulawesi',
  'Klepon': 'Java',
  'Onde-Onde': 'Java',
  'Kue Lapis': 'Indonesia',
  'Kue Lumpur': 'Java',
  'Bika Ambon': 'Medan',
  'Putri Salju': 'Indonesia',
  'Kastengel': 'Indonesia',
  'Nastar': 'Indonesia',
  'Lemang': 'Minangkabau',
  'Wajik': 'Java',
  'Es Doger': 'Betawi (Jakarta)',
  'Es Bir Pletok': 'Betawi (Jakarta)',
  'Wedang Uwuh': 'Yogyakarta',
  'Wedang Ronde': 'Java',
  'Bandrek': 'West Java (Sunda)',
  'Sekoteng': 'Java',
  'Lahang': 'West Java',
  'Es Gempol': 'Indonesia',
  'Cendol': 'Java',
  'Es Kopyor': 'Java',
  'Ayam Betutu': 'Bali',
  'Ayam Geprek': 'Yogyakarta',
  'Ayam Pop': 'West Sumatra',
  'Rendang Jengkol': 'West Sumatra',
  'Dendeng Batokok': 'West Sumatra',
  'Gulai Tambusu': 'West Sumatra',
  'Kalio': 'West Sumatra',
  'Pindang Patin': 'South Sumatra',
  'Tempoyak': 'South Sumatra',
  'Mie Aceh': 'Aceh',
  'Kuah Beulangong': 'Aceh',
  'Sop Kambing': 'Jakarta',
  'Timlo Solo': 'Central Java (Solo)',
  'Tongseng': 'Central Java',
  'Tutug Oncom': 'West Java (Tasikmalaya)',
  'Kupat Tahu': 'West Java (Bandung)',
  'Serabi': 'Java',
  'Dadar Gulung': 'Java',
  'Lemper': 'Java',
  'Arem-Arem': 'Java',
  'Kue Putu': 'Java',
  'Cenil': 'Java',
  'Gethuk': 'Central Java',
  'Mochi': 'Indonesia',
  'Kue Cubit': 'Jakarta',
  'Pukis': 'Java',
  'Bakpia': 'Yogyakarta',
  'Wingko': 'Central Java (Semarang)',
  'Kue Talam': 'Indonesia',
  'Es Palu Butung': 'Makassar',
  'Es Kelapa Muda': 'Indonesia',
  'Es Tebu': 'Java',
  'Es Timun Serut': 'Indonesia',
  'Es Kacang Merah': 'Indonesia',
};

// Complete ingredient translations
const ingredientTranslations = {
  '2 piring nasi putih dingin': '2 plates cold steamed rice',
  '2 siung bawang putih cincang': '2 cloves garlic, minced',
  '3 siung bawang merah iris': '3 shallots, sliced',
  '2 butir telur': '2 eggs',
  '1 sdm kecap manis': '1 tbsp sweet soy sauce',
  '1 sdt garam': '1 tsp salt',
  '½ sdt merica': '½ tsp pepper',
  'Minyak kelapa secukupnya': 'Coconut oil as needed',
  'Pelengkap: kerupuk, acar, tomat, daun bawang': 'Garnish: crackers, pickles, tomato, spring onion',
  '1 kg daging sapi has dalam': '1 kg beef tenderloin',
  '2 liter santan kental': '2 liters thick coconut milk',
  '5 lembar daun jeruk': '5 kaffir lime leaves',
  '2 batang serai': '2 lemongrass stalks',
  '2 lembar daun kunyit': '2 turmeric leaves',
  'Bumbu halus: 12 bawang merah, 8 bawang putih, 150 gr cabe merah, 4 cm jahe, 4 cm lengkuas, 3 cm kunyit, 2 sdt ketumbar, 1 sdt jintan': 'Ground spice paste: 12 shallots, 8 garlic cloves, 150g red chili, 4cm ginger, 4cm galangal, 3cm turmeric, 2 tsp coriander, 1 tsp cumin',
  'Garam dan gula secukupnya': 'Salt and sugar to taste',
  '600 gr dada ayam fillet': '600g chicken breast fillet',
  'Tusuk sate bambu': 'Bamboo skewers',
  '4 sdm kecap manis': '4 tbsp sweet soy sauce',
  '2 sdm minyak kelapa': '2 tbsp coconut oil',
  'Bumbu kacang: 200 gr kacang tanah goreng, 4 bawang putih, 8 cabe rawit, 3 sdm gula merah, 1 sdt garam, 250 ml air': 'Peanut sauce: 200g roasted peanuts, 4 garlic cloves, 8 bird\'s eye chilies, 3 tbsp palm sugar, 1 tsp salt, 250ml water',
  '1 ekor ayam kampung': '1 free-range chicken',
  '2 batang serai': '2 lemongrass stalks',
  '5 lembar daun jeruk': '5 kaffir lime leaves',
  '2,5 liter air': '2.5 liters water',
  'Bumbu halus: 10 bawang merah, 6 bawang putih, 5 cm kunyit, 3 cm jahe, 4 kemiri, 1 sdm ketumbar': 'Ground spice paste: 10 shallots, 6 garlic cloves, 5cm turmeric, 3cm ginger, 4 candlenuts, 1 tbsp coriander',
  'Pelengkap: soun, telur rebus, kol, seledri, bawang goreng, koya, jeruk nipis': 'Garnish: glass noodles, boiled egg, cabbage, celery, fried shallots, koya, lime',
  '150 gr tauge': '150g bean sprouts',
  '150 gr kangkung': '150g water spinach',
  '2 buah kentang rebus': '2 boiled potatoes',
  '3 butir telur rebus': '3 boiled eggs',
  '2 buah tahu goreng': '2 fried tofu',
  'Lontong potong': 'Sliced rice cake',
  'Bumbu kacang: 250 gr kacang tanah, 4 bawang putih, 8 cabe rawit, 3 sdm gula merah, 1 sdt garam, 300 ml air': 'Peanut sauce: 250g peanuts, 4 garlic cloves, 8 bird\'s eye chilies, 3 tbsp palm sugar, 1 tsp salt, 300ml water',
  'Kerupuk emping': 'Melinjo nut crackers',
  '600 gr daging sapi giling': '600g ground beef',
  '150 gr tepung tapioka': '150g tapioca flour',
  '3 putih telur': '3 egg whites',
  '6 siung bawang putih goreng': '6 fried garlic cloves',
  'Es batu': 'Ice cubes',
  'Kuah: 3 liter air kaldu sapi, bawang putih goreng, seledri': 'Broth: 3 liters beef broth, fried garlic, celery',
  'Pelengkap: mi kuning, bihun, sawi, tahu goreng, pangsit, sambal': 'Garnish: yellow noodles, rice vermicelli, mustard greens, fried tofu, wontons, chili sauce',
  '300 gr tepung terigu': '300g all-purpose flour',
  '3 butir telur': '3 eggs',
  '60 gr gula pasir': '60g sugar',
  '400 ml susu cair': '400ml milk',
  '1 sdt baking powder': '1 tsp baking powder',
  '½ sdt soda kue': '½ tsp baking soda',
  '1 sdt ragi instan': '1 tsp instant yeast',
  'Topping: meses, keju, kacang, susu kental manis, margarin': 'Topping: chocolate sprinkles, cheese, peanuts, sweetened condensed milk, margarine',
  '150 gr tepung beras': '150g rice flour',
  '75 gr tepung hunkwe': '75g mung bean flour',
  '800 ml air': '800ml water',
  'Pasta pandan': 'Pandan paste',
  'Sirup: 300 gr gula aren, 150 ml air, daun pandan': 'Syrup: 300g palm sugar, 150ml water, pandan leaves',
  'Santan: 500 ml santan, garam, daun pandan': 'Coconut milk: 500ml coconut milk, salt, pandan leaves',
  'Es serut': 'Shaved ice',
  '600 gr ikan tenggiri giling': '600g ground mackerel',
  '400 gr tepung sagu': '400g sago flour',
  '350 ml air es': '350ml ice water',
  '3 butir telur': '3 eggs',
  'Cuko: 400 gr gula aren, 8 bawang putih, 15 cabe rawit, 4 sdm cuka, 600 ml air, 1 sdt garam': 'Vinegar sauce: 400g palm sugar, 8 garlic cloves, 15 bird\'s eye chilies, 4 tbsp vinegar, 600ml water, 1 tsp salt',
  '2 buah alpukat mentega': '2 butter avocados',
  '150 gr nangka potong': '150g sliced jackfruit',
  '2 buah kelapa muda': '2 young coconuts',
  'Sirup cocopandan': 'Cocopandan syrup',
  'Susu kental manis': 'Sweetened condensed milk',
  'Biji selasih': 'Basil seeds',
  '1 ekor ayam potong 8': '1 chicken, cut into 8 pieces',
  '3 cm lengkuas parut': '3cm grated galangal',
  '5 siung bawang putih': '5 garlic cloves',
  '3 cm kunyit': '3cm turmeric',
  '2 cm jahe': '2cm ginger',
  '1 sdt ketumbar': '1 tsp coriander',
  'Garam dan kaldu bubuk': 'Salt and bouillon powder',
  'Air untuk merebus': 'Water for boiling',
  'Minyak untuk menggoreng': 'Oil for frying',
  '2 ikat kangkung siangi': '2 bunches water spinach, trimmed',
  '2 sdm belacan (terasi) bakar': '2 tbsp roasted shrimp paste',
  '4 siung bawang merah': '4 shallots',
  '3 siung bawang putih': '3 garlic cloves',
  '5 buah cabai merah': '5 red chilies',
  '1 sdt gula': '1 tsp sugar',
  'Garam secukupnya': 'Salt to taste',
  'Minyak untuk menumis': 'Oil for sautéing',
  '4 ekor ikan kakap/baronang': '4 red snapper/rabbit fish',
  '5 siung bawang putih': '5 garlic cloves',
  '3 cm kunyit': '3cm turmeric',
  '2 cm jahe': '2cm ginger',
  '1 sdm ketumbar': '1 tbsp coriander',
  '3 sdm kecap manis': '3 tbsp sweet soy sauce',
  '2 sdm air jeruk nipis': '2 tbsp lime juice',
  'Garam dan merica': 'Salt and pepper',
  'Sambal matah untuk pelengkap': 'Raw shallot sambal for garnish',
  '1 kg buntut sapi potong': '1 kg oxtail, cut',
  '2 liter air': '2 liters water',
  '3 wortel potong': '3 carrots, sliced',
  '3 kentang potong': '3 potatoes, cubed',
  '2 batang seledri': '2 celery stalks',
  '2 batang daun bawang': '2 spring onions',
  '5 siung bawang putih': '5 garlic cloves',
  '3 cm jahe': '3cm ginger',
  '1 sdt merica': '1 tsp pepper',
  'Garam dan kaldu sapi': 'Salt and beef bouillon',
  'Bawang goreng untuk taburan': 'Fried shallots for garnish',
  '500 gr mie telur basah': '500g fresh egg noodles',
  '3 butir telur': '3 eggs',
  '5 siung bawang merah': '5 shallots',
  '3 siung bawang putih': '3 garlic cloves',
  '3 sdm kecap manis': '3 tbsp sweet soy sauce',
  '1 sdt merica': '1 tsp pepper',
  '1 sdt garam': '1 tsp salt',
  '1 batang daun bawang': '1 spring onion',
  'Sayur: kol, sawi, wortel': 'Vegetables: cabbage, mustard greens, carrot',
  'Minyak untuk menumis': 'Oil for sautéing',
  '500 gr kentang potong dadu': '500g potatoes, diced',
  '250 gr hati ayam sapi rebus': '250g boiled chicken liver',
  '5 sdm santan kental': '5 tbsp thick coconut milk',
  '10 buah cabai merah': '10 red chilies',
  '6 siung bawang merah': '6 shallots',
  '4 siung bawang putih': '4 garlic cloves',
  '2 lembar daun salam': '2 Indonesian bay leaves',
  '2 cm lengkuas': '2cm galangal',
  'Garam dan gula secukupnya': 'Salt and sugar to taste',
  'Minyak untuk menggoreng': 'Oil for frying',
  '2 buah wortel iris serong': '2 carrots, diagonally sliced',
  '1 bonggol brokoli': '1 head broccoli',
  '10 buah bakso sapi iris': '10 sliced beef meatballs',
  '5 siung bawang putih cincang': '5 garlic cloves, minced',
  '1 sdm saus tiram': '1 tbsp oyster sauce',
  '1 sdm kecap asin': '1 tbsp soy sauce',
  '1 sdt merica': '1 tsp pepper',
  '1 sdt garam': '1 tsp salt',
  '1 sdm maizena larutkan dengan air': '1 tbsp cornstarch dissolved in water',
  '200 ml air': '200ml water',
  'Minyak untuk menumis': 'Oil for sautéing',
  '4 ekor ikan mas': '4 goldfish',
  '10 buah cabai merah': '10 red chilies',
  '8 siung bawang merah': '8 shallots',
  '5 siung bawang putih': '5 garlic cloves',
  '3 cm kunyit': '3cm turmeric',
  '2 cm jahe': '2cm ginger',
  '3 butir kemiri': '3 candlenuts',
  '2 batang serai iris tipis': '2 lemongrass stalks, thinly sliced',
  '4 lembar daun salam': '4 Indonesian bay leaves',
  'Daun pisang untuk membungkus': 'Banana leaves for wrapping',
  'Garam dan gula secukupnya': 'Salt and sugar to taste',
  '1 kg iga sapi': '1 kg beef ribs',
  '2 liter air': '2 liters water',
  '2 wortel potong': '2 carrots, sliced',
  '2 kentang potong': '2 potatoes, cubed',
  '1 buah tomat potong': '1 tomato, sliced',
  '2 batang seledri': '2 celery stalks',
  '2 batang daun bawang': '2 spring onions',
  '6 siung bawang putih': '6 garlic cloves',
  '1 sdt merica': '1 tsp pepper',
  'Garam dan kaldu sapi': 'Salt and beef bouillon',
  'Bawang goreng': 'Fried shallots',
  '500 gr beras': '500g rice',
  '1 liter santan encer': '1 liter thin coconut milk',
  '5 siung bawang merah iris': '5 shallots, sliced',
  '3 siung bawang putih iris': '3 garlic cloves, sliced',
  '2 batang serai memarkan': '2 lemongrass stalks, bruised',
  '4 lembar daun salam': '4 Indonesian bay leaves',
  '3 cm lengkuas': '3cm galangal',
  'Garam secukupnya': 'Salt to taste',
  'Pelengkap: ayam suwir, telur pindang, sambal': 'Garnish: shredded chicken, pindang eggs, chili sauce',
  '1 ekor ayam kampung': '1 free-range chicken',
  '15 buah cabai merah': '15 red chilies',
  '10 buah cabai rawit': '10 bird\'s eye chilies',
  '8 siung bawang merah': '8 shallots',
  '5 siung bawang putih': '5 garlic cloves',
  '2 cm kencur': '2cm kencur (aromatic ginger)',
  '2 butir kemiri': '2 candlenuts',
  '1 sdt terasi bakar': '1 tsp roasted shrimp paste',
  '200 ml santan': '200ml coconut milk',
  '1 sdm air asam': '1 tbsp tamarind water',
  'Garam dan gula merah': 'Salt and palm sugar',
  '1 kg nangka muda potong': '1 kg young jackfruit, cut',
  '1,5 liter santan': '1.5 liters coconut milk',
  '250 gr gula merah': '250g palm sugar',
  '4 lembar daun salam': '4 Indonesian bay leaves',
  '3 cm lengkuas': '3cm galangal',
  '10 bawang merah': '10 shallots',
  '5 bawang putih': '5 garlic cloves',
  '4 kemiri': '4 candlenuts',
  '2 sdt ketumbar': '2 tsp coriander',
  'Pelengkap: ayam opor, telur pindang, krecek': 'Garnish: chicken opor, pindang eggs, beef skin crackers',
  '6 buah pisang kepok matang': '6 ripe kepok bananas',
  '5 sdm tepung terigu': '5 tbsp all-purpose flour',
  '2 sdm tepung beras': '2 tbsp rice flour',
  '1 sdm gula pasir': '1 tbsp sugar',
  '1 sdt garam': '1 tsp salt',
  '1 sdt vanili': '1 tsp vanilla',
  'Air secukupnya': 'Water as needed',
  'Minyak untuk menggoreng': 'Oil for frying',
  'Topping: gula donat, meses, keju': 'Topping: powdered sugar, chocolate sprinkles, cheese',
  '6 buah tahu putih goreng': '6 fried white tofu',
  '5 siung bawang merah iris': '5 shallots, sliced',
  '3 buah cabai rawit iris': '3 bird\'s eye chilies, sliced',
  '3 sdm kecap manis': '3 tbsp sweet soy sauce',
  '2 sdm air asam jawa': '2 tbsp tamarind water',
  '1 sdm gula merah': '1 tbsp palm sugar',
  'Garam secukupnya': 'Salt to taste',
  '100 ml air matang': '100ml drinking water',
  '100 gr cincau hitam potong': '100g black grass jelly, cubed',
  '100 gr nangka potong': '100g jackfruit, sliced',
  '2 buah alpukat keruk': '2 avocados, scooped',
  '50 gr kolang kaling rebus': '50g boiled sugar palm fruit',
  'Es serut': 'Shaved ice',
  'Sirup gula merah': 'Palm sugar syrup',
  'Susu kental manis': 'Sweetened condensed milk',
  '100 ml santan matang': '100ml cooked coconut milk',
  '500 gr kentang': '500g potatoes',
  '2 butir telur': '2 eggs',
  '3 siung bawang putih goreng': '3 fried garlic cloves',
  '2 batang daun seledri iris': '2 celery stalks, sliced',
  '1 sdt merica': '1 tsp pepper',
  '1 sdt garam': '1 tsp salt',
  'Minyak untuk menggoreng': 'Oil for frying',
  '4 ekor ikan nila': '4 tilapia fish',
  '5 siung bawang putih': '5 garlic cloves',
  '3 cm kunyit': '3cm turmeric',
  '2 cm jahe': '2cm ginger',
  '1 sdm ketumbar': '1 tbsp coriander',
  '3 sdm kecap manis': '3 tbsp sweet soy sauce',
  '2 sdm air jeruk nipis': '2 tbsp lime juice',
  'Garam dan merica': 'Salt and pepper',
  'Sambal kecap pelengkap': 'Sweet soy chili sauce for garnish',
  '200 gr beras': '200g rice',
  '1 liter air kaldu ayam': '1 liter chicken broth',
  '200 gr ayam rebus suwir': '200g boiled shredded chicken',
  '2 lembar daun salam': '2 Indonesian bay leaves',
  '1 sdt garam': '1 tsp salt',
  'Pelengkap: cakwe, telur rebus, seledri, bawang goreng, kecap manis, sambal': 'Garnish: fried dough, boiled egg, celery, fried shallots, sweet soy sauce, chili sauce',
  '1 papan tempe iris tipis': '1 block tempeh, thinly sliced',
  '5 sdm tepung terigu': '5 tbsp all-purpose flour',
  '2 sdm tepung beras': '2 tbsp rice flour',
  '2 siung bawang putih halus': '2 garlic cloves, ground',
  '1 sdt ketumbar': '1 tsp coriander',
  '1 sdt garam': '1 tsp salt',
  '1 batang daun bawang iris': '1 spring onion, sliced',
  'Air secukupnya': 'Water as needed',
  'Minyak untuk menggoreng': 'Oil for frying',
  '1 ekor ayam kampung potong': '1 free-range chicken, cut',
  '1,5 liter air': '1.5 liters water',
  '6 siung bawang putih geprek': '6 garlic cloves, crushed',
  '3 cm jahe memarkan': '3cm ginger, bruised',
  '2 batang serai memarkan': '2 lemongrass stalks, bruised',
  '4 lembar daun jeruk': '4 kaffir lime leaves',
  '2 batang seledri ikat': '2 celery stalks, tied',
  'Garam dan merica': 'Salt and pepper',
  'Bawang goreng untuk taburan': 'Fried shallots for garnish',
  '500 gr daging sapi': '500g beef',
  '250 gr jeroan sapi': '250g beef offal',
  '5 kluwek': '5 kluwek nuts',
  '8 bawang merah': '8 shallots',
  '6 bawang putih': '6 garlic cloves',
  '3 cm jahe': '3cm ginger',
  '2 batang serai': '2 lemongrass stalks',
  'Kelapa parut sangrai': 'Toasted grated coconut',
  '1 sdm ketumbar': '1 tbsp coriander',
  'Bawang goreng': 'Fried shallots',
  '500 gr daging sapi has': '500g beef tenderloin',
  'Tusuk sate': 'Skewers',
  '8 bawang merah': '8 shallots',
  '6 bawang putih': '6 garlic cloves',
  '3 cm jahe': '3cm ginger',
  '2 cm kunyit': '2cm turmeric',
  '1 sdm ketumbar': '1 tbsp coriander',
  '3 sdm tepung beras': '3 tbsp rice flour',
  'Kerupuk dan bawang goreng': 'Crackers and fried shallots',
  '300 gr daging ayam giling': '300g ground chicken',
  '250 gr tuna giling': '250g ground tuna',
  '6 bawang merah': '6 shallots',
  '5 bawang putih': '5 garlic cloves',
  '3 cm kencur': '3cm kencur',
  '2 cm kunyit': '2cm turmeric',
  '2 sdt ketumbar': '2 tsp coriander',
  'Kelapa parut sangrai': 'Toasted grated coconut',
  'Batang serai untuk tusuk': 'Lemongrass stalks for skewers',
  '300 gr daging sapi cincang': '300g minced beef',
  '200 gr kelapa parut': '200g grated coconut',
  '6 bawang merah': '6 shallots',
  '4 bawang putih': '4 garlic cloves',
  '2 sdt ketumbar': '2 tsp coriander',
  'Tusuk sate': 'Skewers',
  'Minyak': 'Oil',
  '500 gr daging kambing muda': '500g young goat meat',
  'Tusuk sate besi': 'Iron skewers',
  'Garam dan merica kasar': 'Salt and coarse pepper',
  '4 siung bawang putih parut': '4 garlic cloves, grated',
  '1 sdm jeruk nipis': '1 tbsp lime juice',
  'Sambal kecap': 'Sweet soy chili sauce',
  '500 gr daging sapi has': '500g beef tenderloin',
  '5 siung bawang putih': '5 garlic cloves',
  '3 cm jahe': '3cm ginger',
  '2 sdm ketumbar': '2 tbsp coriander',
  '3 sdm kecap manis': '3 tbsp sweet soy sauce',
  '1 sdm air asam': '1 tbsp tamarind water',
  'Sambal oncom, ketan bakar': 'Oncom chili sauce, grilled sticky rice',
  '1 kg nangka muda': '1 kg young jackfruit',
  '500 ml santan kental': '500ml thick coconut milk',
  '200 gr gula merah': '200g palm sugar',
  '5 lembar daun salam': '5 Indonesian bay leaves',
  '3 cm lengkuas': '3cm galangal',
  '8 bawang merah': '8 shallots',
  '6 bawang putih': '6 garlic cloves',
  'Telur rebus, tahu, tempe': 'Boiled eggs, tofu, tempeh',
  'Labu siam': 'Chayote',
  'Kacang panjang': 'Long beans',
  '1 terong': '1 eggplant',
  'Daun melinjo': 'Melinjo leaves',
  '200 ml santan': '200ml coconut milk',
  '6 bawang merah': '6 shallots',
  '4 bawang putih': '4 garlic cloves',
  '3 cm lengkuas': '3cm galangal',
  '1 sdt ebi': '1 tsp dried shrimp',
  '4 lontong': '4 rice cakes',
  'Labu siam': 'Chayote',
  'Kacang panjang': 'Long beans',
  '200 ml santan': '200ml coconut milk',
  '6 bawang merah': '6 shallots',
  '4 bawang putih': '4 garlic cloves',
  '3 cm kunyit': '3cm turmeric',
  'Telur rebus, kerupuk': 'Boiled eggs, crackers',
  '200 gr bihun': '200g rice vermicelli',
  '150 gr tauge': '150g bean sprouts',
  'Tahu goreng': 'Fried tofu',
  'Telur rebus': 'Boiled egg',
  'Lontong': 'Rice cake',
  'Kacang tanah, cabe, bawang putih': 'Peanuts, chili, garlic',
  'Kecap manis, kerupuk': 'Sweet soy sauce, crackers',
  '500 gr beras': '500g rice',
  '400 ml santan encer': '400ml thin coconut milk',
  '2 daun pandan': '2 pandan leaves',
  '2 serai': '2 lemongrass stalks',
  '3 daun jeruk': '3 kaffir lime leaves',
  '1 sdt garam': '1 tsp salt',
  'Ayam goreng, tempe orek, telur balado': 'Fried chicken, stir-fried tempeh, spicy eggs',
  '500 gr beras': '500g rice',
  '400 ml santan': '400ml coconut milk',
  'Kunyit parut': 'Grated turmeric',
  '2 serai': '2 lemongrass stalks',
  '3 daun jeruk': '3 kaffir lime leaves',
  '1 sdt garam': '1 tsp salt',
  'Ayam goreng, urap, perkedel': 'Fried chicken, mixed vegetables, potato fritters',
  '1 kg beras': '1 kg rice',
  '800 ml santan': '800ml coconut milk',
  'Kunyit': 'Turmeric',
  '3 serai': '3 lemongrass stalks',
  '5 daun jeruk': '5 kaffir lime leaves',
  'Ayam goreng, urap, telur, perkedel': 'Fried chicken, mixed vegetables, eggs, potato fritters',
  '200 gr beras': '200g rice',
  'Labu kuning': 'Pumpkin',
  '2 wortel': '2 carrots',
  'Bayam': 'Spinach',
  'Kangkung': 'Water spinach',
  'Kemangi': 'Lemon basil',
  '2 serai': '2 lemongrass stalks',
  'Ikan asin, sambal roa': 'Salted fish, roa chili sauce',
  '300 gr daging sapi': '300g beef',
  '200 gr jeroan': '200g offal',
  '8 bawang merah': '8 shallots',
  '6 bawang putih': '6 garlic cloves',
  '3 cm jahe': '3cm ginger',
  '1 sdm ketumbar': '1 tbsp coriander',
  'Bihun, tauge, jeruk nipis': 'Rice vermicelli, bean sprouts, lime',
  '200 gr beras': '200g rice',
  'Labu kuning': 'Pumpkin',
  '2 wortel': '2 carrots',
  'Bayam': 'Spinach',
  'Kangkung': 'Water spinach',
  'Kemangi': 'Lemon basil',
  '2 serai': '2 lemongrass stalks',
  'Ikan asin': 'Salted fish',
  '250 gr tepung ketan': '250g glutinous rice flour',
  '100 gr tepung beras': '100g rice flour',
  'Air daun suji': 'Suji leaf water',
  '150 gr gula merah': '150g palm sugar',
  'Kelapa parut': 'Grated coconut',
  '250 gr tepung ketan': '250g glutinous rice flour',
  'Kacang hijau kupas': 'Peeled mung beans',
  '100 gr gula pasir': '100g sugar',
  'Wijen': 'Sesame seeds',
  'Minyak': 'Oil',
  '200 gr tepung beras': '200g rice flour',
  '200 gr tapioka': '200g tapioca',
  '400 ml santan': '400ml coconut milk',
  '200 gr gula': '200g sugar',
  'Pasta warna': 'Food coloring',
  '200 gr tepung': '200g flour',
  '150 gr gula': '150g sugar',
  '2 telur': '2 eggs',
  '200 ml santan': '200ml coconut milk',
  '100 gr kentang': '100g potatoes',
  'Kismis topping': 'Raisin topping',
  '500 gr tapioka': '500g tapioca',
  '200 gr terigu': '200g flour',
  '400 gr gula': '400g sugar',
  '500 ml santan': '500ml coconut milk',
  '10 telur': '10 eggs',
  'Ragi': 'Yeast',
  '250 gr margarin': '250g margarine',
  '100 gr gula halus': '100g powdered sugar',
  '2 kuning telur': '2 egg yolks',
  '350 gr terigu': '350g flour',
  '50 gr maizena': '50g cornstarch',
  'Gula donat': 'Powdered sugar',
  '250 gr margarin': '250g margarine',
  '2 kuning telur': '2 egg yolks',
  '250 gr terigu': '250g flour',
  '200 gr keju edam': '200g edam cheese',
  '1/2 sdt garam': '½ tsp salt',
  '250 gr margarin': '250g margarine',
  '2 kuning telur': '2 egg yolks',
  '350 gr terigu': '350g flour',
  'Selai nanas': 'Pineapple jam',
  'Olesan kuning telur': 'Egg yolk wash',
  '500 gr ketan': '500g glutinous rice',
  '400 ml santan': '400ml coconut milk',
  '1 sdt garam': '1 tsp salt',
  'Daun pisang': 'Banana leaves',
  'Bambu': 'Bamboo',
  'Rendang': 'Rendang',
  '500 gr ketan': '500g glutinous rice',
  '300 gr gula merah': '300g palm sugar',
  '200 ml santan': '200ml coconut milk',
  '2 daun pandan': '2 pandan leaves',
  '200 gr tape singkong': '200g fermented cassava',
  '100 gr nangka': '100g jackfruit',
  '150 gr kelapa muda': '150g young coconut',
  'Selasih': 'Basil seeds',
  'Es serut': 'Shaved ice',
  'SKM, sirup merah': 'Sweetened condensed milk, red syrup',
  '2 batang jahe': '2 ginger stalks',
  '3 serai': '3 lemongrass stalks',
  '5 cm kayu manis': '5cm cinnamon',
  '3 cengkeh': '3 cloves',
  'Gula pasir': 'Sugar',
  '1 liter air': '1 liter water',
  'Es batu': 'Ice cubes',
  '5 cm jahe': '5cm ginger',
  '2 serai': '2 lemongrass stalks',
  '2 daun jeruk': '2 kaffir lime leaves',
  'Kayu manis': 'Cinnamon',
  '2 cengkeh': '2 cloves',
  'Gula batu': 'Rock sugar',
  '500 ml air': '500ml water',
  '250 gr tepung ketan': '250g glutinous rice flour',
  'Kacang tanah': 'Peanuts',
  'Gula merah': 'Palm sugar',
  'Jahe': 'Ginger',
  'Gula pasir': 'Sugar',
  '500 ml air': '500ml water',
  '5 cm jahe': '5cm ginger',
  '2 serai': '2 lemongrass stalks',
  'Kayu manis': 'Cinnamon',
  '2 cengkeh': '2 cloves',
  'Lada hitam': 'Black pepper',
  'Gula merah': 'Palm sugar',
  '500 ml air': '500ml water',
  '5 cm jahe': '5cm ginger',
  '2 serai': '2 lemongrass stalks',
  'Kacang tanah': 'Peanuts',
  'Kismis': 'Raisins',
  'Kolang-kaling': 'Sugar palm fruit',
  'Cincau': 'Grass jelly',
  '500 ml air': '500ml water',
  '500 ml air nira': '500ml palm sap',
  'Es batu': 'Ice cubes',
  'Jeruk nipis': 'Lime',
  '200 gr tepung beras': '200g rice flour',
  '100 gr tapioka': '100g tapioca',
  '400 ml santan': '400ml coconut milk',
  'Gula pasir': 'Sugar',
  'Pasta pandan': 'Pandan paste',
  'Sirup gula merah': 'Palm sugar syrup',
  '150 gr tepung beras': '150g rice flour',
  '75 gr hunkwe': '75g mung bean flour',
  'Pasta pandan': 'Pandan paste',
  '300 gr gula aren': '300g palm sugar',
  '500 ml santan': '500ml coconut milk',
  'Es serut': 'Shaved ice',
  '2 kelapa muda': '2 young coconuts',
  '200 ml air kelapa': '200ml coconut water',
  'SKM': 'Sweetened condensed milk',
  'Sirup cocopandan': 'Cocopandan syrup',
  'Es batu': 'Ice cubes',
  '1 ayam kampung': '1 free-range chicken',
  '8 bawang merah': '8 shallots',
  '6 bawang putih': '6 garlic cloves',
  '5 cm kunyit': '5cm turmeric',
  '5 cm jahe': '5cm ginger',
  '3 serai': '3 lemongrass stalks',
  'Daun pisang': 'Banana leaves',
  '3 potong ayam tepung': '3 pieces fried chicken',
  '15 cabe rawit': '15 bird\'s eye chilies',
  '5 bawang putih': '5 garlic cloves',
  '1 sdt garam': '1 tsp salt',
  'Minyak panas': 'Hot oil',
  '1 ayam potong 8': '1 chicken, cut into 8 pieces',
  '5 bawang putih': '5 garlic cloves',
  '3 cm jahe': '3cm ginger',
  'Air kelapa': 'Coconut water',
  'Sambal lado mudo': 'Green chili sambal',
  '500 gr jengkol': '500g jengkol (dog fruit)',
  '500 ml santan': '500ml coconut milk',
  '8 bawang merah': '8 shallots',
  '6 bawang putih': '6 garlic cloves',
  '5 cabe merah': '5 red chilies',
  '3 cm jahe': '3cm ginger',
  '2 serai': '2 lemongrass stalks',
  '500 gr daging sapi': '500g beef',
  '8 cabe merah': '8 red chilies',
  '6 cabe rawit': '6 bird\'s eye chilies',
  '6 bawang merah': '6 shallots',
  '4 bawang putih': '4 garlic cloves',
  '3 cm jahe': '3cm ginger',
  '300 gr usus sapi': '300g beef intestine',
  '200 ml santan': '200ml coconut milk',
  '6 bawang merah': '6 shallots',
  '4 bawang putih': '4 garlic cloves',
  '3 cm kunyit': '3cm turmeric',
  '2 serai': '2 lemongrass stalks',
  '500 gr daging sapi': '500g beef',
  '500 ml santan': '500ml coconut milk',
  '8 bawang merah': '8 shallots',
  '6 bawang putih': '6 garlic cloves',
  '5 cabe merah': '5 red chilies',
  '3 cm jahe': '3cm ginger',
  '2 serai': '2 lemongrass stalks',
  '1 kg ikan patin': '1 kg patin fish',
  '6 bawang merah': '6 shallots',
  '4 bawang putih': '4 garlic cloves',
  '3 cm jahe': '3cm ginger',
  '2 serai': '2 lemongrass stalks',
  '5 cabe rawit': '5 bird\'s eye chilies',
  'Asam jawa': 'Tamarind',
  '300 gr tempoyak': '300g fermented durian',
  '200 gr ikan patin': '200g patin fish',
  '6 cabe rawit': '6 bird\'s eye chilies',
  '4 bawang merah': '4 shallots',
  '3 bawang putih': '3 garlic cloves',
  '2 cm jahe': '2cm ginger',
  '500 gr mie basah': '500g fresh noodles',
  '200 gr daging iris': '200g sliced beef',
  '150 gr udang': '150g shrimp',
  '8 cabe merah': '8 red chilies',
  '6 bawang merah': '6 shallots',
  '1 sdm bubuk kari': '1 tbsp curry powder',
  'Tauge': 'Bean sprouts',
  '1 kg daging kambing': '1 kg goat meat',
  '500 gr nangka muda': '500g young jackfruit',
  '8 bawang merah': '8 shallots',
  '6 bawang putih': '6 garlic cloves',
  '5 cabe merah': '5 red chilies',
  '3 cm kunyit': '3cm turmeric',
  '3 serai': '3 lemongrass stalks',
  '500 gr daging kambing': '500g goat meat',
  '2 liter air': '2 liters water',
  '8 bawang merah': '8 shallots',
  '6 bawang putih': '6 garlic cloves',
  '3 cm jahe': '3cm ginger',
  '1 sdt merica': '1 tsp pepper',
  'Daun bawang': 'Spring onion',
  '1/2 ekor ayam': '½ chicken',
  '2 liter air': '2 liters water',
  '6 bawang merah': '6 shallots',
  '4 bawang putih': '4 garlic cloves',
  '3 cm jahe': '3cm ginger',
  'Soun, telur rebus, jamur': 'Glass noodles, boiled egg, mushrooms',
  '400 gr daging kambing': '400g goat meat',
  '200 gr kol': '200g cabbage',
  '2 tomat': '2 tomatoes',
  '6 bawang merah': '6 shallots',
  '4 bawang putih': '4 garlic cloves',
  '3 sdm kecap': '3 tbsp sweet soy sauce',
  '2 daun jeruk': '2 kaffir lime leaves',
  '3 piring nasi': '3 plates rice',
  '200 gr oncom': '200g oncom (fermented soybean)',
  '5 cabe rawit': '5 bird\'s eye chilies',
  '3 siung bawang putih': '3 garlic cloves',
  '3 cm kencur': '3cm kencur',
  'Daun kemangi': 'Lemon basil leaves',
  '4 ketupat': '4 woven rice cakes',
  '4 tahu goreng': '4 fried tofu',
  '150 gr tauge': '150g bean sprouts',
  'Kacang tanah': 'Peanuts',
  '5 cabe rawit': '5 bird\'s eye chilies',
  '3 bawang putih': '3 garlic cloves',
  'Kecap manis': 'Sweet soy sauce',
  '200 gr tepung beras': '200g rice flour',
  '100 gr terigu': '100g flour',
  '400 ml santan': '400ml coconut milk',
  '100 gr gula': '100g sugar',
  'Ragi': 'Yeast',
  'Topping sesuai selera': 'Toppings as desired',
  '200 gr terigu': '200g flour',
  '2 telur': '2 eggs',
  '400 ml santan': '400ml coconut milk',
  'Pasta pandan': 'Pandan paste',
  'Kelapa parut, gula merah': 'Grated coconut, palm sugar',
  '500 gr ketan': '500g glutinous rice',
  '400 ml santan': '400ml coconut milk',
  '200 gr ayam suwir': '200g shredded chicken',
  '4 bawang merah': '4 shallots',
  '3 bawang putih': '3 garlic cloves',
  'Daun pisang': 'Banana leaves',
  '500 gr beras': '500g rice',
  '400 ml santan': '400ml coconut milk',
  '150 gr daging cincang': '150g minced beef',
  '4 bawang merah': '4 shallots',
  '3 bawang putih': '3 garlic cloves',
  'Daun pisang': 'Banana leaves',
  '200 gr tepung beras': '200g rice flour',
  '150 gr gula merah': '150g palm sugar',
  '100 gr kelapa parut': '100g grated coconut',
  'Daun pandan': 'Pandan leaves',
  'Cetakan bambu': 'Bamboo molds',
  '250 gr tapioka': '250g tapioca',
  '100 gr tepung beras': '100g rice flour',
  'Pasta warna': 'Food coloring',
  'Kelapa parut': 'Grated coconut',
  'Gula merah cair': 'Liquid palm sugar',
  '500 gr singkong': '500g cassava',
  '100 gr gula': '100g sugar',
  '1/2 sdt vanili': '½ tsp vanilla',
  'Kelapa parut': 'Grated coconut',
  '200 gr tepung ketan': '200g glutinous rice flour',
  '150 gr gula': '150g sugar',
  'Kacang tanah sangrai': 'Toasted peanuts',
  'Maizena': 'Cornstarch',
  '200 gr terigu': '200g flour',
  '150 gr gula': '150g sugar',
  '2 telur': '2 eggs',
  '200 ml susu': '200ml milk',
  'BP, soda': 'Baking powder, baking soda',
  'Topping meses': 'Chocolate sprinkles topping',
  '250 gr terigu': '250g flour',
  '150 gr gula': '150g sugar',
  '2 telur': '2 eggs',
  '350 ml santan': '350ml coconut milk',
  'Ragi': 'Yeast',
  'Topping': 'Topping',
  '300 gr terigu': '300g flour',
  '150 gr margarin': '150g margarine',
  'Kacang hijau kupas': 'Peeled mung beans',
  '100 gr gula': '100g sugar',
  '250 gr tepung ketan': '250g glutinous rice flour',
  '200 gr kelapa parut': '200g grated coconut',
  '200 gr gula': '200g sugar',
  '200 ml santan': '200ml coconut milk',
};

// Complete instruction translations
const instructionTranslations = {
  'Panaskan minyak, tumis bawang merah dan bawang putih hingga harum.': 'Heat oil, sauté shallots and garlic until fragrant.',
  'Sisihkan ke pinggir wajan, masukkan telur, orak-arik hingga matang.': 'Push to the side of the wok, add eggs, scramble until cooked.',
  'Masukkan nasi, aduk rata dengan api besar.': 'Add rice, stir well over high heat.',
  'Tambahkan kecap manis, garam, merica. Aduk cepat hingga merata.': 'Add sweet soy sauce, salt, pepper. Stir quickly until evenly distributed.',
  'Masak 3-5 menit hingga nasi sedikit kering.': 'Cook 3-5 minutes until rice is slightly dry.',
  'Sajikan hangat dengan kerupuk, acar, dan irisan tomat.': 'Serve hot with crackers, pickles, and sliced tomato.',
  'Tumis bumbu halus hingga matang dan minyak terpisah.': 'Sauté ground spices until cooked and oil separates.',
  'Masukkan daging, aduk hingga berubah warna.': 'Add beef, stir until color changes.',
  'Tuang santan, masak dengan api sedang sambil diaduk.': 'Pour coconut milk, cook over medium heat while stirring.',
  'Kecilkan api, masak 3-4 jam hingga santan menyusut.': 'Reduce heat, cook 3-4 hours until coconut milk reduces.',
  'Aduk sesekali agar tidak gosong.': 'Stir occasionally to prevent burning.',
  'Masak hingga rendang berwarna coklat gelap kehitaman.': 'Cook until rendang turns dark brownish-black.',
  'Sajikan dengan nasi hangat.': 'Serve with warm rice.',
  'Marinasi ayam dengan kecap dan minyak, diamkan 45 menit.': 'Marinate chicken with sweet soy sauce and oil, let sit 45 minutes.',
  'Tusukkan ayam ke tusuk sate.': 'Thread chicken onto skewers.',
  'Haluskan bahan bumbu kacang, tambahkan air hingga kekentalan pas.': 'Grind peanut sauce ingredients, add water to desired consistency.',
  'Panggang sate di atas bara api, bolak-balik sambil dioles bumbu.': 'Grill satay over charcoal, flip while basting with sauce.',
  'Sajikan dengan bumbu kacang dan lontong.': 'Serve with peanut sauce and rice cake.',
  'Rebus ayam dengan air, buang busa. Masukkan serai dan daun jeruk.': 'Boil chicken in water, discard foam. Add lemongrass and lime leaves.',
  'Tumis bumbu halus hingga harum, masukkan ke rebusan ayam.': 'Sauté ground spices until fragrant, add to chicken broth.',
  'Masak hingga ayam empuk. Angkat ayam, goreng sebentar, suwir.': 'Cook until chicken is tender. Remove, fry briefly, shred.',
  'Saring kuah, didihkan kembali. Koreksi rasa.': 'Strain broth, bring to boil again. Adjust seasoning.',
  'Sajikan dengan nasi, soun, kol, suwiran ayam, telur rebus, dan kuah.': 'Serve with rice, glass noodles, cabbage, shredded chicken, boiled egg, and broth.',
  'Siapkan semua sayuran rebus dan bahan di piring.': 'Arrange all boiled vegetables and ingredients on a plate.',
  'Haluskan bumbu kacang, tambahkan air hangat hingga kekentalan pas.': 'Grind peanut sauce, add warm water to desired consistency.',
  'Siram bumbu kacang di atas tatanan sayur.': 'Pour peanut sauce over the arranged vegetables.',
  'Taburi bawang goreng, sajikan dengan kerupuk emping.': 'Sprinkle fried shallots, serve with melinjo crackers.',
  'Campur daging giling, garam, merica, bawang putih. Uleni.': 'Mix ground beef, salt, pepper, garlic. Knead.',
  'Tambahkan putih telur dan tepung tapioka, uleni hingga kalis.': 'Add egg whites and tapioca flour, knead until smooth.',
  'Bentuk bola-bola, rebus dalam air mendidih hingga mengapung.': 'Shape into balls, boil in water until they float.',
  'Rendam bakso dalam air es agar kenyal.': 'Soak meatballs in ice water for elasticity.',
  'Kuah: didihkan kaldu, bumbui, masukkan bakso.': 'Broth: bring broth to boil, season, add meatballs.',
  'Sajikan dengan mi, bihun, sawi, dan pelengkap lainnya.': 'Serve with noodles, vermicelli, mustard greens, and other garnishes.',
  'Campur terigu, gula, garam, ragi, dan susu. Diamkan 45-60 menit.': 'Mix flour, sugar, salt, yeast, and milk. Let rest 45-60 minutes.',
  'Tambahkan telur, baking powder, soda kue. Aduk rata.': 'Add eggs, baking powder, baking soda. Stir well.',
  'Panaskan wajan martabak, tuang adonan.': 'Heat martabak pan, pour batter.',
  'Tunggu gelembung, taburi gula pasir. Tutup, masak hingga matang.': 'Wait for bubbles, sprinkle sugar. Cover, cook until done.',
  'Olesi margarin, taburi topping, lipat, potong-potong.': 'Spread margarine, add toppings, fold, slice.',
  'Campur tepung dan air, masak hingga mengental.': 'Mix flour and water, cook until thickened.',
  'Cetak cendol ke air es.': 'Press cendol into ice water.',
  'Rebus gula aren dengan air dan pandan hingga mengental.': 'Boil palm sugar with water and pandan until thickened.',
  'Rebus santan dengan garam dan pandan, jangan sampai mendidih.': 'Boil coconut milk with salt and pandan, do not let it boil.',
  'Sajikan cendol dengan es serut, sirup, dan santan.': 'Serve cendol with shaved ice, syrup, and coconut milk.',
  'Campur ikan, air es, garam, telur. Uleni.': 'Mix fish, ice water, salt, egg. Knead.',
  'Masukkan tepung sagu sedikit demi sedikit.': 'Add sago flour gradually.',
  'Bentuk kapal selam: pipihkan adonan, isi telur, tutup rapat.': 'Shape submarine: flatten dough, fill with egg, seal tightly.',
  'Rebus hingga mengapung. Tiriskan.': 'Boil until floating. Drain.',
  'Goreng hingga keemasan.': 'Fry until golden.',
  'Cuko: rebus semua bahan cuko hingga mendidih, saring.': 'Cuko sauce: boil all sauce ingredients, strain.',
  'Keruk daging alpukat, potong nangka, keruk kelapa muda.': 'Scoop avocado, cut jackfruit, scoop young coconut.',
  'Masukkan semua buah ke gelas.': 'Add all fruits to glass.',
  'Tambahkan es serut hingga penuh.': 'Add shaved ice until full.',
  'Tuang sirup dan susu kental manis.': 'Pour syrup and sweetened condensed milk.',
  'Aduk rata, sajikan segera.': 'Stir well, serve immediately.',
  'Haluskan bawang putih, kunyit, jahe, ketumbar, garam.': 'Grind garlic, turmeric, ginger, coriander, salt.',
  'Lumuri ayam dengan bumbu halus dan lengkuas parut.': 'Coat chicken with ground spices and grated galangal.',
  'Rebus ayam dengan bumbu dan sedikit air hingga empuk dan air habis.': 'Boil chicken with spices and a little water until tender and water evaporates.',
  'Panaskan minyak, goreng ayam hingga kecoklatan.': 'Heat oil, fry chicken until golden brown.',
  'Goreng juga sisa bumbu lengkuas hingga kering untuk taburan.': 'Also fry remaining galangal spices until dry for garnish.',
  'Sajikan dengan nasi hangat dan sambal.': 'Serve with warm rice and chili sauce.',
  'Haluskan bawang merah, bawang putih, cabai, dan belacan.': 'Grind shallots, garlic, chili, and shrimp paste.',
  'Panaskan minyak, tumis bumbu halus hingga harum.': 'Heat oil, sauté ground spices until fragrant.',
  'Masukkan kangkung, aduk cepat hingga layu.': 'Add water spinach, stir quickly until wilted.',
  'Tambahkan gula dan garam. Koreksi rasa.': 'Add sugar and salt. Adjust seasoning.',
  'Angkat dan sajikan segera.': 'Remove and serve immediately.',
  'Haluskan bawang putih, kunyit, jahe, ketumbar, garam.': 'Grind garlic, turmeric, ginger, coriander, salt.',
  'Lumuri ikan dengan bumbu halus, kecap, dan air jeruk. Diamkan 30 menit.': 'Coat fish with ground spices, sweet soy sauce, and lime juice. Let sit 30 minutes.',
  'Panggang ikan di atas bara api sambil dioles sisa bumbu.': 'Grill fish over charcoal while basting with remaining spices.',
  'Balik ikan, panggang hingga kedua sisi matang.': 'Flip fish, grill until both sides are cooked.',
  'Sajikan dengan sambal matah dan nasi hangat.': 'Serve with raw shallot sambal and warm rice.',
  'Rebus buntut sapi hingga empuk (bisa pakai presto 45 menit).': 'Boil oxtail until tender (can use pressure cooker 45 minutes).',
  'Angkat buntut, saring kaldunya.': 'Remove oxtail, strain the broth.',
  'Haluskan bawang putih, jahe, dan merica.': 'Grind garlic, ginger, and pepper.',
  'Tumis bumbu halus hingga harum, masukkan ke kaldu.': 'Sauté ground spices until fragrant, add to broth.',
  'Masukkan wortel dan kentang. Masak hingga empuk.': 'Add carrots and potatoes. Cook until tender.',
  'Masukkan buntut, garam, dan kaldu bubuk. Koreksi rasa.': 'Add oxtail, salt, and bouillon powder. Adjust seasoning.',
  'Taburi seledri, daun bawang, dan bawang goreng.': 'Garnish with celery, spring onions, and fried shallots.',
  'Rebus mie sebentar, tiriskan. Beri sedikit minyak.': 'Blanch noodles briefly, drain. Toss with a little oil.',
  'Haluskan bawang merah dan bawang putih.': 'Grind shallots and garlic.',
  'Tumis bumbu halus hingga harum. Masukkan telur, orak-arik.': 'Sauté ground spices until fragrant. Add eggs, scramble.',
  'Masukkan sayuran, aduk hingga layu.': 'Add vegetables, stir until wilted.',
  'Masukkan mie, kecap manis, merica, garam. Aduk rata.': 'Add noodles, sweet soy sauce, pepper, salt. Stir well.',
  'Masukkan daun bawang, aduk sebentar. Sajikan.': 'Add spring onions, stir briefly. Serve.',
  'Goreng kentang hingga matang, sisihkan.': 'Fry potatoes until cooked, set aside.',
  'Haluskan cabai, bawang merah, bawang putih.': 'Grind chili, shallots, garlic.',
  'Tumis bumbu halus dengan daun salam dan lengkuas hingga harum.': 'Sauté ground spices with bay leaves and galangal until fragrant.',
  'Masukkan hati, aduk rata.': 'Add liver, stir well.',
  'Tambahkan santan, garam, dan gula. Masak hingga kuah mengental.': 'Add coconut milk, salt, and sugar. Cook until sauce thickens.',
  'Masukkan kentang goreng, aduk rata. Sajikan.': 'Add fried potatoes, stir well. Serve.',
  'Panaskan minyak, tumis bawang putih hingga harum.': 'Heat oil, sauté garlic until fragrant.',
  'Masukkan bakso, aduk hingga berubah warna.': 'Add meatballs, stir until color changes.',
  'Masukkan wortel dan brokoli, aduk rata.': 'Add carrots and broccoli, stir well.',
  'Tuang air, saus tiram, kecap asin, merica, garam.': 'Add water, oyster sauce, soy sauce, pepper, salt.',
  'Masak hingga sayuran matang.': 'Cook until vegetables are done.',
  'Tuang larutan maizena, aduk hingga kuah mengental. Sajikan.': 'Pour cornstarch solution, stir until sauce thickens. Serve.',
  'Haluskan cabai, bawang, kunyit, jahe, kemiri.': 'Grind chili, shallots, turmeric, ginger, candlenuts.',
  'Lumuri ikan dengan bumbu halus, garam, dan gula.': 'Coat fish with ground spices, salt, and sugar.',
  'Tambahkan serai iris dan daun salam.': 'Add sliced lemongrass and bay leaves.',
  'Bungkus ikan dengan daun pisang, semat lidi.': 'Wrap fish in banana leaves, secure with toothpicks.',
  'Kukus pepes selama 30 menit hingga matang.': 'Steam pepes for 30 minutes until done.',
  'Bakar sebentar di atas grill agar lebih wangi. Sajikan.': 'Grill briefly for extra aroma. Serve.',
  'Rebus iga sapi hingga empuk (presto 40 menit).': 'Boil beef ribs until tender (pressure cooker 40 minutes).',
  'Saring kaldu, sisihkan.': 'Strain broth, set aside.',
  'Haluskan bawang putih dan merica.': 'Grind garlic and pepper.',
  'Tumis bumbu halus hingga harum, masukkan ke kaldu.': 'Sauté ground spices until fragrant, add to broth.',
  'Masukkan wortel dan kentang, masak hingga empuk.': 'Add carrots and potatoes, cook until tender.',
  'Masukkan iga, tomat, garam, kaldu bubuk.': 'Add ribs, tomato, salt, bouillon powder.',
  'Sajikan dengan seledri, daun bawang, dan bawang goreng.': 'Serve with celery, spring onions, and fried shallots.',
  'Cuci beras hingga bersih, tiriskan.': 'Wash rice until clean, drain.',
  'Tumis bawang merah dan bawang putih hingga harum.': 'Sauté shallots and garlic until fragrant.',
  'Masukkan beras, serai, daun salam, lengkuas, garam. Aduk rata.': 'Add rice, lemongrass, bay leaves, galangal, salt. Stir well.',
  'Tuang santan, masak dengan api kecil hingga mendidih.': 'Pour coconut milk, cook over low heat until boiling.',
  'Aduk sesekali, masak hingga santan terserap.': 'Stir occasionally, cook until coconut milk is absorbed.',
  'Kukus nasi hingga matang sempurna (30 menit).': 'Steam rice until perfectly cooked (30 minutes).',
  'Sajikan dengan pelengkap.': 'Serve with garnishes.',
  'Haluskan semua bumbu halus. Tumis hingga harum.': 'Grind all spice paste ingredients. Sauté until fragrant.',
  'Masukkan santan, air asam, garam, gula. Masak hingga mendidih.': 'Add coconut milk, tamarind water, salt, sugar. Cook until boiling.',
  'Masukkan ayam, masak dengan api kecil hingga bumbu meresap.': 'Add chicken, cook over low heat until spices are absorbed.',
  'Panggang ayam sambil diolesi sisa bumbu hingga kecoklatan.': 'Grill chicken while basting with remaining spices until golden brown.',
  'Sajikan dengan nasi hangat dan plecing kangkung.': 'Serve with warm rice and plecing kangkung.',
  'Rebus nangka 2x untuk hilangkan getah. Tiriskan.': 'Boil jackfruit twice to remove sap. Drain.',
  'Tumis bumbu halus hingga harum.': 'Sauté ground spices until fragrant.',
  'Masukkan nangka, santan, dan gula merah.': 'Add jackfruit, coconut milk, and palm sugar.',
  'Masak dengan api kecil 3-4 jam hingga empuk dan mengental.': 'Cook over low heat 3-4 hours until tender and thickened.',
  'Sajikan dengan ayam opor, telur pindang, dan krecek.': 'Serve with chicken opor, pindang eggs, and beef skin crackers.',
  'Campur semua tepung, gula, garam, vanili. Beri air sedikit demi sedikit.': 'Mix all flours, sugar, salt, vanilla. Add water gradually.',
  'Aduk hingga adonan kental tidak bergerindil.': 'Stir until batter is thick and smooth.',
  'Belah pisang memanjang, celupkan ke adonan.': 'Slice banana lengthwise, dip in batter.',
  'Goreng dalam minyak panas hingga kuning keemasan.': 'Fry in hot oil until golden yellow.',
  'Angkat, tiriskan. Beri topping sesuai selera.': 'Remove, drain. Add toppings as desired.',
  'Potong tahu goreng kecil-kecil, letakkan di piring.': 'Cut fried tofu into small pieces, place on plate.',
  'Campur bawang merah, cabai, kecap, air asam, gula, garam, dan air.': 'Mix shallots, chili, sweet soy sauce, tamarind water, sugar, salt, and water.',
  'Aduk rata bumbu hingga gula larut.': 'Stir sauce well until sugar dissolves.',
  'Siram bumbu ke atas tahu.': 'Pour sauce over tofu.',
  'Sajikan segera selagi hangat.': 'Serve immediately while warm.',
  'Siapkan semua bahan dalam mangkuk.': 'Arrange all ingredients in a bowl.',
  'Masukkan es serut ke gelas saji.': 'Add shaved ice to serving glass.',
  'Tata cincau, nangka, alpukat, kolang kaling.': 'Arrange grass jelly, jackfruit, avocado, sugar palm fruit.',
  'Tuang sirup gula merah, susu kental manis, dan santan.': 'Pour palm sugar syrup, sweetened condensed milk, and coconut milk.',
  'Sajikan segera.': 'Serve immediately.',
  'Kupas kentang, potong, goreng hingga empuk.': 'Peel potatoes, cut, fry until tender.',
  'Haluskan kentang selagi panas.': 'Mash potatoes while hot.',
  'Campur dengan bawang putih goreng halus, seledri, merica, garam.': 'Mix with finely ground fried garlic, celery, pepper, salt.',
  'Tambahkan 1 butir telur, aduk rata.': 'Add 1 egg, stir well.',
  'Bentuk bulat pipih.': 'Shape into flat rounds.',
  'Celupkan ke telur kocok, goreng hingga kecoklatan.': 'Dip in beaten egg, fry until golden brown.',
  'Haluskan bawang putih, kunyit, jahe, ketumbar, garam.': 'Grind garlic, turmeric, ginger, coriander, salt.',
  'Lumuri ikan dengan bumbu halus dan air jeruk. Diamkan 20 menit.': 'Coat fish with ground spices and lime juice. Let sit 20 minutes.',
  'Panggang ikan di atas bara api atau grill.': 'Grill fish over charcoal or grill.',
  'Olesi kecap manis saat membakar.': 'Baste with sweet soy sauce while grilling.',
  'Sajikan dengan sambal kecap dan lalapan.': 'Serve with sweet soy chili sauce and fresh vegetables.',
  'Cuci beras, rebus dengan air kaldu dan daun salam.': 'Wash rice, boil with broth and bay leaves.',
  'Masak dengan api kecil sambil diaduk hingga menjadi bubur.': 'Cook over low heat while stirring until it becomes porridge.',
  'Tambahkan garam, aduk rata.': 'Add salt, stir well.',
  'Sajikan bubur dengan suwiran ayam dan pelengkap.': 'Serve porridge with shredded chicken and garnishes.',
  'Campur semua tepung, bawang putih, ketumbar, garam, daun bawang.': 'Mix all flours, garlic, coriander, salt, spring onion.',
  'Beri air sedikit demi sedikit hingga adonan kental.': 'Add water gradually until batter is thick.',
  'Celupkan irisan tempe ke adonan.': 'Dip tempeh slices in batter.',
  'Goreng dalam minyak panas sebentar saja (tidak sampai kering).': 'Fry in hot oil briefly (not until crispy).',
  'Angkat, sajikan hangat dengan sambal kecap.': 'Remove, serve warm with sweet soy chili sauce.',
  'Rebus ayam dengan air hingga mendidih. Buang busa.': 'Boil chicken in water until boiling. Discard foam.',
  'Masukkan bawang putih, jahe, serai, daun jeruk, seledri.': 'Add garlic, ginger, lemongrass, lime leaves, celery.',
  'Masak dengan api kecil hingga ayam empuk.': 'Cook over low heat until chicken is tender.',
  'Tambahkan garam dan merica. Koreksi rasa.': 'Add salt and pepper. Adjust seasoning.',
  'Sajikan dengan taburan bawang goreng.': 'Serve with fried shallot garnish.',
  'Rebus daging dan jeroan hingga empuk. Potong.': 'Boil beef and offal until tender. Cut.',
  'Haluskan kluwek, bawang, jahe, ketumbar.': 'Grind kluwek, shallots, ginger, coriander.',
  'Tumis bumbu dengan serai.': 'Sauté spices with lemongrass.',
  'Campur ke kaldu, tambahkan daging.': 'Add to broth, add beef.',
  'Masak hingga mendidih. Taburi kelapa sangrai.': 'Cook until boiling. Sprinkle toasted coconut.',
  'Rebus daging, potong dadu. Tusuk.': 'Boil beef, dice. Skewer.',
  'Haluskan bawang, jahe, kunyit, ketumbar.': 'Grind shallots, ginger, turmeric, coriander.',
  'Tumis bumbu, tambahkan kaldu. Kentalkan.': 'Sauté spices, add broth. Thicken.',
  'Panggang sate di atas bara.': 'Grill satay over charcoal.',
  'Sajikan dengan siraman kuah kental.': 'Serve with thick sauce drizzle.',
  'Campur daging, bumbu halus, kelapa sangrai.': 'Mix meat, ground spices, toasted coconut.',
  'Bentuk pada batang serai.': 'Shape onto lemongrass stalks.',
  'Panggang di atas bara hingga matang.': 'Grill over charcoal until done.',
  'Sajikan dengan sambal matah.': 'Serve with raw shallot sambal.',
  'Campur daging, kelapa, bumbu halus.': 'Mix meat, coconut, ground spices.',
  'Bentuk pada tusuk sate.': 'Shape onto skewers.',
  'Panggang hingga matang.': 'Grill until done.',
  'Potong daging dadu besar.': 'Cut meat into large cubes.',
  'Lumuri garam, merica, bawang putih.': 'Coat with salt, pepper, garlic.',
  'Tusuk, panggang di atas bara.': 'Skewer, grill over charcoal.',
  'Sajikan dengan sambal kecap.': 'Serve with sweet soy chili sauce.',
  'Iris daging tipis.': 'Slice meat thinly.',
  'Marinasi dengan bumbu 1 jam.': 'Marinate with spices for 1 hour.',
  'Tusuk, panggang sambil dioles bumbu.': 'Skewer, grill while basting with spices.',
  'Sajikan dengan sambal oncom.': 'Serve with oncom chili sauce.',
  'Potong nangka, rebus.': 'Cut jackfruit, boil.',
  'Tumis bumbu halus.': 'Sauté ground spices.',
  'Masukkan nangka, santan, gula.': 'Add jackfruit, coconut milk, sugar.',
  'Masak 3-4 jam hingga kuah mengental.': 'Cook 3-4 hours until sauce thickens.',
  'Haluskan bawang, ebi.': 'Grind shallots, dried shrimp.',
  'Tumis dengan lengkuas.': 'Sauté with galangal.',
  'Masukkan sayuran, air.': 'Add vegetables, water.',
  'Tuang santan, masak hingga empuk.': 'Pour coconut milk, cook until tender.',
  'Haluskan bawang, kunyit.': 'Grind shallots, turmeric.',
  'Tumis bumbu.': 'Sauté spices.',
  'Masukkan sayuran, santan.': 'Add vegetables, coconut milk.',
  'Sajikan lontong dengan siraman sayur.': 'Serve rice cake with vegetable sauce.',
  'Haluskan kacang, cabe, bawang.': 'Grind peanuts, chili, garlic.',
  'Tambahkan air dan kecap.': 'Add water and sweet soy sauce.',
  'Tata bihun, tauge, tahu, lontong.': 'Arrange vermicelli, bean sprouts, tofu, rice cake.',
  'Siram bumbu kacang.': 'Pour peanut sauce.',
  'Cuci beras.': 'Wash rice.',
  'Rebus santan dengan daun pandan, serai.': 'Boil coconut milk with pandan leaves, lemongrass.',
  'Masak beras hingga matang.': 'Cook rice until done.',
  'Sajikan dengan pelengkap.': 'Serve with garnishes.',
  'Cuci beras.': 'Wash rice.',
  'Rebus santan dengan kunyit, serai.': 'Boil coconut milk with turmeric, lemongrass.',
  'Masak beras hingga matang.': 'Cook rice until done.',
  'Sajikan dengan pelengkap.': 'Serve with garnishes.',
  'Masak nasi kuning.': 'Cook yellow rice.',
  'Cetak berbentuk kerucut.': 'Mold into cone shape.',
  'Hias dengan pelengkap.': 'Decorate with garnishes.',
  'Sajikan untuk acara selamatan.': 'Serve for celebration events.',
  'Rebus beras hingga jadi bubur.': 'Boil rice until it becomes porridge.',
  'Masukkan labu dan wortel.': 'Add pumpkin and carrots.',
  'Masukkan bayam, kangkung, kemangi.': 'Add spinach, water spinach, lemon basil.',
  'Sajikan dengan ikan asin.': 'Serve with salted fish.',
  'Rebus daging dan jeroan.': 'Boil beef and offal.',
  'Haluskan bumbu.': 'Grind spices.',
  'Tumis, campur ke kaldu.': 'Sauté, add to broth.',
  'Sajikan dengan bihun dan tauge.': 'Serve with vermicelli and bean sprouts.',
  'Rebus beras hingga jadi bubur.': 'Boil rice until it becomes porridge.',
  'Masukkan labu dan wortel.': 'Add pumpkin and carrots.',
  'Masukkan sayuran hijau.': 'Add green vegetables.',
  'Sajikan dengan ikan asin goreng.': 'Serve with fried salted fish.',
  'Campur tepung, garam.': 'Mix flour, salt.',
  'Tuang air daun suji, uleni.': 'Pour suji leaf water, knead.',
  'Isi gula merah, bulatkan.': 'Fill with palm sugar, shape into balls.',
  'Rebus, gulingkan di kelapa.': 'Boil, roll in grated coconut.',
  'Kukus kacang hijau, haluskan.': 'Steam mung beans, grind.',
  'Buat adonan, isi kacang hijau.': 'Make dough, fill with mung beans.',
  'Gulingkan di wijen.': 'Roll in sesame seeds.',
  'Goreng hingga kecoklatan.': 'Fry until golden brown.',
  'Campur tepung, santan.': 'Mix flour, coconut milk.',
  'Bagi adonan, beri warna.': 'Divide batter, add coloring.',
  'Kukus lapis demi lapis.': 'Steam layer by layer.',
  'Potong setelah dingin.': 'Cut after cooling.',
  'Kocok telur dan gula.': 'Beat eggs and sugar.',
  'Masukkan kentang, santan, tepung.': 'Add potatoes, coconut milk, flour.',
  'Tuang ke cetakan.': 'Pour into molds.',
  'Beri topping, masak hingga matang.': 'Add topping, cook until done.',
  'Rebus santan, dinginkan.': 'Boil coconut milk, cool.',
  'Kocok telur dan gula.': 'Beat eggs and sugar.',
  'Campur semua, diamkan 1-2 jam.': 'Mix all, let rest 1-2 hours.',
  'Panggang hingga matang.': 'Bake until done.',
  'Kocok margarin dan gula.': 'Beat margarine and sugar.',
  'Masukkan tepung.': 'Add flour.',
  'Bentuk bulan sabit.': 'Shape into crescents.',
  'Panggang, taburi gula donat.': 'Bake, dust with powdered sugar.',
  'Kocok margarin dan telur.': 'Beat margarine and eggs.',
  'Masukkan tepung, keju.': 'Add flour, cheese.',
  'Cetak persegi panjang.': 'Mold into rectangles.',
  'Panggang hingga matang.': 'Bake until done.',
  'Kocok margarin, gula, telur.': 'Beat margarine, sugar, eggs.',
  'Masukkan tepung.': 'Add flour.',
  'Isi selai nanas, bulatkan.': 'Fill with pineapple jam, shape into balls.',
  'Oles kuning telur, panggang.': 'Brush with egg yolk, bake.',
  'Cuci ketan, rendam.': 'Wash glutinous rice, soak.',
  'Masukkan ke bambu berlapis daun.': 'Put into bamboo lined with leaves.',
  'Panggang sambil diputar.': 'Grill while rotating.',
  'Sajikan dengan rendang.': 'Serve with rendang.',
  'Kukus ketan matang.': 'Steam glutinous rice until done.',
  'Rebus gula merah dan santan.': 'Boil palm sugar and coconut milk.',
  'Campur ketan, tuang ke loyang.': 'Mix with glutinous rice, pour into pan.',
  'Potong setelah mengeras.': 'Cut after hardening.',
  'Siapkan gelas.': 'Prepare glass.',
  'Masukkan tape, nangka, kelapa.': 'Add fermented cassava, jackfruit, coconut.',
  'Tambahkan es serut.': 'Add shaved ice.',
  'Tuang SKM dan sirup.': 'Pour sweetened condensed milk and syrup.',
  'Rebus rempah dengan air.': 'Boil spices with water.',
  'Tambahkan gula.': 'Add sugar.',
  'Saring, dinginkan.': 'Strain, cool.',
  'Sajikan dengan es batu.': 'Serve with ice cubes.',
  'Bakar jahe, memarkan.': 'Roast ginger, crush.',
  'Rebus semua rempah.': 'Boil all spices.',
  'Saring ke gelas.': 'Strain into glass.',
  'Tambahkan gula batu.': 'Add rock sugar.',
  'Buat adonan ronde.': 'Make ronde dough.',
  'Isi kacang dan gula.': 'Fill with peanuts and sugar.',
  'Rebus hingga mengapung.': 'Boil until floating.',
  'Sajikan dengan kuah jahe.': 'Serve with ginger broth.',
  'Bakar jahe.': 'Roast ginger.',
  'Rebus semua rempah.': 'Boil all spices.',
  'Saring ke gelas.': 'Strain into glass.',
  'Tambahkan gula merah.': 'Add palm sugar.',
  'Rebus jahe dan serai.': 'Boil ginger and lemongrass.',
  'Siapkan mangkuk.': 'Prepare bowl.',
  'Masukkan kacang, kismis.': 'Add peanuts, raisins.',
  'Tuang kuah jahe.': 'Pour ginger broth.',
  'Saring air nira.': 'Strain palm sap.',
  'Beri perasan jeruk nipis.': 'Add lime juice.',
  'Sajikan dengan es batu.': 'Serve with ice cubes.',
  'Campur tepung, santan. Masak.': 'Mix flour, coconut milk. Cook.',
  'Cetak bulat ke air es.': 'Mold into balls, drop into ice water.',
  'Sajikan dengan sirup.': 'Serve with syrup.',
  'Campur tepung, masak.': 'Mix flour, cook.',
  'Cetak cendol ke air es.': 'Press cendol into ice water.',
  'Sajikan dengan es serut.': 'Serve with shaved ice.',
  'Keruk daging kelapa.': 'Scoop coconut flesh.',
  'Campur dengan air kelapa.': 'Mix with coconut water.',
  'Tambahkan SKM dan sirup.': 'Add sweetened condensed milk and syrup.',
  'Haluskan bumbu. Lumuri ayam.': 'Grind spices. Coat chicken.',
  'Bungkus daun pisang.': 'Wrap in banana leaves.',
  'Kukus 1 jam.': 'Steam for 1 hour.',
  'Panggang 30 menit.': 'Grill for 30 minutes.',
  'Goreng ayam tepung.': 'Fry battered chicken.',
  'Haluskan cabe, bawang.': 'Grind chili, garlic.',
  'Siram minyak panas.': 'Pour hot oil.',
  'Geprek ayam di atas sambal.': 'Smash chicken on top of chili sauce.',
  'Haluskan bumbu.': 'Grind spices.',
  'Rebus ayam dengan air kelapa.': 'Boil chicken in coconut water.',
  'Goreng sebentar.': 'Fry briefly.',
  'Sajikan dengan sambal.': 'Serve with chili sauce.',
  'Rebus jengkol hingga empuk.': 'Boil jengkol until tender.',
  'Tumis bumbu halus.': 'Sauté ground spices.',
  'Masukkan santan dan jengkol.': 'Add coconut milk and jengkol.',
  'Masak hingga kental.': 'Cook until thickened.',
  'Rebus daging, iris tipis.': 'Boil beef, slice thinly.',
  'Pukul hingga pipih.': 'Pound until flattened.',
  'Goreng kering.': 'Fry until crispy.',
  'Tumis dengan bumbu halus.': 'Sauté with ground spices.',
  'Cuci usus bersih.': 'Clean intestines thoroughly.',
  'Tumis bumbu.': 'Sauté spices.',
  'Masukkan santan dan usus.': 'Add coconut milk and intestines.',
  'Masak hingga empuk.': 'Cook until tender.',
  'Potong daging.': 'Cut beef.',
  'Tumis bumbu halus.': 'Sauté ground spices.',
  'Masukkan daging dan santan.': 'Add beef and coconut milk.',
  'Masak hingga kuah mengental.': 'Cook until sauce thickens.',
  'Haluskan bumbu.': 'Grind spices.',
  'Tumis, tambahkan air.': 'Sauté, add water.',
  'Masukkan ikan.': 'Add fish.',
  'Masak hingga matang.': 'Cook until done.',
  'Tumis bumbu halus.': 'Sauté ground spices.',
  'Masukkan tempoyak.': 'Add fermented durian.',
  'Tambahkan ikan.': 'Add fish.',
  'Masak hingga matang.': 'Cook until done.',
  'Tumis bumbu dengan kari.': 'Sauté spices with curry.',
  'Masukkan daging dan udang.': 'Add beef and shrimp.',
  'Masukkan mie.': 'Add noodles.',
  'Sajikan dengan tauge.': 'Serve with bean sprouts.',
  'Potong daging dan nangka.': 'Cut beef and jackfruit.',
  'Tumis bumbu.': 'Sauté spices.',
  'Masukkan daging dan air.': 'Add beef and water.',
  'Masak hingga empuk.': 'Cook until tender.',
  'Rebus daging hingga empuk.': 'Boil beef until tender.',
  'Haluskan bumbu.': 'Grind spices.',
  'Masukkan ke kaldu.': 'Add to broth.',
  'Sajikan dengan daun bawang.': 'Serve with spring onions.',
  'Rebus ayam, suwir.': 'Boil chicken, shred.',
  'Haluskan bumbu.': 'Grind spices.',
  'Masukkan ke kaldu.': 'Add to broth.',
  'Sajikan dengan pelengkap.': 'Serve with garnishes.',
  'Iris daging tipis.': 'Slice meat thinly.',
  'Tumis bumbu.': 'Sauté spices.',
  'Masukkan daging dan kecap.': 'Add meat and sweet soy sauce.',
  'Masukkan kol dan tomat.': 'Add cabbage and tomatoes.',
  'Goreng oncom, hancurkan.': 'Fry oncom, crumble.',
  'Haluskan bumbu.': 'Grind spices.',
  'Campur nasi dengan bumbu.': 'Mix rice with spices.',
  'Sajikan dengan tempe goreng.': 'Serve with fried tempeh.',
  'Haluskan kacang, cabe.': 'Grind peanuts, chili.',
  'Tata ketupat, tahu, tauge.': 'Arrange rice cake, tofu, bean sprouts.',
  'Siram bumbu kacang.': 'Pour peanut sauce.',
  'Campur tepung, santan. Diamkan.': 'Mix flour, coconut milk. Let rest.',
  'Panaskan cetakan.': 'Heat molds.',
  'Tuang adonan.': 'Pour batter.',
  'Beri topping.': 'Add topping.',
  'Buat dadar tipis.': 'Make thin crepe.',
  'Masak isian kelapa.': 'Cook coconut filling.',
  'Isi dadar, gulung.': 'Fill crepe, roll.',
  'Kukus ketan.': 'Steam glutinous rice.',
  'Tumis ayam suwir.': 'Sauté shredded chicken.',
  'Bentuk ketan berisi ayam.': 'Shape glutinous rice with chicken filling.',
  'Masak aron.': 'Cook rice partially.',
  'Tumis daging cincang.': 'Sauté minced beef.',
  'Bentuk lonjong berisi daging.': 'Shape into ovals with beef filling.',
  'Campur tepung dengan air.': 'Mix flour with water.',
  'Isi cetakan dengan gula.': 'Fill molds with sugar.',
  'Kukus hingga matang.': 'Steam until done.',
  'Masak tepung hingga kental.': 'Cook flour until thick.',
  'Beri pewarna, bentuk bulat.': 'Add coloring, shape into balls.',
  'Gulingkan di kelapa.': 'Roll in grated coconut.',
  'Kukus singkong, haluskan.': 'Steam cassava, mash.',
  'Campur gula dan vanili.': 'Mix sugar and vanilla.',
  'Bentuk, taburi kelapa.': 'Shape, sprinkle with coconut.',
  'Kukus adonan tepung.': 'Steam flour mixture.',
  'Isi kacang tanah.': 'Fill with peanuts.',
  'Gulingkan di maizena.': 'Roll in cornstarch.',
  'Kocok telur dan gula.': 'Beat eggs and sugar.',
  'Masukkan tepung, susu.': 'Add flour, milk.',
  'Tuang ke cetakan.': 'Pour into molds.',
  'Kocok telur dan gula.': 'Beat eggs and sugar.',
  'Masukkan tepung, santan.': 'Add flour, coconut milk.',
  'Diamkan, tuang ke cetakan.': 'Let rest, pour into molds.',
  'Buat kulit.': 'Make wrapper.',
  'Isi kacang hijau.': 'Fill with mung beans.',
  'Panggang dalam oven.': 'Bake in oven.',
  'Campur semua bahan.': 'Mix all ingredients.',
  'Panggang di teflon.': 'Grill on teflon.',
  'Masak hingga matang.': 'Cook until done.',
};

function slugify(name) {
  return name.toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .trim();
}

function translateIngredient(ing) {
  // Try exact match first
  if (ingredientTranslations[ing]) {
    return ingredientTranslations[ing];
  }
  
  // Try partial match
  for (const [indo, eng] of Object.entries(ingredientTranslations)) {
    if (ing.includes(indo) || indo.includes(ing)) {
      return eng;
    }
  }
  
  // Return original if no translation found
  return ing;
}

function translateInstruction(inst) {
  // Try exact match first
  if (instructionTranslations[inst]) {
    return instructionTranslations[inst];
  }
  
  // Try partial match
  for (const [indo, eng] of Object.entries(instructionTranslations)) {
    if (inst.includes(indo) || indo.includes(inst)) {
      return eng;
    }
  }
  
  // Return original if no translation found
  return inst;
}

function generateDescription(name, kategori, origin) {
  const descriptions = {
    'makanan-berat': `A beloved main dish from ${origin || 'Indonesia'}, featuring authentic flavors passed down through generations.`,
    'sup-soto': `A comforting soup from ${origin || 'Indonesia'}, rich with traditional spices and aromatic herbs.`,
    'sate-panggang': `A grilled delicacy from ${origin || 'Indonesia'}, expertly seasoned and cooked over charcoal.`,
    'jajanan': `A traditional snack from ${origin || 'Indonesia'}, offering a perfect balance of sweet and savory flavors.`,
    'minuman': `A refreshing traditional drink from ${origin || 'Indonesia'}, perfect for any occasion.`,
  };
  return descriptions[kategori] || `An authentic recipe from ${origin || 'Indonesia'}.`;
}

// Transform recipes
const newRecipes = recipes.map(r => {
  const engName = nameTranslations[r.nama] || r.nama;
  const slug = slugify(engName);
  const origin = originMap[r.nama] || 'Indonesia';
  
  return {
    id: r.id,
    slug: slug,
    title: engName,
    description: generateDescription(engName, r.kategori, origin),
    image: r.gambar,
    kategori: r.kategori,
    waktu: r.waktu,
    porsi: r.porsi.replace('orang', 'people').replace('buah', 'pieces').replace('gelas', 'glasses').replace('loyang', 'pans').replace('potong', 'pieces'),
    kesulitan: difficultyMap[r.kesulitan] || r.kesulitan,
    rating: r.rating,
    origin: origin,
    ingredients: r.bahan.map(translateIngredient),
    instructions: r.langkah.map(translateInstruction),
    tips: `Enjoy this authentic ${engName} from ${origin}. Best served fresh and hot.`,
  };
});

// Generate TypeScript
let ts = `import { Recipe } from "@/types";\n\nexport const recipes: Recipe[] = [\n`;

newRecipes.forEach((r, i) => {
  ts += `  {\n`;
  ts += `    id: ${r.id},\n`;
  ts += `    slug: "${r.slug}",\n`;
  ts += `    title: "${r.title.replace(/"/g, '\\"')}",\n`;
  ts += `    description: "${r.description.replace(/"/g, '\\"')}",\n`;
  ts += `    image: "${r.image}",\n`;
  ts += `    kategori: "${r.kategori}",\n`;
  ts += `    waktu: ${r.waktu},\n`;
  ts += `    porsi: "${r.porsi.replace(/"/g, '\\"')}",\n`;
  ts += `    kesulitan: "${r.kesulitan}",\n`;
  ts += `    rating: ${r.rating},\n`;
  ts += `    origin: "${r.origin.replace(/"/g, '\\"')}",\n`;
  ts += `    ingredients: [\n`;
  r.ingredients.forEach(ing => {
    ts += `      "${ing.replace(/"/g, '\\"')}",\n`;
  });
  ts += `    ],\n`;
  ts += `    instructions: [\n`;
  r.instructions.forEach(inst => {
    ts += `      "${inst.replace(/"/g, '\\"')}",\n`;
  });
  ts += `    ],\n`;
  ts += `    tips: "${r.tips.replace(/"/g, '\\"')}",\n`;
  ts += `  },\n`;
});

ts += `];\n\n`;
ts += `export const getRecipeBySlug = (slug: string): Recipe | undefined =>\n`;
ts += `  recipes.find((r) => r.slug === slug);\n\n`;
ts += `export const getRecipeById = (id: number): Recipe | undefined =>\n`;
ts += `  recipes.find((r) => r.id === id);\n\n`;
ts += `export const searchRecipes = (query: string): Recipe[] => {\n`;
ts += `  const q = query.toLowerCase();\n`;
ts += `  return recipes.filter(\n`;
ts += `    (r) =>\n`;
ts += `      r.title.toLowerCase().includes(q) ||\n`;
ts += `      r.description.toLowerCase().includes(q) ||\n`;
ts += `      r.origin.toLowerCase().includes(q) ||\n`;
ts += `      r.ingredients.some((i) => i.toLowerCase().includes(q))\n`;
ts += `  );\n`;
ts += `};\n\n`;
ts += `export const filterByKategori = (kategori: string): Recipe[] => {\n`;
ts += `  if (kategori === "all") return recipes;\n`;
ts += `  return recipes.filter((r) => r.kategori === kategori);\n`;
ts += `};\n`;

fs.writeFileSync('/home/liveuser/nusantaraeats/src/data/recipes.ts', ts);
console.log(`✅ Translated ${newRecipes.length} recipes with full English ingredients and instructions`);
console.log(`📁 Saved to src/data/recipes.ts`);
