const fs = require('fs');

// Recipe-specific data based on actual Indonesian culinary knowledge
const recipeSpecificData = {
  // === MAIN DISHES (makanan-berat) ===
  "rendang": {
    history: "Rendang originates from the Minangkabau highlands of West Sumatra, Indonesia. The dish was created as a preservation method — cooking meat in coconut milk and spices for hours until the liquid evaporates, creating a dry, concentrated coating that acts as a natural preservative. Historically, Minangkabau women prepared rendang for special ceremonies, weddings, and the Hajj pilgrimage. The slow cooking process was practical: without refrigeration, rendang could last weeks at room temperature, making it perfect for long journeys. The dish gained international recognition when it was voted the world's most delicious food by CNN Travel in 2011 and 2017. In Minangkabau culture, rendang symbolizes the '9 jambi' (9 ingredients) that represent the core values of Minangkabau society: musyawarah (deliberation), mufakat (consensus), and gotong royong (mutual cooperation).",
    culturalSignificance: "In Minangkabau tradition, rendang is mandatory at every major life event — births, circumcisions, weddings, and funerals. The preparation is a communal activity where women gather to grind spices and stir the pot for hours, strengthening social bonds. The slow cooking represents patience and dedication, values deeply cherished in Minangkabau culture. When served at weddings, rendang symbolizes prosperity and abundance. During Ramadan, families prepare large batches for iftar meals. The dish also serves as a gift between families, representing respect and hospitality. In modern Indonesia, rendang has become a symbol of national identity, appearing on airline menus, diplomatic receptions, and international food festivals.",
    variations: "Traditional Minangkabau rendang uses only beef, but modern variations include chicken, duck, and even jackfruit for vegetarian versions. The original 'rendang kering' (dry rendang) is the most authentic — dark, almost black, with very little sauce remaining. 'Rendang basah' (wet rendang) is a newer style with more gravy, popular in restaurants outside West Sumatra. Kalio, a related dish, is essentially rendang in its early cooking stage before the coconut milk fully reduces. In Malaysia, rendang is often drier and spicier, while Javanese versions tend to be sweeter with more palm sugar. Premium versions use wagyu beef or short ribs for a more luxurious texture.",
    nutrition: "Rendang is nutritionally dense, providing approximately 350-450 calories per serving. The beef provides 25-35g of protein per serving, essential for muscle maintenance and growth. Turmeric, a key ingredient, contains curcumin — a powerful anti-inflammatory compound. Galangal and ginger aid digestion and boost immunity. Coconut milk provides healthy fats including lauric acid, which has antimicrobial properties. The slow cooking process actually increases the bioavailability of nutrients, making them easier for the body to absorb. For those watching calories, using lean cuts of beef and reducing coconut milk can lower the calorie count while maintaining authentic flavor.",
    pairing: "Traditional accompaniments include steamed white rice, which balances the rich, intense flavors of rendang. In Minangkabau cuisine, rendang is part of a 'nasi Padang' spread alongside gulai, kalio, and various vegetables. For beverages, es kelapa muda (young coconut ice) provides refreshing contrast to the spicy richness. Teh tawar (plain tea) cleanses the palate between bites. For special occasions, rendang pairs beautifully with lemang (glutinous rice cooked in bamboo). Wine enthusiasts might try an off-dry Riesling or Gewürztraminer, which complement the complex spice profile. Bintang beer is a casual Indonesian pairing that works surprisingly well with the bold flavors.",
    faq: [
      { q: "Why is rendang cooked for 4 hours?", a: "The extended cooking time allows the coconut milk to fully reduce and the spices to deeply penetrate the meat. This process creates the signature dry, concentrated coating that preserves the meat naturally. The Maillard reaction during this long cooking creates hundreds of flavor compounds that give rendang its distinctive taste." },
      { q: "What cut of beef is best for rendang?", a: "Beef chuck, brisket, or shank are ideal for rendang. These cuts have enough collagen and fat to stay moist during the long cooking process. Lean cuts like tenderloin will become dry and tough. The connective tissue in chuck breaks down over 4 hours, creating tender, flavorful meat." },
      { q: "Can rendang be frozen?", a: "Yes! Rendang freezes exceptionally well for up to 3 months. The concentrated coconut milk coating acts as a natural preservative. In fact, many Minangkabau families make rendang in large batches specifically for freezing. The flavors actually improve after freezing as the spices continue to meld." },
      { q: "Why is my rendang not turning dark?", a: "The dark color comes from the caramelization of coconut milk and the Maillard reaction during extended cooking. If your rendang isn't darkening, continue cooking on low heat — the transformation happens in the final hour. Also, use thick coconut milk (santan kental) for better caramelization." },
      { q: "Is rendang spicy?", a: "Traditional Minangkabau rendang has moderate heat from red chilies. The spice level can be adjusted by varying the amount of chili peppers. Most of the flavor comes from the complex spice paste, not just heat." },
      { q: "What's the difference between rendang and kalio?", a: "Kalio is essentially rendang in its early cooking stage — when there's still plenty of gravy. Rendang is the final stage where all the liquid has evaporated and the meat is coated in a thick, dry spice paste. Both are delicious, but rendang has more concentrated flavors." },
    ],
  },
  "soto-betawi": {
    history: "Soto Betawi is the signature soup of Jakarta's Betawi people, the original inhabitants of the city before Dutch colonization. The dish evolved from Javanese soto traditions but incorporated Dutch colonial influences — the use of fresh milk or coconut milk gives it a distinctive creamy white appearance unlike other Indonesian sotos. The Betawi people, descendants of the ancient Sundanese kingdom of Pajajaran, developed this rich, hearty soup to sustain laborers working in the hot Jakarta climate. The dish became popular in the 19th century when Jakarta (then Batavia) was a major trading port, and vendors sold soto Betawi from street carts to dockworkers and traders. Today, it remains a beloved comfort food, especially during Jakarta's rainy season.",
    culturalSignificance: "Soto Betawi holds a special place in Jakarta's culinary identity as one of the few dishes uniquely attributed to the Betawi people. In Betawi culture, the dish is served during important family gatherings, particularly during Lebaran (Eid al-Fitr) when families reunite. The rich, creamy broth represents abundance and togetherness. Street vendors selling soto Betawi are an iconic part of Jakarta's culinary landscape, with some recipes passed down through four or five generations. The dish also reflects Jakarta's role as a melting pot — combining Javanese, Sundanese, and Chinese culinary influences.",
    variations: "Traditional soto Betawi uses either fresh milk (susu sapi) or coconut milk (santan), creating two distinct styles. The milk version is creamier and milder, while coconut milk adds richness and a subtle sweetness. Some versions add potatoes for extra heartiness, while purists keep it simple with just beef and broth. Offal lovers can find versions with tripe, liver, and intestines. The modern 'soto Betawi kuah susu' trend uses fresh milk for a lighter, more contemporary flavor. In some areas, soto Betawi is served with ketupat (rice cakes) instead of regular rice.",
    nutrition: "Soto Betawi provides approximately 250-350 calories per serving, making it a lighter option compared to rendang. The beef provides 20-25g of protein, while the broth is rich in minerals from the bones and spices. Turmeric and galangal offer anti-inflammatory benefits. The coconut milk version provides healthy fats and lauric acid. The broth contains gelatin from the bones, which supports joint and gut health. Compared to Western beef soups, soto Betawi uses significantly less fat while delivering complex, layered flavors from the aromatic spices.",
    pairing: "Soto Betawi is traditionally served with steamed rice or ketupat (compressed rice cakes). Condiments include sambal for heat, lime wedges for brightness, and crispy fried shallots for texture. Koya — a savory powder made from crushed fried garlic and dried shrimp — is a signature accompaniment that adds umami depth. For beverages, es jeruk (iced orange juice) or es kelapa muda (young coconut ice) provide refreshing contrast. The creamy broth pairs well with light, acidic drinks that cut through the richness.",
    faq: [
      { q: "What makes soto Betawi broth special?", a: "The broth gets its distinctive creamy white appearance from fresh milk or coconut milk, unlike other Indonesian sotos that use clear broth. The combination of beef bones, turmeric, and aromatic spices creates a complex, layered flavor that's both comforting and sophisticated." },
      { q: "Can I use beef broth instead of bones?", a: "While beef broth works, using bones creates a richer, more gelatinous broth with deeper flavor. The collagen from the bones gives the soup its characteristic body. If using broth, add a few bones for better results." },
      { q: "What is koya?", a: "Koya is a savory condiment made from crushed fried garlic and dried shrimp (ebi). It's unique to soto Betawi and adds a crunchy, umami-rich texture that complements the creamy broth." },
    ],
  },
  "rawon": {
    history: "Rawon is a dark, aromatic beef soup from East Java, famous for its deep black broth colored by kluwek nuts (Pangium edule). The dish originated in the royal courts of Majapahit Empire (1293-1527), where it was served to nobility and visiting dignitaries. The kluwek nut, which grows only in Southeast Asian tropical forests, was considered a luxury ingredient due to its labor-intensive preparation — the nuts must be fermented for weeks before use. In the Majapahit era, rawon symbolized power and mystery, its dark color representing the cosmic forces of the underworld. The dish survived the fall of Majapahit and became a beloved street food in Surabaya, East Java's largest city. Today, rawon is most associated with Surabaya and Malang, where it's served for breakfast and lunch.",
    culturalSignificance: "In Javanese culture, rawon's dark color is associated with spiritual power and protection. Historically, it was served to warriors before battle for courage and strength. During the Islamic fasting month of Ramadan, rawon is a popular iftar dish in East Java, its rich broth providing sustenance after a day of fasting. The dish is also served at important ceremonies, including weddings and circumcisions. In Surabaya, rawon vendors are cultural landmarks — some have been operating for over a century, their recipes closely guarded family secrets. The 'rawon setan' (devil's rawon) variant, known for extreme spiciness, has become a cultural phenomenon in Malang.",
    variations: "Traditional rawon uses beef shank, but modern versions include oxtail, ribs, and even tongue. The classic East Javanese version is mild with subtle spice, while Malang's 'rawon setan' adds intense heat. Some versions include potato chunks for heartiness, while purists keep it simple. The broth can vary from thin and clear to thick and rich, depending on the cook's preference. Premium versions use wagyu beef or short ribs. In Jakarta, some restaurants serve rawon with nasi uduk (coconut rice) instead of plain white rice.",
    nutrition: "Rawon provides approximately 280-350 calories per serving, making it a moderate-calorie option. The beef delivers 22-28g of protein, while the kluwek nuts provide healthy fats and unique antioxidants not found in other spices. The broth is rich in minerals from the bones, and the turmeric adds anti-inflammatory benefits. Kluwek contains compounds that may support brain health. The dish is naturally gluten-free and can be made dairy-free. For those watching sodium, the broth can be made with less salt while maintaining flavor through the aromatic spices.",
    pairing: "Rawon is traditionally served with steamed white rice, which absorbs the rich, dark broth. In East Java, it's often accompanied by tauge (bean sprouts) and salted eggs (telur asin), which add contrasting textures and flavors. Kerupuk (shrimp crackers) provide crunch. For beverages, es kelapa muda or es teh manis (sweet iced tea) are popular choices. The deep, complex flavors of rawon also pair well with a cold Bintang beer or a crisp white wine.",
    faq: [
      { q: "Why is rawon black?", a: "Rawon gets its deep black color from kluwek nuts (Pangium edule), which are fermented for weeks before use. The fermentation process develops dark pigments that turn the broth jet black. Kluwek is unique to Southeast Asian cuisine and cannot be substituted with other ingredients." },
      { q: "What does kluwek taste like?", a: "Kluwek has a complex, earthy flavor with notes of chocolate, coffee, and truffle. It adds a deep umami quality to rawon that's impossible to replicate. The taste is often described as 'Indonesian black truffle.'" },
      { q: "Is rawon spicy?", a: "Traditional rawon has mild to moderate spice. The heat comes from chili peppers, not the kluwek. Malang's 'rawon setan' version is intentionally very spicy, but classic East Javanese rawon is more about depth of flavor than heat." },
    ],
  },
  "pempek": {
    history: "Pempek is a savory fish cake delicacy from Palembang, South Sumatra, originating from the ancient Srivijaya Empire (7th-13th century). The dish was created by Chinese immigrants who settled in Palembang and combined their fish paste-making techniques with local Indonesian ingredients. The name 'pempek' is believed to come from 'pek-pek,' the sound of the fish cake being sliced. The iconic 'cuko' (vinegar sauce) was added later, creating the sweet-sour-spicy flavor profile that defines pempek today. Historically, pempek was a breakfast food sold by vendors who carried bamboo baskets through the streets. The dish gained national popularity in the 20th century and is now considered Palembang's most famous culinary export.",
    culturalSignificance: "Pempek is inseparable from Palembang's identity — the city is often called 'Kota Pempek' (Pempek City). In Palembang culture, pempek is served at every major celebration, from weddings to religious holidays. The preparation is a family activity, with recipes passed down through generations. The cuko sauce represents the perfect balance of flavors that Palembang people value in their cuisine. During Ramadan, pempek vendors see a surge in business as families break their fast with this beloved dish. The dish has become a symbol of Palembang pride, and locals often bring pempek as a gift when traveling.",
    variations: "The most famous types are pempek kapal selam (submarine-shaped with egg inside), pempek lenjer (long cylindrical), and pempek adaan (round, fried balls). The cuko sauce varies between families — some prefer it sweeter, others more spicy. Modern variations include pempek with cheese, chocolate, or even ice cream fillings. The fish used can be tenggiri (Spanish mackerel), which is traditional, or other firm white fish. Some vendors offer 'pempek telur' (egg pempek) and 'pempek tahu' (tofu pempek) for variety.",
    nutrition: "Pempek provides approximately 200-300 calories per serving, depending on the type and size. The fish provides lean protein (15-20g per serving), while the tapioca starch adds carbohydrates for energy. The cuko sauce is low in calories but high in flavor. The dish is naturally dairy-free and can be made gluten-free with proper tapioca starch. The fish provides omega-3 fatty acids, which support heart health. For a lighter version, pempek can be steamed instead of fried.",
    pairing: "Pempek is always served with cuko sauce — the sweet, sour, and spicy vinegar-based condiment is essential. In Palembang, it's accompanied by diced cucumber and noodle strips. For beverages, es teh manis (sweet iced tea) or es kelapa muda provide refreshing contrast to the rich fish cakes. Some Palembang locals enjoy pempek with es kacang merah (red bean ice) for a traditional combination. The dish is typically eaten as a snack or light meal, not as part of a larger spread.",
    faq: [
      { q: "What fish is used in pempek?", a: "Traditional pempek uses tenggiri (Spanish mackerel), which has a firm texture and mild flavor that holds up well when ground and shaped. Other firm white fish like tuna or mackerel can substitute, but tenggiri is considered authentic." },
      { q: "What is cuko?", a: "Cuko is the signature sweet-sour-spicy sauce served with pempek. Made from vinegar, palm sugar, chili, and garlic, it provides the perfect balance of flavors that complements the savory fish cakes. Every family has their own secret ratio." },
      { q: "Can pempek be frozen?", a: "Yes! Uncooked pempek freezes well for up to 2 months. Place them on a baking sheet in a single layer until frozen, then transfer to a bag. Cook from frozen, adding a few extra minutes to the boiling time." },
    ],
  },
  "gudeg": {
    history: "Gudeg is a sweet dish from Yogyakarta made from young jackfruit (nangka muda) cooked slowly in coconut milk and palm sugar. The dish originated in the Mataram Sultanate (16th-18th century), where it was served in the royal court of Keraton Yogyakarta. The slow cooking process — up to 8 hours — was a luxury available only to the royal family and wealthy households. After Indonesian independence, gudeg became accessible to the masses and is now Yogyakarta's signature dish. The city is often called 'Kota Gudeg' (Gudeg City), and vendors selling gudeg from wooden carts are an iconic sight. The dish represents the patience and artistry of Javanese cuisine.",
    culturalSignificance: "Gudeg is the culinary symbol of Yogyakarta, representing the city's royal heritage and Javanese cultural identity. In Yogyakarta, gudeg is served at every important occasion — from births to weddings to religious ceremonies. The preparation is a communal activity, with families gathering to prepare large batches. During Lebaran (Eid al-Fitr), gudeg is a must-have dish on the table. The slow cooking process reflects Javanese values of patience and mindfulness. In modern Yogyakarta, gudeg is both a cultural treasure and an economic driver, supporting thousands of vendors and restaurants.",
    variations: "Traditional gudeg is sweet with a thick, dark sauce, but variations exist across Java. Yogyakarta gudeg tends to be sweeter and drier, while Solo (Surakarta) gudeg is slightly lighter. 'Gudeg kering' (dry gudeg) has very little sauce, while 'gudeg basah' (wet gudeg) has more gravy. Modern variations include gudeg with chicken, beef, or even jackfruit seeds. Some restaurants offer 'gudeg mercon' (firecracker gudeg) with intense spiciness. The dish is traditionally served with krecek (spicy beef skin stew), ayam opor (chicken in coconut milk), and telur pindang (tea-stained eggs).",
    nutrition: "Gudeg provides approximately 200-300 calories per serving, making it a moderate-calorie option. Young jackfruit is low in calories but high in fiber, supporting digestive health. The coconut milk provides healthy fats, while the palm sugar adds natural sweetness. The dish contains vitamins A and C from the jackfruit, plus minerals from the spices. Teak leaves, traditionally used in cooking, may have additional health benefits. For a lighter version, reduce coconut milk and palm sugar while maintaining the essential flavors.",
    pairing: "Gudeg is traditionally served with nasi putih (steamed white rice) and accompanied by krecek (spicy beef skin stew), ayam opor (chicken in coconut milk), and telur pindang (tea-stained eggs). For beverages, es dawet or es cendol provide sweet, cooling contrast. Teh tawar (plain tea) cleanses the palate. In Yogyakarta, gudeg is often eaten with tempe orek (sweet fried tempeh) and sambal goreng krecek for a complete meal.",
    faq: [
      { q: "Why does gudeg take so long to cook?", a: "The 8-hour cooking time is essential for the young jackfruit to absorb the coconut milk and palm sugar flavors. The slow process also softens the fibrous jackfruit to a tender, almost meat-like texture. Rushing this process results in tough, under-flavored jackfruit." },
      { q: "What makes Yogyakarta gudeg different?", a: "Yogyakarta gudeg is typically sweeter and drier than versions from other cities. It uses teak leaves (daun jati) during cooking, which adds a distinctive color and subtle flavor. The slow reduction of coconut milk creates a thick, caramelized coating." },
      { q: "Can gudeg be made vegetarian?", a: "Gudeg is already vegetarian! The dish uses only jackfruit, coconut milk, palm sugar, and spices. The accompanying dishes (krecek, ayam opor) are separate and can be omitted for a fully vegetarian meal." },
    ],
  },
  "coto-makassar": {
    history: "Coto Makassar is a rich, peanut-based beef soup from Makassar, South Sulawesi. The dish originated from the Bugis and Makassar people, who have been trading spices and ingredients across the Indonesian archipelago for centuries. The use of ground peanuts in the broth reflects the influence of Chinese traders who introduced peanut-based sauces to the region. Traditionally, coto was a breakfast food for fishermen and market vendors, providing sustenance for a day of hard labor. The dish gained popularity across Indonesia in the 20th century and is now a staple of Makassar's culinary identity. Some of the oldest coto restaurants in Makassar have been operating for over 50 years.",
    culturalSignificance: "In Makassar culture, coto is more than just food — it's a social institution. Families gather at coto restaurants for breakfast, lunch, and dinner. The dish is served at major celebrations, including weddings and religious festivals. During Ramadan, coto is a popular iftar choice, its rich broth providing nourishment after fasting. The preparation is a source of pride for Makassar families, with each restaurant guarding its secret spice blend. Coto also represents Makassar's identity as a trading port, combining local ingredients with influences from across the archipelago.",
    variations: "Traditional coto uses beef offal (tripe, liver, intestines) alongside regular beef, creating a complex texture profile. Modern versions may use only beef for a cleaner taste. The peanut paste can vary from smooth to chunky, affecting the broth's thickness. Some versions add potatoes for extra heartiness. The condiments are essential — koya (garlic-shrimp powder), lime, sambal, and fried shallots each add a different dimension. In Makassar, coto is served with ketupat (compressed rice cakes) instead of regular rice.",
    nutrition: "Coto Makassar provides approximately 300-400 calories per serving, making it a hearty but balanced option. The beef and offal provide 25-30g of protein per serving, while the peanuts add healthy fats and additional protein. The broth is rich in minerals from the bones and spices. Turmeric and galangal offer anti-inflammatory benefits. The dish is naturally gluten-free. For those watching fat content, using lean cuts of beef and reducing peanut paste can lower calories while maintaining authentic flavor.",
    pairing: "Coto Makassar is traditionally served with ketupat (compressed rice cakes) or steamed white rice. Condiments are essential: koya (garlic-shrimp powder), lime wedges, sambal, and fried shallots. For beverages, es jeruk (iced orange juice) or es kelapa muda provide refreshing contrast. In Makassar, coto is often paired with pallubasa, another rich beef soup, for a truly indulgent meal.",
    faq: [
      { q: "What is in coto Makassar broth?", a: "The broth is made from beef bones simmered with ground peanuts, turmeric, galangal, and a blend of spices. The peanuts give it a creamy, nutty flavor unlike any other Indonesian soup." },
      { q: "What is koya?", a: "Koya is a savory condiment made from crushed fried garlic and dried shrimp (ebi). It's essential for coto Makassar, adding a crunchy, umami-rich texture that complements the creamy broth." },
      { q: "Is coto Makassar spicy?", a: "Traditional coto has mild spice. The heat comes from sambal, which is added to taste. The broth itself is rich and savory, not spicy." },
    ],
  },
  "mie-aceh": {
    history: "Mie Aceh (Aceh noodles) is a spicy stir-fried noodle dish from Aceh, the northernmost province of Sumatra. The dish reflects Aceh's position as a major trading port on the Spice Route, where Indian, Arab, and Chinese culinary influences merged with local traditions. The curry-like spices in mie aceh come from Indian traders who settled in Aceh centuries ago. The dish gained popularity in the 20th century as Acehnese migrants brought their culinary traditions to other parts of Indonesia. Today, mie aceh vendors are found across the archipelago, with each region adding its own touch to the recipe.",
    culturalSignificance: "In Aceh culture, mie aceh represents the province's rich trading history and multicultural identity. The dish is served at every major gathering, from family meals to community celebrations. During Ramadan, mie aceh is a popular iftar choice, its bold flavors satisfying hunger after a day of fasting. The preparation reflects Acehnese values of generosity and community — large portions are served to ensure everyone is well-fed. In modern Aceh, mie aceh is both a cultural symbol and an economic driver, supporting thousands of vendors and restaurants.",
    variations: "The most common versions are mie aceh goreng (fried) and mie aceh kuah (soup). The protein can be beef, seafood (shrimp, squid), or a combination. The spice level varies from mild to extremely spicy. Some versions add potatoes for extra heartiness. In Jakarta, mie aceh is often served with emping (melinjo nut crackers) and pickled vegetables. The noodles themselves are thick and yellow, similar to Chinese egg noodles but with a firmer texture.",
    nutrition: "Mie aceh provides approximately 400-500 calories per serving, making it a substantial meal. The noodles provide carbohydrates for energy, while the protein (beef or seafood) delivers 20-25g per serving. The curry spices contain anti-inflammatory compounds, and the tomatoes provide vitamin C. The dish is naturally dairy-free. For a lighter version, use less oil and more vegetables.",
    pairing: "Mie aceh is traditionally served on its own as a complete meal, but it pairs well with emping (melinjo nut crackers) for crunch and pickled vegetables for acidity. For beverages, es jeruk (iced orange juice) or es teh manis (sweet iced tea) provide refreshing contrast to the rich, spicy noodles.",
    faq: [
      { q: "What makes mie aceh different from other Indonesian noodles?", a: "Mie aceh uses a curry-like spice blend with cumin, coriander, and curry powder, reflecting Indian influence. The thick, yellow noodles and generous spice coating make it distinct from mie goreng or bakmi." },
      { q: "Is mie aceh very spicy?", a: "Mie aceh can range from mild to extremely spicy, depending on the vendor. Most versions have moderate heat from chili peppers. Ask for 'tidak pedas' (not spicy) if you prefer milder flavors." },
    ],
  },
  "ayam-taliwang": {
    history: "Ayam Taliwang is a spicy grilled chicken dish from Lombok, West Nusa Tenggara. The dish originated in the village of Taliwang, where locals developed a fiery chili paste to marinate and grill chicken. The recipe has been passed down through generations, with each family adding their own touch. Ayam taliwang gained popularity across Indonesia in the 1990s when Lombok's tourism industry brought attention to the island's cuisine. Today, it's considered Lombok's most famous culinary export and is served in restaurants across the archipelago.",
    culturalSignificance: "In Lombok culture, ayam taliwang represents the island's bold, straightforward culinary identity. The intense spiciness reflects the Sasak people's love of bold flavors. The dish is served at every major celebration, from weddings to religious festivals. The preparation is a communal activity, with families gathering to prepare the spice paste and grill the chicken. Ayam taliwang also represents Lombok's growing tourism economy, as visitors seek out the authentic dish.",
    variations: "Traditional ayam taliwang uses whole chickens grilled over charcoal, but modern versions use chicken pieces for convenience. The spice paste can vary from medium to extremely spicy. Some versions add coconut milk for richness, while purists keep it dry. The dish is often served with plecing kangkung (spicy water spinach) for a complete Lombok meal.",
    nutrition: "Ayam taliwang provides approximately 300-400 calories per serving, making it a moderate-calorie protein source. The chicken provides 25-30g of protein, while the chili paste adds metabolism-boosting capsaicin. The grilling method reduces fat compared to frying. For a healthier version, use skinless chicken and reduce oil in the spice paste.",
    pairing: "Ayam taliwang is traditionally served with steamed rice and plecing kangkung (spicy water spinach). For beverages, es kelapa muda or es jeruk provide cooling contrast to the intense spiciness.",
    faq: [
      { q: "How spicy is ayam taliwang?", a: "Ayam taliwang is known for its intense heat from bird's eye chilies (cabe rawit). The spice level can range from medium to extremely hot, depending on the vendor. It's not for the faint of heart!" },
      { q: "What is plecing kangkung?", a: "Plecing kangkung is a spicy water spinach dish served alongside ayam taliwang. Blanched water spinach is topped with a fiery chili-tomato sambal, creating a fresh, spicy contrast to the grilled chicken." },
    ],
  },
  "papeda": {
    history: "Papeda is a staple food from eastern Indonesia, particularly Papua and Maluku. Made from sago starch, it's a gluey, translucent porridge that serves as the base for many meals in the region. Sago palms grow abundantly in the tropical forests of eastern Indonesia, making papeda an accessible and sustainable food source. The dish has been eaten for thousands of years, long before rice cultivation reached the eastern islands. In traditional Papuan and Moluccan culture, sago processing is a community activity that strengthens social bonds.",
    culturalSignificance: "Papeda represents the self-sufficiency and resilience of eastern Indonesian communities. In Papuan culture, sago is considered a sacred plant, and papeda preparation is accompanied by traditional rituals. The dish is served at every major ceremony, from births to funerals. In Maluku, papeda is often served with ikan kuah kuning (fish in yellow turmeric broth), creating a complete, nutritious meal. The dish also represents the unique culinary identity of eastern Indonesia, distinct from the rice-based cuisines of Java and Sumatra.",
    variations: "Papeda can be made from different types of sago, affecting its texture and color. In Papua, it's typically thicker and more translucent, while Maluccan versions are slightly thinner. The accompaniments vary by region — fish, vegetables, and sambal are common. Some modern versions add turmeric for color or coconut milk for richness.",
    nutrition: "Papeda is naturally gluten-free and low in fat, making it a healthy staple. It provides carbohydrates for energy and contains some fiber from the sago. When served with fish and vegetables, it becomes a balanced meal with protein, vitamins, and minerals. Sago is also a sustainable food source, as sago palms require minimal processing and grow in poor soil conditions.",
    pairing: "Papeda is traditionally served with ikan kuah kuning (fish in yellow turmeric broth) and sambal. In Maluku, it's often accompanied by sayur paku (fern vegetables) and grilled fish. For beverages, water or fresh coconut water are common choices.",
    faq: [
      { q: "What does papeda taste like?", a: "Papeda has a neutral, starchy flavor similar to thick porridge or mochi. It's a blank canvas that takes on the flavors of the broth and condiments served with it." },
      { q: "How do you eat papeda?", a: "Papeda is traditionally eaten with bare hands or with two wooden sticks (garpu papeda) that twirl the sticky porridge into portions. It's scooped up with the broth and side dishes." },
    ],
  },
  "sate-madura": {
    history: "Sate Madura refers to the distinctive satay style from Madura, an island off the northeast coast of Java. Madura is famous throughout Indonesia for producing the best satay vendors, who travel across the archipelago to sell their grilled skewers. The Madurese satay tradition dates back centuries, with families passing down their secret peanut sauce recipes through generations. The island's sandy soil makes rice cultivation difficult, so livestock farming became the primary livelihood, leading to the development of satay as a way to cook and preserve meat.",
    culturalSignificance: "In Madurese culture, satay is more than food — it's a livelihood and a source of pride. Madurese satay vendors are known for their distinctive call, a rhythmic cry that echoes through neighborhoods at dusk. The preparation of the peanut sauce is a closely guarded family secret, with each vendor claiming theirs is the most authentic. During religious festivals and celebrations, satay is always present. The dish also represents the Madurese people's entrepreneurial spirit, as they travel far from home to share their culinary tradition.",
    variations: "Madurese satay typically uses chicken, but beef and mutton versions exist. The peanut sauce is the star — rich, slightly sweet, and complex. Some vendors add sweet soy sauce for extra depth. The grilling technique uses coconut shell charcoal for distinctive smoky flavor. In different regions, Madurese vendors adapt their recipes to local tastes, sometimes adding more spice or sweetness.",
    nutrition: "Sate Madura provides approximately 250-350 calories per serving, making it a moderate-calorie protein source. The chicken provides 20-25g of protein, while the peanut sauce adds healthy fats and additional protein. The grilling method reduces fat compared to frying. For a lighter version, use less peanut sauce and skip the sweet soy sauce.",
    pairing: "Sate Madura is traditionally served with lontong (compressed rice cakes) and extra peanut sauce. Pickled vegetables and sliced cucumber provide fresh contrast. For beverages, es teh manis or es kelapa muda are popular choices.",
    faq: [
      { q: "What makes Madurese satay different?", a: "Madurese satay is distinguished by its rich, complex peanut sauce and the use of coconut shell charcoal for grilling. The vendors travel across Indonesia, adapting their recipes to local tastes while maintaining the core Madurese flavors." },
      { q: "Why is Madurese satay so popular?", a: "Madurese satay vendors are known for their quality and consistency. They've perfected their craft over generations, and the combination of tender meat, smoky charcoal flavor, and rich peanut sauce creates an irresistible combination." },
    ],
  },
};

// Read recipes file
const content = fs.readFileSync('src/data/recipes.ts', 'utf8');

// Get all recipe slugs
const slugRegex = /slug:\s*"([^"]+)"/g;
const slugs = [];
let match;
while ((match = slugRegex.exec(content)) !== null) {
  slugs.push(match[1]);
}

console.log('Total recipes to process:', slugs.length);
console.log('Recipes with specific data:', Object.keys(recipeSpecificData).length);

// Check which recipes need updates
const needsUpdate = slugs.filter(slug => !recipeSpecificData[slug]);
console.log('Recipes needing generic content replacement:', needsUpdate.length);
console.log('');
console.log('First 10 needing update:', needsUpdate.slice(0, 10));
