name = "nusantaraeats"
compatibility_date = "2024-01-01"
pages_build_output_dir = "out"

# Cloudflare Account
account_id = "243dd09cf194815c3fce5ce09528167c"

# KV namespace for view counters
[[kv_namespaces]]
binding = "VIEWS_KV"
id = "7736b7450fc74eba80ab78f51068b3c6"
